[package]
name = "chelis-shell"
description = "Shell (.chb) metadata for the Chelis package system"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-deep.workspace = true
serde.workspace = true
bincode = "1"
semver.workspace = true

[lints]
workspace = true
