{
  pkgs,
  lib,
  root,
  contracts,
  cvc5,
  built,
  packages,
  apps,
}:
let
  escape = lib.escapeShellArg;
  shapeCheck =
    name: package: shape:
    let
      requiredChecks = lib.concatMapStringsSep "\n" (path: ''
        if [ ! -e "${package}/${path}" ]; then
          echo "${name} package is missing ${path}" >&2
          exit 1
        fi
      '') shape.required;
      forbiddenChecks = lib.concatMapStringsSep "\n" (path: ''
        if [ -e "${package}/${path}" ]; then
          echo "${name} package contains forbidden path ${path}" >&2
          exit 1
        fi
      '') shape.forbidden;
      executableCheck =
        if shape.allowedProductExecutables == [ ] then
          ''
            echo "${name} package contains undeclared product executable $relative" >&2
            exit 1
          ''
        else
          ''
            case "$relative" in
              ${lib.concatMapStringsSep "|" (path: escape path) shape.allowedProductExecutables}) ;;
              *)
                echo "${name} package contains undeclared product executable $relative" >&2
                exit 1
                ;;
            esac
          '';
    in
    pkgs.runCommand "${name}-package-shape" { nativeBuildInputs = [ pkgs.findutils ]; } ''
      assert_exact_inventory() {
        local package="$1"
        local package_name="$2"
        shift 2
        local actual
        local expected
        actual="$(find "$package" -mindepth 1 -printf '%P\n' | sort)"
        expected="$(printf '%s\n' "$@" | sort)"
        if [ "$actual" != "$expected" ]; then
          echo "$package_name package inventory differs from its exact contract" >&2
          printf 'expected:\n%s\nactual:\n%s\n' "$expected" "$actual" >&2
          return 1
        fi
      }

      assert_exact_inventory \
        ${escape package} \
        ${escape name} \
        ${lib.escapeShellArgs shape.inventory}
      ${requiredChecks}
      ${forbiddenChecks}
      if [ -d "${package}/bin" ]; then
        while IFS= read -r executable; do
          relative="''${executable#${package}/}"
          ${executableCheck}
        done < <(find "${package}/bin" -type f -perm -0100 -print)
      fi
      touch "$out"
    '';

  chelisShape = shapeCheck "chelis" packages.chelis contracts.packageShapes.chelis;
  runtimeShape =
    shapeCheck "chelis-runtime" packages.chelis-runtime
      contracts.packageShapes.chelis-runtime;
  chelisupShape = shapeCheck "chelisup" packages.chelisup contracts.packageShapes.chelisup;

  cvc5Dir = pkgs.runCommand "cvc5-dir-contract" { } ''
    test -f ${cvc5.dir}/cmake/version-base.cmake
    grep -F 'set(CVC5_LAST_RELEASE "${cvc5.version}")' ${cvc5.dir}/cmake/version-base.cmake
    test -f ${cvc5.dir}/include/cvc5/c/cvc5.h
    test -d ${cvc5.dir}/build/include
    test -f ${cvc5.dir}/build/src/libcvc5.a
    test -d ${cvc5.dir}/build/deps/lib
    touch "$out"
  '';

  appContract = pkgs.runCommand "chelis-app-contract" { } ''
    test ${escape apps.chelis.program} = ${escape "${packages.chelis}/bin/chelis"}
    test ${escape apps.chelisup.program} = ${escape "${packages.chelisup}/bin/chelisup"}
    test ${escape apps.default.program} = ${escape apps.chelis.program}
    touch "$out"
  '';

  lockParity =
    pkgs.runCommand "nix-lock-parity"
      {
        nativeBuildInputs = [ pkgs.python311 ];
      }
      ''
        python3 ${root}/scripts/check_nix_lock_parity.py \
          --flake-lock ${root}/flake.lock \
          --devenv-lock ${root}/devenv.lock
        touch "$out"
      '';
  crate2nixGeneration =
    let
      requiredWorkspaceMembers = [
        "chelis-cli"
        "chelis-runtime"
        "chelis-python"
        "chelis-runtime-identity-build"
        "chelisup"
      ];
      missingWorkspaceMembers = builtins.filter (
        name: !(builtins.hasAttr name built.cargoGraph.workspaceMembers)
      ) requiredWorkspaceMembers;
    in
    assert missingWorkspaceMembers == [ ];
    pkgs.runCommand "crate2nix-ifd-contract" { } ''
      test ${escape built.crate2nixVersion} = ${escape "0.15.0"}
      test -f ${built.generatedCargoNix}/default.nix
      test -f ${built.generatedCargoNix}/crate/Cargo-generated.nix
      grep -F '@generated by crate2nix 0.15.0' \
        ${built.generatedCargoNix}/crate/Cargo-generated.nix
      test ! -e ${root}/Cargo.nix
      touch "$out"
    '';

  platformBuildInputs = lib.optionals pkgs.stdenv.hostPlatform.isLinux [ pkgs.openblas ];
  compilerBehavior =
    pkgs.runCommand "chelis-compiler-behavior"
      {
        nativeBuildInputs = [
          pkgs.python311
          pkgs.stdenv.cc
        ]
        ++ platformBuildInputs;
      }
      ''
        export HOME="$TMPDIR/home"
        export CHELIS_RUNTIME_DIR="${packages.chelis}/lib"
        mkdir -p "$HOME"

        version_output="$(${packages.chelis}/bin/chelis --version 2>&1)"
        if [ "$version_output" != ${escape "chelis ${built.version}"} ]; then
          echo "unexpected chelis version output" >&2
          echo "expected: chelis ${built.version}" >&2
          echo "actual: $version_output" >&2
          exit 1
        fi
        ${packages.chelis}/bin/chelis --help >/dev/null

        cp -R ${built.source}/crates/chelis-cli/tests/fixtures/release_pipe_stage \
          "$TMPDIR/release-fixture"
        chmod -R u+w "$TMPDIR/release-fixture"
        cd "$TMPDIR/release-fixture"
        ${packages.chelis}/bin/chelis test tests

        cd "$TMPDIR"
        python3 ${root}/.github/scripts/verify_release_smt.py ${packages.chelis}/bin/chelis
        touch "$out"
      '';

  runtimeConsumer =
    pkgs.runCommand "chelis-runtime-consumer"
      {
        nativeBuildInputs = [ pkgs.stdenv.cc ] ++ platformBuildInputs;
      }
      ''
        cc -std=c11 -Wall -Wextra -Werror \
          -I${packages.chelis-runtime}/include \
          ${./tests/runtime-consumer.c} \
          ${packages.chelis-runtime}/lib/libchelis_runtime.a \
          ${
            if pkgs.stdenv.hostPlatform.isDarwin then
              "-framework Accelerate"
            else
              "-lopenblas -lm -lpthread -ldl"
          } \
          -o runtime-consumer
        ./runtime-consumer
        touch "$out"
      '';

  # Producer-only boundary: exact installed outputs are resolved from verified
  # compiler receipts, never from the distribution's first-found archive.
  runtimeIdentityMissingInput = pkgs.testers.testBuildFailure built.runtimeIdentityProducerControls.missingInputRuntimeCrate;
  runtimeIdentityProducers =
    pkgs.runCommand "runtime-identity-producers"
      {
        nativeBuildInputs = [ pkgs.python311 ];
      }
      ''
        observer=${built.identityObserver}/bin/chelis-runtime-identity-build
        # The installed observer and receipt closure must suffice on a machine
        # that never had a workspace checkout or compiler observation state.
        unset CHELIS_IDENTITY_WORKSPACE CHELIS_IDENTITY_STATE
        unset CHELIS_IDENTITY_DEPENDENCIES CHELIS_IDENTITY_DIRECT_DEPENDENCIES
        unset CHELIS_IDENTITY_BUILD_DEPENDENCIES CHELIS_IDENTITY_BUILD_SCRIPT
        export CHELIS_IDENTITY_PYTHON="${pkgs.python311}/bin/python3"
        mkdir installed-consumer
        cd installed-consumer
        runtime="$("$observer" producer-artifact --lib-dir ${built.runtimeCrate.lib} --kind runtime)"
        cli="$("$observer" producer-artifact --lib-dir ${built.compilerCrate.lib} --kind cli)"
        python="$("$observer" producer-artifact --lib-dir ${built.pythonCrate.lib} --kind python)"
        changed_runtime="$("$observer" producer-artifact \
          --lib-dir ${built.runtimeIdentityProducerControls.changedRuntimeCrate.lib} --kind runtime)"
        mkdir -p "$out"
        "$observer" inspect runtime "$runtime" > "$out/runtime.json"
        "$observer" inspect cli "$cli" > "$out/cli.json"
        "$observer" inspect python "$python" > "$out/python.json"
        "$observer" inspect runtime "$changed_runtime" > "$out/ownership-ledger-runtime.json"
        "$observer" inspect-provenance runtime "$runtime" > "$out/runtime-provenance.json"
        "$observer" inspect-provenance cli "$cli" > "$out/cli-provenance.json"
        "$observer" inspect-provenance python "$python" > "$out/python-provenance.json"
        "$observer" inspect-provenance runtime "$changed_runtime" > "$out/ownership-ledger-runtime-provenance.json"
        "$observer" verify-producers --runtime "$runtime" --cli "$cli" --python "$python"
        python3 - "$observer" "$runtime" "$changed_runtime" "$cli" "$python" "$out" \
          ${runtimeIdentityMissingInput.out} "${pkgs.stdenv.hostPlatform.system}" <<'PY'
        import hashlib
        import json
        import re
        import subprocess
        import sys
        from pathlib import Path

        observer, runtime, changed_runtime, cli, python, output, failed, system = sys.argv[1:]
        output, failed = Path(output), Path(failed)
        artifacts = {
            "runtime": runtime,
            "cli": cli,
            "python": python,
            "ownership-ledger-runtime": changed_runtime,
        }
        (output / "artifacts.json").write_text(json.dumps({
            "builder": "nix runtime-identity-producers",
            "system": system,
            "artifacts": {
                kind: {
                    "path": path,
                    "sha256": hashlib.sha256(Path(path).read_bytes()).hexdigest(),
                }
                for kind, path in artifacts.items()
            },
        }, indent=2, sort_keys=True) + "\n")
        descriptors = {
            kind: json.loads((output / f"{kind}.json").read_text())
            for kind in ("runtime", "cli", "python", "ownership-ledger-runtime")
        }
        provenance = {
            kind: json.loads((output / f"{kind}-provenance.json").read_text())
            for kind in ("runtime", "cli", "python", "ownership-ledger-runtime")
        }
        if any(value.get("mode") != "sealed_distribution" for value in provenance.values()):
            raise SystemExit(f"Nix producer provenance was not explicitly sealed: {provenance}")
        # verify-producers stops at the first mismatch. Independently decoded
        # CLI/Python equality makes that same rejection apply to both consumers.
        if not descriptors["runtime"] == descriptors["cli"] == descriptors["python"]:
            raise SystemExit("matching runtime/CLI/Python expectations differ")
        if descriptors["ownership-ledger-runtime"]["features"] == descriptors["runtime"]["features"]:
            raise SystemExit("ownership-ledger did not change the runtime feature identity")
        crossed = subprocess.run(
            [observer, "verify-producers", "--runtime", changed_runtime, "--cli", cli, "--python", python],
            text=True, capture_output=True, check=False,
        )
        (output / "crossed-recipe.stdout").write_text(crossed.stdout)
        (output / "crossed-recipe.stderr").write_text(crossed.stderr)
        mismatch = re.fullmatch(
            r"runtime identity: runtime identity mismatch: \[([A-Za-z, ]+)\]\n?",
            crossed.stderr,
        )
        if crossed.returncode != 1 or mismatch is None or "Features" not in mismatch[1].split(", "):
            raise SystemExit(f"crossed recipe did not fail for feature identity: {crossed}")

        # testBuildFailure alone accepts any failed builder. Demand the exact
        # producer diagnostic for the deliberately withheld per-crate header.
        log = (failed / "testBuildFailure.log").read_text()
        exit_code = (failed / "testBuildFailure.exit").read_text().strip()
        failures = [line for line in log.splitlines() if line.startswith("runtime identity:")]
        if exit_code != "1" or len(failures) != 1 or not re.fullmatch(
            r"runtime identity: missing declared build input /[^\n]*/chelis-source/"
            r"crates/chelis-runtime/include/chelis_runtime\.h",
            failures[0],
        ):
            raise SystemExit(f"missing-input build did not fail for its required header:\n{log}")
        (output / "missing-required-input.log").write_text(log)
        (output / "missing-required-input.exit").write_text(exit_code + "\n")
        PY
      '';

  chelisupBehavior = pkgs.runCommand "chelisup-behavior" { } ''
    ${packages.chelisup}/bin/chelisup --help >/dev/null
    touch "$out"
  '';

  # The generated launcher is the one shell program in the package
  # outputs; it gets the same static gate the bootstrap script has.
  chelisupLauncherLint =
    pkgs.runCommand "chelisup-launcher-lint"
      {
        nativeBuildInputs = [ pkgs.shellcheck ];
      }
      ''
        bash -n ${packages.chelisup}/bin/chelisup
        shellcheck ${packages.chelisup}/bin/chelisup
        touch "$out"
      '';

  nixFormat =
    pkgs.runCommand "nix-format"
      {
        nativeBuildInputs = [ pkgs.nixfmt ];
      }
      ''
        nixfmt --check \
          ${root}/devenv.nix \
          ${root}/devenv/ci.nix \
          ${root}/devenv/entry-shell.nix \
          ${root}/devenv/commands.nix \
          ${root}/devenv/generated-files.nix \
          ${root}/devenv/git-hooks.nix \
          ${root}/devenv/smoke-tests.nix \
          ${root}/devenv/toolchains.nix \
          ${root}/flake.nix \
          ${./checks.nix} \
          ${./contracts.nix} \
          ${./cvc5.nix} \
          ${./packages.nix} \
          ${./runtime-identity.nix} \
          ${./source.nix}
        touch "$out"
      '';

  contractChecks = [
    appContract
    chelisShape
    chelisupBehavior
    chelisupLauncherLint
    chelisupShape
    compilerBehavior
    crate2nixGeneration
    cvc5Dir
    lockParity
    nixFormat
    runtimeConsumer
    runtimeIdentityProducers
    runtimeShape
  ];
  native = pkgs.runCommand "chelis-native-contracts" { } ''
    ${lib.concatMapStringsSep "\n" (check: "test -e ${check}") contractChecks}
    test -e ${packages.chelis}
    test -e ${packages.chelis-runtime}
    test -e ${packages.chelisup}
    touch "$out"
  '';
in
{
  inherit
    appContract
    chelisShape
    chelisupBehavior
    chelisupLauncherLint
    chelisupShape
    compilerBehavior
    crate2nixGeneration
    cvc5Dir
    lockParity
    native
    nixFormat
    runtimeConsumer
    runtimeIdentityProducers
    runtimeShape
    ;
  runtime-identity-producers = runtimeIdentityProducers;
  chelis = packages.chelis;
  chelis-runtime = packages.chelis-runtime;
  chelisup = packages.chelisup;
}
