/* Generated by chelis-abi; edit its schema, not this fragment. */
#ifndef CHELIS_DEVICE_DESCRIPTOR_H
#define CHELIS_DEVICE_DESCRIPTOR_H
#include "chelis_runtime_dtype.h"
typedef int64_t chelis_device_metadata;
typedef int32_t chelis_device_rank;

typedef struct {
    void *data;
    const int64_t *shape;
    const int64_t *strides;
    int64_t count;
    int64_t byte_capacity;
    int32_t rank;
    chelis_dtype dtype;
    uint8_t ownership;
    uint8_t reserved[2];
} chelis_gpu_tensor;
#endif
