//! Bounded memoized monomorphization for recursive generic host calls
//! (chelis#1158, successor to chelis#941).
//!
//! # Why outlining rather than inlining
//!
//! A type-polymorphic top-level function has no standalone C ABI, so
//! `lower_host_program` deliberately does not emit one: a `Box[a]` cannot
//! cross a concrete host boundary before a call site binds `a`. Until this
//! module existed, the only way to reach such a body was call-site inlining,
//! which cannot terminate when the callee participates in a call cycle — so
//! every recursive generic call was rejected under `[05-UNS-1]`.
//!
//! The fix is to stop inlining recursive generics and start *outlining* them.
//! A call site whose callee is type-polymorphic resolves the call's fully
//! concrete signature, interns `(callee, canonical signature) -> mangled
//! symbol`, enqueues the pair the first time it is seen, and emits an
//! ordinary C call. After the main lowering pass drains the worklist, each
//! pending pair is lowered once as a standalone `HostFunction` with the
//! generic's type variables bound to the interned concrete terms. Recursive
//! calls inside a draining body re-enter the interner, hit the memo, and
//! become ordinary calls too.
//!
//! Termination is by memoization, so **mutual recursion needs no SCC
//! analysis**: each distinct pair is enqueued exactly once and a cycle
//! resolves to an already-interned symbol.
//!
//! # What still cannot be monomorphized
//!
//! Polymorphic recursion — a cycle that keeps minting *new* instantiations,
//! as in `f[a]` calling `f[(a, a)]` — has no finite family of monomorphic
//! symbols, so it stays on the (now narrowed) `[05-UNS-1]` boundary. Two
//! caps keep that fail-loud rather than divergent: [`MONO_SPECIALIZATION_CAP`]
//! bounds how many distinct specializations one callee may mint, and
//! [`MONO_SIGNATURE_NODE_CAP`] bounds one signature's size. The size cap is
//! not redundant: the `f[(a, a)]` shape doubles the type at every level, so
//! the count cap alone would be reached only after building a signature with
//! 2^64 nodes.
//!
//! # V1 scope
//!
//! Only **fully concrete** signatures are interned. A call site that still
//! carries a free type, precision, or rank variable after unification falls
//! through to the pre-existing inline/rejection paths untouched, so this
//! module never interacts with the precision- and rank-polymorphism
//! machinery.

use std::cell::RefCell;
use std::collections::{HashMap, HashSet, VecDeque};

use chelis_deep::DeepTag;
use chelis_deep::ast::{Atom, Expr, List, MetaMap};

use crate::dag::{DimInfo, TensorType};
use crate::host_type_state::{
    HostPrecisionTerm, HostShapeSlot, HostShapeTerm, HostTensorTypeTerm, HostTypeTerm,
};

/// Maximum number of distinct monomorphic specializations one generic callee
/// may mint in a single program. A legitimate program instantiates a generic
/// at a handful of types; exceeding this bound means the instantiation family
/// is being generated by the recursion itself.
pub(crate) const MONO_SPECIALIZATION_CAP: usize = 64;

/// Maximum number of type-term nodes in one interned signature. Polymorphic
/// recursion that grows the type multiplicatively (`f[a]` calling `f[(a, a)]`)
/// reaches this long before [`MONO_SPECIALIZATION_CAP`], and reaching it is
/// the only thing that keeps the worklist from allocating a signature larger
/// than memory.
pub(crate) const MONO_SIGNATURE_NODE_CAP: usize = 512;

/// One `(callee, concrete signature)` pair awaiting outlined emission.
#[derive(Debug, Clone)]
pub(crate) struct PendingSpecialization {
    /// The generic top-level def this specializes.
    pub(crate) callee: String,
    /// The emitted C symbol for this specialization.
    pub(crate) symbol: String,
    /// Fully concrete parameter types, positionally matching the def's params.
    pub(crate) params: Vec<HostTypeTerm>,
    /// Fully concrete return type.
    pub(crate) ret: HostTypeTerm,
    /// Instantiation chain that reached this specialization, oldest first.
    /// Rendered into the cap diagnostic so polymorphic recursion is
    /// debuggable rather than merely rejected.
    pub(crate) chain: Vec<String>,
}

/// The type-variable bindings in force while one specialization's body is
/// being lowered.
#[derive(Debug, Clone)]
struct MonoFrame {
    callee: String,
    bindings: HashMap<String, HostTypeTerm>,
    chain: Vec<String>,
}

thread_local! {
    /// `(callee, canonical signature)` -> emitted symbol. The memo is what
    /// makes the worklist terminate.
    static MONO_INTERN: RefCell<HashMap<(String, String), String>> =
        RefCell::new(HashMap::new());
    /// Pending specializations in first-seen order. FIFO, not a hash-map
    /// iteration, so emission order — and therefore the emitted `.c` — is
    /// deterministic (chelis#1002).
    static MONO_WORKLIST: RefCell<VecDeque<PendingSpecialization>> =
        const { RefCell::new(VecDeque::new()) };
    /// How many distinct specializations each callee has minted.
    static MONO_SPECIALIZATION_COUNTS: RefCell<HashMap<String, usize>> =
        RefCell::new(HashMap::new());
    /// Emitted symbol -> the canonical signature it was minted for. The
    /// reverse of `MONO_INTERN`, kept so a hash collision is caught rather
    /// than emitted: two signatures sharing a symbol would collapse into one
    /// C definition, and the emitter's duplicate-symbol check cannot see it
    /// (it compares distinct `HostFunction` names, which would be equal).
    static MONO_SYMBOL_ORIGINS: RefCell<HashMap<String, String>> =
        RefCell::new(HashMap::new());
    /// The stack of specializations currently being lowered.
    static MONO_FRAMES: RefCell<Vec<MonoFrame>> = const { RefCell::new(Vec::new()) };
}

/// Makes a speculative lowering side-effect-free on the interner.
///
/// Several lowering decisions are taken by *probing*: `top_level_fn_helper_
/// summary_rejects` fully lowers a callee body only to ask whether its tensor
/// helper would register a summary rejection, then throws the result away. The
/// lowering is discarded; the interning it performed was not. Three
/// consequences, all real:
///
/// 1. **Nondeterministic emitted C (chelis#1002).** The probe set is iterated
///    from a `HashSet`, so probe order varies per run. Whichever probe ran
///    first fixed that specialization's position in the FIFO worklist, and the
///    drain preserves worklist order into emission order. Measured: 25 builds
///    of one file produced two distinct `.c` hashes, differing only by two
///    `count__mono_*` definitions swapping places.
/// 2. **Cap budget consumed by discarded work.** `intern_specialization`
///    increments the per-callee count at intern time, so a probe could push a
///    program over [`MONO_SPECIALIZATION_CAP`] without any surviving call site.
/// 3. **Unconditional emission of probe-only specializations.** The drain
///    lowers every enqueued pair and propagates failure with `?`, so a
///    specialization that only ever existed inside a discarded probe can abort
///    the whole build.
///
/// Restoring the snapshot on scope exit removes all three at the root: after a
/// probe the interner is byte-for-byte what it was before, and every surviving
/// specialization was interned by the real lowering pass, in that pass's
/// deterministic traversal order.
pub(crate) struct MonoProbeGuard {
    intern: HashMap<(String, String), String>,
    worklist: VecDeque<PendingSpecialization>,
    counts: HashMap<String, usize>,
    symbol_origins: HashMap<String, String>,
    frames: Vec<MonoFrame>,
}

impl MonoProbeGuard {
    pub(crate) fn begin() -> Self {
        Self {
            intern: MONO_INTERN.with(|state| state.borrow().clone()),
            worklist: MONO_WORKLIST.with(|state| state.borrow().clone()),
            counts: MONO_SPECIALIZATION_COUNTS.with(|state| state.borrow().clone()),
            symbol_origins: MONO_SYMBOL_ORIGINS.with(|state| state.borrow().clone()),
            frames: MONO_FRAMES.with(|state| state.borrow().clone()),
        }
    }
}

impl Drop for MonoProbeGuard {
    fn drop(&mut self) {
        // Restore rather than clear: a probe can run while a specialization
        // body is being drained, and that outer frame must survive.
        MONO_INTERN.with(|state| *state.borrow_mut() = std::mem::take(&mut self.intern));
        MONO_WORKLIST.with(|state| *state.borrow_mut() = std::mem::take(&mut self.worklist));
        MONO_SPECIALIZATION_COUNTS
            .with(|state| *state.borrow_mut() = std::mem::take(&mut self.counts));
        MONO_SYMBOL_ORIGINS
            .with(|state| *state.borrow_mut() = std::mem::take(&mut self.symbol_origins));
        MONO_FRAMES.with(|state| *state.borrow_mut() = std::mem::take(&mut self.frames));
    }
}

/// Clear every interner cache. Called from the host-lowering cache guard so
/// one process may lower many programs without leaking symbols between them.
pub(crate) fn reset_mono_state() {
    MONO_INTERN.with(|intern| intern.borrow_mut().clear());
    MONO_WORKLIST.with(|worklist| worklist.borrow_mut().clear());
    MONO_SPECIALIZATION_COUNTS.with(|counts| counts.borrow_mut().clear());
    MONO_SYMBOL_ORIGINS.with(|origins| origins.borrow_mut().clear());
    MONO_FRAMES.with(|frames| frames.borrow_mut().clear());
}

/// Why a call site could not be monomorphized. Both variants keep the
/// `[05-UNS-1]` brand; they differ in what the author can do about it.
#[derive(Debug, Clone)]
pub(crate) enum MonoRejection {
    /// The call's type arguments did not resolve to a concrete signature, so
    /// there is nothing to intern. This is the residual chelis#730 shape.
    NotConcrete { detail: String },
    /// The instantiation family is unbounded: the recursion mints a new type
    /// at every level. No finite set of monomorphic symbols exists.
    UnboundedInstantiation { chain: Vec<String>, reason: String },
    /// Two distinct signatures hashed to one emitted symbol. Astronomically
    /// unlikely at 64 bits, and silently wrong if it ever happened, so it is
    /// a rejection rather than an assumption.
    SymbolCollision {
        symbol: String,
        signature: String,
        existing: String,
    },
}

impl MonoRejection {
    pub(crate) fn describe(&self, callee: &str) -> String {
        match self {
            Self::NotConcrete { detail } => format!(
                "generic host call `{callee}` has no monomorphic symbol: {detail} \
                 (chelis#1158; [05-UNS-1])"
            ),
            Self::UnboundedInstantiation { chain, reason } => format!(
                "generic host call `{callee}` requires unbounded monomorphization \
                 ({reason}); this is polymorphic recursion: the instantiation \
                 chain {} mints a new type at every level, so no finite set of \
                 monomorphic symbols exists (chelis#1158; [05-UNS-1])",
                render_chain(chain)
            ),
            Self::SymbolCollision {
                symbol,
                signature,
                existing,
            } => format!(
                "generic host call `{callee}` hashed signature `{signature}` onto \
                 symbol `{symbol}`, which signature `{existing}` already holds; \
                 emitting both would collapse two specializations into one C \
                 definition (chelis#1158; [05-UNS-1])"
            ),
        }
    }
}

fn render_chain(chain: &[String]) -> String {
    const SHOWN: usize = 4;
    let mut rendered = chain
        .iter()
        .take(SHOWN)
        .cloned()
        .collect::<Vec<_>>()
        .join(" -> ");
    if chain.len() > SHOWN {
        rendered.push_str(" -> ...");
    }
    if rendered.is_empty() {
        "(entry)".to_string()
    } else {
        rendered
    }
}

/// Intern `(callee, params -> ret)`, enqueueing the pair the first time it is
/// seen. Returns the emitted symbol, or the reason no symbol may exist.
///
/// The caps are checked here rather than at drain time because the drain is
/// downstream of the allocation this bounds: a signature that is already too
/// large has already been built.
pub(crate) fn intern_specialization(
    callee: &str,
    params: &[HostTypeTerm],
    ret: &HostTypeTerm,
) -> Result<String, MonoRejection> {
    let nodes = params
        .iter()
        .map(host_type_node_count)
        .sum::<usize>()
        .saturating_add(host_type_node_count(ret));
    let key = canonical_signature_key(params, ret);
    let label = format!("{callee}{key}");
    // An empty prefix is a fact, not a default: this call site is not inside
    // any specialization, so it IS the head of its instantiation chain.
    let mut chain = MONO_FRAMES.with(|frames| match frames.borrow().last() {
        Some(frame) => frame.chain.clone(),
        None => Vec::new(),
    });
    chain.push(label);

    if let Some(symbol) = MONO_INTERN.with(|intern| {
        intern
            .borrow()
            .get(&(callee.to_string(), key.clone()))
            .cloned()
    }) {
        return Ok(symbol);
    }
    if nodes > MONO_SIGNATURE_NODE_CAP {
        return Err(MonoRejection::UnboundedInstantiation {
            chain,
            reason: format!(
                "signature has {nodes} type nodes, over the \
                 {MONO_SIGNATURE_NODE_CAP}-node cap"
            ),
        });
    }
    let minted = MONO_SPECIALIZATION_COUNTS.with(|counts| {
        let mut counts = counts.borrow_mut();
        let slot = counts.entry(callee.to_string()).or_insert(0);
        *slot += 1;
        *slot
    });
    if minted > MONO_SPECIALIZATION_CAP {
        return Err(MonoRejection::UnboundedInstantiation {
            chain,
            reason: format!(
                "{minted} distinct specializations, over the \
                 {MONO_SPECIALIZATION_CAP}-per-callee cap"
            ),
        });
    }

    // The origin is the callee-qualified label, not the signature alone: two
    // DIFFERENT callees whose names sanitize to one C identifier (`A.f` and
    // `A_f`) would otherwise pass this check while sharing a symbol.
    let symbol = mono_symbol(callee, &key);
    let origin = format!("{callee}{key}");
    if let Some(existing) = MONO_SYMBOL_ORIGINS.with(|origins| {
        origins
            .borrow_mut()
            .insert(symbol.clone(), origin.clone())
            .filter(|existing| existing != &origin)
    }) {
        return Err(MonoRejection::SymbolCollision {
            symbol,
            signature: origin,
            existing,
        });
    }
    MONO_INTERN.with(|intern| {
        intern
            .borrow_mut()
            .insert((callee.to_string(), key), symbol.clone())
    });
    MONO_WORKLIST.with(|worklist| {
        worklist.borrow_mut().push_back(PendingSpecialization {
            callee: callee.to_string(),
            symbol: symbol.clone(),
            params: params.to_vec(),
            ret: ret.clone(),
            chain,
        })
    });
    Ok(symbol)
}

pub(crate) fn pop_pending_specialization() -> Option<PendingSpecialization> {
    MONO_WORKLIST.with(|worklist| worklist.borrow_mut().pop_front())
}

/// Push the type-variable environment for one specialization's body.
pub(crate) fn push_mono_frame(
    callee: &str,
    bindings: HashMap<String, HostTypeTerm>,
    chain: Vec<String>,
) {
    MONO_FRAMES.with(|frames| {
        frames.borrow_mut().push(MonoFrame {
            callee: callee.to_string(),
            bindings,
            chain,
        })
    });
}

pub(crate) fn pop_mono_frame() {
    MONO_FRAMES.with(|frames| {
        frames.borrow_mut().pop();
    });
}

/// The enclosing specialization's binding for `variable`, when the call being
/// lowered is a *self*-recursive call inside that specialization.
///
/// This is the one place a binding is read rather than derived from the call
/// site's own types, and it is deliberately narrow. Inside `f`'s body the
/// signature's type variables are rigid, so when a recursive `f(...)`
/// argument carries no checked type of its own — `loop(Empty)` in
/// chelis#941's reproducer, where `Empty` is a nullary constructor whose type
/// the checker solved by unifying it with `f`'s own parameter — the enclosing
/// instantiation *is* the checker's solution, not a guess. Restricting the
/// lookup to `callee == the def being specialized` keeps it from being
/// applied across two defs that happen to have both authored `[a]`.
pub(crate) fn enclosing_binding(callee: &str, variable: &str) -> Option<HostTypeTerm> {
    MONO_FRAMES.with(|frames| {
        let frames = frames.borrow();
        let frame = frames.last()?;
        (frame.callee == callee)
            .then(|| frame.bindings.get(variable).cloned())
            .flatten()
    })
}

// ---------------------------------------------------------------------------
// Canonical signatures, symbols, and sizes
// ---------------------------------------------------------------------------

/// A deterministic, injective-enough rendering of one signature. Used both as
/// the memo key and as the hash input for the emitted symbol, so it must not
/// depend on hash-map iteration order or on pointer identity.
pub(crate) fn canonical_signature_key(params: &[HostTypeTerm], ret: &HostTypeTerm) -> String {
    let mut out = String::from("(");
    for (index, param) in params.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        render_host_type(param, &mut out);
    }
    out.push_str(")->");
    render_host_type(ret, &mut out);
    out
}

/// The canonical rendering of one type term, for diagnostics.
pub(crate) fn render_host_type_term(ty: &HostTypeTerm) -> String {
    let mut out = String::new();
    render_host_type(ty, &mut out);
    out
}

fn render_host_type(ty: &HostTypeTerm, out: &mut String) {
    match ty {
        HostTypeTerm::Scalar(HostPrecisionTerm::Concrete(prim)) => out.push_str(prim.name()),
        HostTypeTerm::Scalar(HostPrecisionTerm::Variable(name)) => {
            out.push_str("%prec:");
            out.push_str(name);
        }
        HostTypeTerm::Fn(params, ret) => {
            out.push_str("fn(");
            for (index, param) in params.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                render_host_type(param, out);
            }
            out.push_str(")->");
            render_host_type(ret, out);
        }
        HostTypeTerm::Adt(name, args) => {
            out.push_str(name);
            out.push('[');
            for (index, arg) in args.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                render_host_type(arg, out);
            }
            out.push(']');
        }
        HostTypeTerm::List(inner) => {
            out.push_str("List[");
            render_host_type(inner, out);
            out.push(']');
        }
        HostTypeTerm::Option(inner) => {
            out.push_str("Option[");
            render_host_type(inner, out);
            out.push(']');
        }
        HostTypeTerm::Dict(key, value) => {
            out.push_str("Dict[");
            render_host_type(key, out);
            out.push(',');
            render_host_type(value, out);
            out.push(']');
        }
        HostTypeTerm::Tuple(items) => {
            out.push('(');
            for (index, item) in items.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                render_host_type(item, out);
            }
            out.push(')');
        }
        HostTypeTerm::Tensor(tensor) => {
            out.push_str("tensor[");
            for dim in &tensor.dims {
                render_dim(dim, out);
                out.push(',');
            }
            out.push_str(tensor.precision.name());
            out.push(']');
        }
        HostTypeTerm::PolymorphicTensor(tensor) => {
            out.push_str("tensor?[");
            match &tensor.shape {
                HostShapeTerm::Concrete(dims) => {
                    for dim in dims {
                        render_dim(dim, out);
                        out.push(',');
                    }
                }
                HostShapeTerm::Polymorphic(slots) => {
                    for slot in slots {
                        match slot {
                            HostShapeSlot::Dim(dim) => render_dim(dim, out),
                            HostShapeSlot::RankVariable(name) => {
                                out.push_str("%rank:");
                                out.push_str(name);
                            }
                        }
                        out.push(',');
                    }
                }
            }
            match &tensor.precision {
                HostPrecisionTerm::Concrete(prim) => out.push_str(prim.name()),
                HostPrecisionTerm::Variable(name) => {
                    out.push_str("%prec:");
                    out.push_str(name);
                }
            }
            out.push(']');
        }
        HostTypeTerm::MappedFile => out.push_str("MappedFile"),
        HostTypeTerm::Unit => out.push_str("unit"),
        HostTypeTerm::TypeVariable(name) => {
            out.push_str("%var:");
            out.push_str(name);
        }
        HostTypeTerm::InferenceVariable(var) => {
            out.push_str("%inf:");
            out.push_str(&var.0.to_string());
        }
        HostTypeTerm::Never => out.push_str("never"),
    }
}

fn render_dim(dim: &DimInfo, out: &mut String) {
    match dim {
        DimInfo::Lit(value) => out.push_str(&value.to_string()),
        DimInfo::Named(name, None) => out.push_str(name),
        DimInfo::Named(name, Some(value)) => {
            out.push_str(name);
            out.push('=');
            out.push_str(&value.to_string());
        }
    }
}

/// The infix that marks an emitted symbol as a monomorphized specialization
/// rather than an authored def. A Chelis source identifier cannot contain it
/// in this position, because `mono_symbol` is the only producer.
const MONO_SYMBOL_INFIX: &str = "__mono_";

/// Whether an emitted host function name is a chelis#1158 specialization.
///
/// The C backend asks so it can keep these out of the program's published
/// `.h`: the name is a hash of an interned signature, it moves whenever the
/// instantiation set does, and it is compiler-owned. Kept here rather than
/// re-derived in the backend so one module owns the convention.
pub fn is_monomorphized_specialization(name: &str) -> bool {
    name.contains(MONO_SYMBOL_INFIX)
}

/// The emitted C symbol for one specialization.
///
/// The hash is FNV-1a rather than `DefaultHasher`: `std`'s default hasher is
/// explicitly not stable across releases or processes, and an unstable symbol
/// name would make the emitted `.c` non-reproducible (chelis#1002). Non-C
/// identifier bytes in the callee (a dotted module path, for example) are
/// folded to `_` so the result is always a legal C identifier.
pub(crate) fn mono_symbol(callee: &str, signature_key: &str) -> String {
    let mut sanitized = String::with_capacity(callee.len());
    for byte in callee.chars() {
        if byte.is_ascii_alphanumeric() || byte == '_' {
            sanitized.push(byte);
        } else {
            sanitized.push('_');
        }
    }
    if sanitized.starts_with(|c: char| c.is_ascii_digit()) {
        sanitized.insert(0, '_');
    }
    format!(
        "{sanitized}{MONO_SYMBOL_INFIX}{:016x}",
        fnv1a64(signature_key.as_bytes())
    )
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}

/// Structural node count of a type term. Bounds the worklist's allocation:
/// see [`MONO_SIGNATURE_NODE_CAP`].
pub(crate) fn host_type_node_count(ty: &HostTypeTerm) -> usize {
    match ty {
        HostTypeTerm::Fn(params, ret) => {
            1 + params.iter().map(host_type_node_count).sum::<usize>() + host_type_node_count(ret)
        }
        HostTypeTerm::Adt(_, args) | HostTypeTerm::Tuple(args) => {
            1 + args.iter().map(host_type_node_count).sum::<usize>()
        }
        HostTypeTerm::List(inner) | HostTypeTerm::Option(inner) => 1 + host_type_node_count(inner),
        HostTypeTerm::Dict(key, value) => {
            1 + host_type_node_count(key) + host_type_node_count(value)
        }
        _ => 1,
    }
}

// ---------------------------------------------------------------------------
// Type-variable unification and substitution
// ---------------------------------------------------------------------------

/// Collect the bindings that make `pattern` equal to `concrete`.
///
/// This is one-directional matching, not full unification: `pattern` carries
/// the generic's variables and `concrete` is the call site's resolved type.
/// A position where `concrete` is itself unresolved contributes nothing, so a
/// partially-known call site still binds what it does know. The first binding
/// for a variable wins, which is why callers unify parameters (specific)
/// before the return type (often only `Unknown`).
pub(crate) fn collect_type_var_bindings(
    pattern: &HostTypeTerm,
    concrete: &HostTypeTerm,
    out: &mut HashMap<String, HostTypeTerm>,
) {
    match (pattern, concrete) {
        (HostTypeTerm::TypeVariable(name), value) => {
            if !value.is_unresolved() {
                out.entry(name.clone()).or_insert_with(|| value.clone());
            }
        }
        (HostTypeTerm::Fn(pattern_params, pattern_ret), HostTypeTerm::Fn(params, ret)) => {
            for (pattern_param, param) in pattern_params.iter().zip(params) {
                collect_type_var_bindings(pattern_param, param, out);
            }
            collect_type_var_bindings(pattern_ret, ret, out);
        }
        (HostTypeTerm::Adt(pattern_name, pattern_args), HostTypeTerm::Adt(name, args))
            if pattern_name == name =>
        {
            for (pattern_arg, arg) in pattern_args.iter().zip(args) {
                collect_type_var_bindings(pattern_arg, arg, out);
            }
        }
        (HostTypeTerm::Tuple(pattern_items), HostTypeTerm::Tuple(items)) => {
            for (pattern_item, item) in pattern_items.iter().zip(items) {
                collect_type_var_bindings(pattern_item, item, out);
            }
        }
        (HostTypeTerm::List(pattern_inner), HostTypeTerm::List(inner))
        | (HostTypeTerm::Option(pattern_inner), HostTypeTerm::Option(inner)) => {
            collect_type_var_bindings(pattern_inner, inner, out);
        }
        (HostTypeTerm::Dict(pattern_key, pattern_value), HostTypeTerm::Dict(key, value)) => {
            collect_type_var_bindings(pattern_key, key, out);
            collect_type_var_bindings(pattern_value, value, out);
        }
        // A signature-quantified precision or rank variable binds from the
        // call's concrete tensor. Those forms have their own specialization
        // paths and normally never reach here; handling them costs nothing
        // and keeps a mixed signature from silently binding only half.
        (HostTypeTerm::PolymorphicTensor(pattern_tensor), HostTypeTerm::Tensor(tensor)) => {
            if let HostPrecisionTerm::Variable(name) = &pattern_tensor.precision {
                out.entry(name.clone()).or_insert_with(|| {
                    HostTypeTerm::Scalar(HostPrecisionTerm::Concrete(tensor.precision))
                });
            }
        }
        _ => {}
    }
}

/// Every type-variable name still free in `ty`.
pub(crate) fn collect_free_type_vars(ty: &HostTypeTerm, out: &mut HashSet<String>) {
    match ty {
        HostTypeTerm::TypeVariable(name)
        | HostTypeTerm::Scalar(HostPrecisionTerm::Variable(name)) => {
            out.insert(name.clone());
        }
        HostTypeTerm::Fn(params, ret) => {
            for param in params {
                collect_free_type_vars(param, out);
            }
            collect_free_type_vars(ret, out);
        }
        HostTypeTerm::Adt(_, args) | HostTypeTerm::Tuple(args) => {
            for arg in args {
                collect_free_type_vars(arg, out);
            }
        }
        HostTypeTerm::List(inner) | HostTypeTerm::Option(inner) => {
            collect_free_type_vars(inner, out);
        }
        HostTypeTerm::Dict(key, value) => {
            collect_free_type_vars(key, out);
            collect_free_type_vars(value, out);
        }
        HostTypeTerm::PolymorphicTensor(tensor) => {
            if let HostPrecisionTerm::Variable(name) = &tensor.precision {
                out.insert(name.clone());
            }
            if let HostShapeTerm::Polymorphic(slots) = &tensor.shape {
                for slot in slots {
                    if let HostShapeSlot::RankVariable(name) = slot {
                        out.insert(name.clone());
                    }
                }
            }
        }
        _ => {}
    }
}

/// Replace every bound type variable in `ty`.
pub(crate) fn apply_type_var_bindings(
    ty: &HostTypeTerm,
    env: &HashMap<String, HostTypeTerm>,
) -> HostTypeTerm {
    match ty {
        HostTypeTerm::TypeVariable(name) => env.get(name).cloned().unwrap_or_else(|| ty.clone()),
        HostTypeTerm::Fn(params, ret) => HostTypeTerm::Fn(
            params
                .iter()
                .map(|param| apply_type_var_bindings(param, env))
                .collect(),
            Box::new(apply_type_var_bindings(ret, env)),
        ),
        HostTypeTerm::Adt(name, args) => HostTypeTerm::Adt(
            name.clone(),
            args.iter()
                .map(|arg| apply_type_var_bindings(arg, env))
                .collect(),
        ),
        HostTypeTerm::Tuple(items) => HostTypeTerm::Tuple(
            items
                .iter()
                .map(|item| apply_type_var_bindings(item, env))
                .collect(),
        ),
        HostTypeTerm::List(inner) => {
            HostTypeTerm::List(Box::new(apply_type_var_bindings(inner, env)))
        }
        HostTypeTerm::Option(inner) => {
            HostTypeTerm::Option(Box::new(apply_type_var_bindings(inner, env)))
        }
        HostTypeTerm::Dict(key, value) => HostTypeTerm::Dict(
            Box::new(apply_type_var_bindings(key, env)),
            Box::new(apply_type_var_bindings(value, env)),
        ),
        HostTypeTerm::Scalar(HostPrecisionTerm::Variable(name)) => match env.get(name) {
            Some(HostTypeTerm::Scalar(HostPrecisionTerm::Concrete(prim))) => {
                HostTypeTerm::Scalar(HostPrecisionTerm::Concrete(*prim))
            }
            _ => ty.clone(),
        },
        HostTypeTerm::PolymorphicTensor(tensor) => {
            let precision = match &tensor.precision {
                HostPrecisionTerm::Variable(name) => match env.get(name) {
                    Some(HostTypeTerm::Scalar(HostPrecisionTerm::Concrete(prim))) => {
                        HostPrecisionTerm::Concrete(*prim)
                    }
                    _ => tensor.precision.clone(),
                },
                concrete => concrete.clone(),
            };
            match (&precision, &tensor.shape) {
                (HostPrecisionTerm::Concrete(prim), HostShapeTerm::Concrete(dims)) => {
                    HostTypeTerm::Tensor(TensorType {
                        dims: dims.clone(),
                        precision: *prim,
                    })
                }
                _ => HostTypeTerm::PolymorphicTensor(HostTensorTypeTerm {
                    precision,
                    shape: tensor.shape.clone(),
                }),
            }
        }
        other => other.clone(),
    }
}

// ---------------------------------------------------------------------------
// Deep type encoding and substitution
// ---------------------------------------------------------------------------

/// Encode a host type term back into a Deep type node — the inverse of
/// `decode_host_type`.
///
/// Returns `None` for states that have no Deep spelling (inference holes and
/// `Never`); a caller that needs a total encoding has already checked
/// concreteness. Round-tripping is what lets a specialization rewrite the
/// generic body's checked type metadata in place, so the whole downstream
/// pipeline sees an ordinary concrete program instead of needing a parallel
/// substitution channel threaded through expression lowering.
pub(crate) fn encode_host_type(ty: &HostTypeTerm) -> Option<Expr> {
    let span = chelis_deep::Span::new(0, 0);
    let node =
        |tag: DeepTag, children: Vec<Expr>| Expr::node(tag, MetaMap::default(), children, span);
    let symbol = |name: &str| Expr::Atom(Atom::Name(name.to_string()), span);
    Some(match ty {
        HostTypeTerm::Scalar(HostPrecisionTerm::Concrete(prim)) => {
            node(DeepTag::TPrim, vec![symbol(prim.name())])
        }
        HostTypeTerm::Scalar(HostPrecisionTerm::Variable(name)) => {
            node(DeepTag::TVar, vec![symbol(name)])
        }
        HostTypeTerm::TypeVariable(name) => node(DeepTag::TVar, vec![symbol(name)]),
        HostTypeTerm::Unit => node(DeepTag::TUnit, vec![]),
        HostTypeTerm::MappedFile => node(DeepTag::TAdt, vec![symbol("MappedFile")]),
        HostTypeTerm::Fn(params, ret) => {
            let mut children = params
                .iter()
                .map(encode_host_type)
                .collect::<Option<Vec<_>>>()?;
            children.push(encode_host_type(ret)?);
            node(DeepTag::TFn, children)
        }
        HostTypeTerm::Adt(name, args) => {
            let mut children = vec![symbol(name)];
            for arg in args {
                children.push(encode_host_type(arg)?);
            }
            node(DeepTag::TAdt, children)
        }
        HostTypeTerm::List(inner) => node(
            DeepTag::TAdt,
            vec![symbol("List"), encode_host_type(inner)?],
        ),
        HostTypeTerm::Option(inner) => node(
            DeepTag::TAdt,
            vec![symbol("Option"), encode_host_type(inner)?],
        ),
        HostTypeTerm::Dict(key, value) => node(
            DeepTag::TAdt,
            vec![
                symbol("Dict"),
                encode_host_type(key)?,
                encode_host_type(value)?,
            ],
        ),
        HostTypeTerm::Tuple(items) => node(
            DeepTag::TTuple,
            items
                .iter()
                .map(encode_host_type)
                .collect::<Option<Vec<_>>>()?,
        ),
        HostTypeTerm::Tensor(tensor) => {
            let mut children = tensor
                .dims
                .iter()
                .map(encode_dim)
                .collect::<Option<Vec<_>>>()?;
            children.push(node(DeepTag::TPrim, vec![symbol(tensor.precision.name())]));
            node(DeepTag::TTensor, children)
        }
        HostTypeTerm::PolymorphicTensor(tensor) => {
            let mut children = match &tensor.shape {
                HostShapeTerm::Concrete(dims) => {
                    dims.iter().map(encode_dim).collect::<Option<Vec<_>>>()?
                }
                HostShapeTerm::Polymorphic(slots) => slots
                    .iter()
                    .map(|slot| match slot {
                        HostShapeSlot::Dim(dim) => encode_dim(dim),
                        HostShapeSlot::RankVariable(name) => {
                            Some(node(DeepTag::DRank, vec![symbol(name)]))
                        }
                    })
                    .collect::<Option<Vec<_>>>()?,
            };
            children.push(match &tensor.precision {
                HostPrecisionTerm::Concrete(prim) => {
                    node(DeepTag::TPrim, vec![symbol(prim.name())])
                }
                HostPrecisionTerm::Variable(name) => node(DeepTag::TVar, vec![symbol(name)]),
            });
            node(DeepTag::TTensor, children)
        }
        HostTypeTerm::InferenceVariable(_) | HostTypeTerm::Never => return None,
    })
}

/// Encode one dimension. A literal extent wider than the Deep integer atom
/// has no spelling; report that rather than clamping it to a different
/// tensor shape.
fn encode_dim(dim: &DimInfo) -> Option<Expr> {
    let span = chelis_deep::Span::new(0, 0);
    Some(match dim {
        DimInfo::Lit(value) => Expr::node(
            DeepTag::DLit,
            MetaMap::default(),
            vec![Expr::Atom(Atom::Int(i64::try_from(*value).ok()?), span)],
            span,
        ),
        DimInfo::Named(name, _) => Expr::node(
            DeepTag::DName,
            MetaMap::default(),
            vec![Expr::Atom(Atom::Name(name.clone()), span)],
            span,
        ),
    })
}

/// Rewrite every `(t-var {} X)` reachable from `expr` — including inside
/// metadata maps — to `env[X]`.
///
/// This is the whole of the Phase-3 substitution environment: instead of
/// threading a parallel type binding through `lower_host_expr`'s typing
/// context, the specialization lowers a *concrete clone* of the generic body
/// through the untouched pipeline. Everything downstream (constructor
/// instantiation, match-arm binder types, tensor-helper extraction) then sees
/// an ordinary monomorphic program and needs no knowledge of this module.
pub(crate) fn substitute_type_vars_in_deep(expr: &Expr, env: &HashMap<String, Expr>) -> Expr {
    if env.is_empty() {
        return expr.clone();
    }
    if let Some(replacement) = type_var_replacement(expr, env) {
        return replacement;
    }
    match expr {
        Expr::List(list, span) => Expr::List(
            List {
                elements: list
                    .elements
                    .iter()
                    .map(|child| substitute_type_vars_in_deep(child, env))
                    .collect(),
            },
            *span,
        ),
        Expr::Node(node, span) => Expr::node(
            node.tag(),
            substitute_type_vars_in_meta(node.meta(), env),
            node.children_slice()
                .iter()
                .map(|child| substitute_type_vars_in_deep(child, env))
                .collect(),
            *span,
        ),
        Expr::Map(meta, span) => Expr::Map(substitute_type_vars_in_meta(meta, env), *span),
        Expr::MetaExpr(meta, span) => Expr::MetaExpr(
            chelis_deep::ast::MetaExpr {
                entries: meta
                    .entries
                    .iter()
                    .map(|(key, value)| (key.clone(), substitute_type_vars_in_deep(value, env)))
                    .collect(),
                expr: Box::new(substitute_type_vars_in_deep(&meta.expr, env)),
            },
            *span,
        ),
        Expr::BareList(items, span) => Expr::BareList(
            items
                .iter()
                .map(|item| substitute_type_vars_in_deep(item, env))
                .collect(),
            *span,
        ),
        _ => expr.clone(),
    }
}

fn substitute_type_vars_in_meta(meta: &MetaMap, env: &HashMap<String, Expr>) -> MetaMap {
    MetaMap {
        entries: meta
            .entries
            .iter()
            .map(|(key, value)| (key.clone(), substitute_type_vars_in_deep(value, env)))
            .collect(),
    }
}

fn type_var_replacement(expr: &Expr, env: &HashMap<String, Expr>) -> Option<Expr> {
    let (tag, children) = match expr {
        Expr::List(list, _) => (
            list.tag()?,
            if list.elements.len() > 2 {
                &list.elements[2..]
            } else {
                &[] as &[Expr]
            },
        ),
        Expr::Node(node, _) => (node.tag(), node.children_slice()),
        _ => return None,
    };
    if tag != DeepTag::TVar {
        return None;
    }
    let Some(Expr::Atom(Atom::Name(name), _)) = children.first() else {
        return None;
    };
    env.get(name).cloned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host_type_state::decode_host_type;
    use chelis_types::types::Prim;

    fn scalar(prim: Prim) -> HostTypeTerm {
        HostTypeTerm::Scalar(HostPrecisionTerm::Concrete(prim))
    }

    #[test]
    fn canonical_key_separates_instantiations() {
        let f32_key = canonical_signature_key(
            &[HostTypeTerm::Adt("Box".into(), vec![scalar(Prim::F32)])],
            &scalar(Prim::Bool),
        );
        let int_key = canonical_signature_key(
            &[HostTypeTerm::Adt("Box".into(), vec![scalar(Prim::Int64)])],
            &scalar(Prim::Bool),
        );
        assert_ne!(f32_key, int_key);
        assert_eq!(f32_key, "(Box[f32])->bool");
    }

    #[test]
    fn mono_symbol_is_a_stable_c_identifier() {
        let key = canonical_signature_key(&[scalar(Prim::F32)], &scalar(Prim::Bool));
        let symbol = mono_symbol("Coral.Internal.Hamt.from_pairs_rec", &key);
        assert!(
            symbol.starts_with("Coral_Internal_Hamt_from_pairs_rec__mono_"),
            "{symbol}"
        );
        assert!(
            symbol
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_'),
            "{symbol}"
        );
        // Stability is the point: an unstable symbol makes the emitted `.c`
        // non-reproducible (chelis#1002).
        assert_eq!(
            symbol,
            mono_symbol("Coral.Internal.Hamt.from_pairs_rec", &key)
        );
    }

    #[test]
    fn per_callee_specialization_cap_is_reachable_and_fail_loud() {
        // The count cap is the bound the `(a, a)` doubling shape never
        // reaches (the signature-size cap fires first), so it needs its own
        // coverage or it is a bound nothing proves.
        reset_mono_state();
        for index in 0..MONO_SPECIALIZATION_CAP {
            let params = vec![HostTypeTerm::Adt(
                format!("Payload{index}"),
                vec![scalar(Prim::F32)],
            )];
            intern_specialization("widget", &params, &scalar(Prim::Bool))
                .unwrap_or_else(|_| panic!("specialization {index} is under the cap"));
        }
        // A repeat of an already-interned signature is a memo hit and must
        // not consume cap budget.
        let repeat = vec![HostTypeTerm::Adt(
            "Payload0".into(),
            vec![scalar(Prim::F32)],
        )];
        intern_specialization("widget", &repeat, &scalar(Prim::Bool))
            .expect("memo hit does not mint");

        let over = vec![HostTypeTerm::Adt(
            "Overflow".into(),
            vec![scalar(Prim::F32)],
        )];
        let rejection = intern_specialization("widget", &over, &scalar(Prim::Bool))
            .expect_err("one past the cap must reject");
        let rendered = rejection.describe("widget");
        assert!(rendered.contains("per-callee cap"), "{rendered}");
        assert!(rendered.contains("[05-UNS-1]"), "{rendered}");
        assert!(rendered.contains("polymorphic recursion"), "{rendered}");
        reset_mono_state();
    }

    #[test]
    fn two_callees_sanitizing_to_one_identifier_collide_loudly() {
        // `A.f` and `A_f` both sanitize to `A_f`, so at one signature they
        // mint the same symbol. Emitting both would collapse two
        // specializations into one C definition, and the emitter's
        // duplicate-symbol check cannot see it.
        reset_mono_state();
        let params = [scalar(Prim::F32)];
        let ret = scalar(Prim::Bool);
        let first = intern_specialization("A.f", &params, &ret).expect("first callee interns");
        let rejection =
            intern_specialization("A_f", &params, &ret).expect_err("colliding callee rejects");
        let rendered = rejection.describe("A_f");
        assert!(rendered.contains(&first), "{rendered}");
        assert!(rendered.contains("[05-UNS-1]"), "{rendered}");
        reset_mono_state();
    }

    #[test]
    fn encode_decode_round_trips_every_concrete_shape() {
        let cases = vec![
            scalar(Prim::F32),
            HostTypeTerm::Unit,
            HostTypeTerm::List(Box::new(scalar(Prim::Int64))),
            HostTypeTerm::Option(Box::new(HostTypeTerm::Adt(
                "Box".into(),
                vec![scalar(Prim::F32)],
            ))),
            HostTypeTerm::Dict(Box::new(scalar(Prim::String)), Box::new(scalar(Prim::F64))),
            HostTypeTerm::Tuple(vec![scalar(Prim::Bool), scalar(Prim::Int32)]),
            HostTypeTerm::Fn(vec![scalar(Prim::F32)], Box::new(scalar(Prim::Bool))),
            HostTypeTerm::Tensor(TensorType {
                dims: vec![DimInfo::Lit(2), DimInfo::Named("n".into(), None)],
                precision: Prim::F32,
            }),
        ];
        for case in cases {
            let encoded = encode_host_type(&case).expect("concrete term encodes");
            let decoded = decode_host_type(&encoded).expect("encoded term decodes");
            assert_eq!(decoded, case, "round trip for {case:?}");
        }
    }

    #[test]
    fn a_probe_leaves_the_interner_untouched() {
        // chelis#1158 Findings 1 and 4: a speculative lowering must not fix a
        // specialization's FIFO position, consume cap budget, or enqueue work
        // for emission.
        reset_mono_state();
        let params = [scalar(Prim::F32)];
        let ret = scalar(Prim::Bool);
        intern_specialization("real", &params, &ret).expect("real intern");
        {
            let _probe = MonoProbeGuard::begin();
            intern_specialization("probe_only", &[scalar(Prim::Int64)], &ret)
                .expect("probe intern");
            intern_specialization("real", &[scalar(Prim::Int32)], &ret).expect("probe intern");
        }
        // Only the pre-probe pending specialization survives, and the cap
        // budget the probe spent is returned.
        let mut drained = Vec::new();
        while let Some(pending) = pop_pending_specialization() {
            drained.push(pending.callee);
        }
        assert_eq!(drained, vec!["real".to_string()]);
        reset_mono_state();
    }

    #[test]
    fn inference_holes_have_no_deep_spelling() {
        assert!(encode_host_type(&HostTypeTerm::Never).is_none());
        assert!(
            encode_host_type(&HostTypeTerm::InferenceVariable(
                crate::host_type_state::HostInferenceVar(7)
            ))
            .is_none()
        );
    }

    #[test]
    fn bindings_come_from_the_concrete_side_only() {
        let pattern = HostTypeTerm::Adt("Box".into(), vec![HostTypeTerm::TypeVariable("a".into())]);
        let mut env = HashMap::new();
        collect_type_var_bindings(
            &pattern,
            &HostTypeTerm::Adt("Box".into(), vec![scalar(Prim::F32)]),
            &mut env,
        );
        assert_eq!(env.get("a"), Some(&scalar(Prim::F32)));

        // An unresolved concrete side contributes nothing rather than
        // binding the variable to another variable.
        let mut empty = HashMap::new();
        collect_type_var_bindings(
            &pattern,
            &HostTypeTerm::Adt("Box".into(), vec![HostTypeTerm::TypeVariable("b".into())]),
            &mut empty,
        );
        assert!(empty.is_empty());
    }

    #[test]
    fn node_count_grows_with_the_doubling_shape() {
        // `f[a]` calling `f[(a, a)]` doubles the type at every level, which
        // is why the node cap and not the per-callee count cap is what stops
        // polymorphic recursion.
        let mut ty = scalar(Prim::F32);
        for _ in 0..4 {
            ty = HostTypeTerm::Tuple(vec![ty.clone(), ty]);
        }
        assert_eq!(host_type_node_count(&ty), 31);
    }
}
