[package]
name = "chelis-types"
description = "Type checker for the Chelis language"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-deep.workspace = true
chelis-pred.workspace = true
chelis-vocab.workspace = true
half.workspace = true
serde.workspace = true
stacker.workspace = true
thiserror.workspace = true

[dev-dependencies]
chelis-surf.workspace = true
chelis-macros.workspace = true
syn.workspace = true
quote.workspace = true
