[package]
name = "chelis-types"
description = "Type checker for the Chelis language"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-deep.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
chelis-surf.workspace = true
