//! C projections of the same schema that expands the owning Rust structures.

#[doc(hidden)]
#[derive(Clone, Copy)]
pub enum FieldKind {
    ConstPointer,
    MutPointer,
    ExtentPointer,
    Int64,
    Rank,
    DType,
    Ownership,
    Reserved7,
    Reserved2,
}

impl FieldKind {
    fn declaration(self, name: &str) -> String {
        match self {
            Self::ConstPointer => format!("const void *{name};"),
            Self::MutPointer => format!("void *{name};"),
            Self::ExtentPointer => format!("const int64_t *{name};"),
            Self::Int64 => format!("int64_t {name};"),
            Self::Rank => format!("int32_t {name};"),
            Self::DType => format!("chelis_dtype {name};"),
            Self::Ownership => format!("uint8_t {name};"),
            Self::Reserved7 => format!("uint8_t {name}[7];"),
            Self::Reserved2 => format!("uint8_t {name}[2];"),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __abi_c_fields {
    ([] { $($field:ident: $kind:ident,)* }) => {
        &[$((stringify!($field), $crate::render::FieldKind::$kind)),*]
    };
}

fn declaration(name: &str, fields: &[(&str, FieldKind)]) -> String {
    let mut output = String::from("typedef struct {\n");
    for (name, kind) in fields {
        output.push_str("    ");
        output.push_str(&kind.declaration(name));
        output.push('\n');
    }
    output.push_str("} ");
    output.push_str(name);
    output.push_str(";\n");
    output
}

/// Complete generated fragment included by the published runtime header.
pub fn host_views_header() -> String {
    let mut output = String::from(
        "/* Generated by chelis-abi; edit its schema, not this fragment. */\n\
         #ifndef CHELIS_RUNTIME_VIEWS_H\n\
         #define CHELIS_RUNTIME_VIEWS_H\n\
         #include <stdint.h>\n\
         #include \"chelis_runtime_dtype.h\"\n\n",
    );
    output.push_str(&declaration(
        "chelis_read_view",
        crate::__abi_schema!(read, __abi_c_fields, []),
    ));
    output.push_str(&declaration(
        "chelis_write_view",
        crate::__abi_schema!(write, __abi_c_fields, []),
    ));
    output.push_str("#endif\n");
    output
}

/// Internal device packet; adoption requires the separate validated owner.
pub fn device_descriptor_header() -> String {
    let mut output = String::from(
        "/* Generated by chelis-abi; edit its schema, not this fragment. */\n\
         #ifndef CHELIS_DEVICE_DESCRIPTOR_H\n\
         #define CHELIS_DEVICE_DESCRIPTOR_H\n\
         #include \"chelis_runtime_dtype.h\"\n\
         typedef int64_t chelis_device_metadata;\n\
         typedef int32_t chelis_device_rank;\n\n",
    );
    output.push_str(&declaration(
        "chelis_gpu_tensor",
        crate::__abi_schema!(device, __abi_c_fields, []),
    ));
    output.push_str("#endif\n");
    output
}
