[package]
name = "chelis-backend-c"
description = "C code generation backend for the Chelis language"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-ir = { path = "../chelis-ir" }
chelis-types = { path = "../chelis-types" }

[dev-dependencies]
tempfile = "3"
