schema = "3"
[package]
name = "nautilus-quantile-contract"
version = "0.1.0"
compiler = "=0.18.11"
module_prefix = "QuantileContract"
resolver = "2"
description = "Example quantile contract for Nautilus"
license = "MIT"
repository = "https://github.com/Chelis-Lang/chelis"
readme = "README.md"

[dependencies]
nautilus = { path = "fixtures/nautilus" }
