[package]
name = "chelis-backend-hip"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
chelis-ir = { path = "../chelis-ir" }
chelis-types = { path = "../chelis-types" }

[dev-dependencies]
chelis-runtime = { path = "../chelis-runtime" }
serde_json = "1"
tempfile = "3"
