[package]
name = "chelis-ir"
description = "RISC DAG intermediate representation for the Chelis language"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-deep.workspace = true
chelis-types = { path = "../chelis-types" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
chelis-effects.workspace = true
chelis-surf.workspace = true
bincode = "1"
serde_json = "1"
