[package]
name = "chelis-deep"
description = "Deep (s-expression) parser for the Chelis language"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-vocab.workspace = true
serde.workspace = true
thiserror.workspace = true
miette.workspace = true
stacker.workspace = true

[dev-dependencies]
bincode = "1"
proptest = "1"
serde_json = "1"

[lints]
workspace = true
