[package]
name = "chelis-surf"
description = "Surface syntax parser and desugaring for the Chelis language"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-deep.workspace = true
thiserror.workspace = true
miette.workspace = true

[dev-dependencies]
proptest = "1"
