[package]
name = "chelis-validate"
description = "Executable grammar validator for the Chelis language"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-unord.workspace = true
chelis-deep.workspace = true
chelis-macros.workspace = true
chelis-surf.workspace = true
pest = "2"
pest_derive = "2"
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
