keys: List[string] = ["alpha", "beta", "gamma"]
ids: List[i64] = [cast(1, i64), cast(2, i64), cast(3, i64)]
pairs = zip(keys, ids)
enumerated = enumerate(keys)
vocab: Dict[string, i64] = dict_of(pairs)
extended = dict_insert(vocab, "delta", cast(4, i64))
overlay: Dict[string, i64] = dict_of([("beta", cast(20, i64)), ("epsilon", cast(5, i64))])
merged = dict_merge(extended, overlay)
trimmed = dict_remove(merged, "gamma")
key_count = len(vocab)
entries = dict_entries(vocab)
merged_entries = dict_entries(merged)
trimmed_entries = dict_entries(trimmed)
entry_count = len(entries)
trimmed_count = len(trimmed)
has_beta = dict_contains(vocab, "beta")
beta_id = match dict_get(vocab, "beta") with {
  | Some(value) => value
  | None => cast(0, i64)
}
merged_beta_id = match dict_get(merged, "beta") with {
  | Some(value) => value
  | None => cast(0, i64)
}
pairs_view = print(pairs)
enumerated_view = print(enumerated)
keys_view = vocab |> dict_keys |> print
values_view = vocab |> dict_values |> print
entries_view = print(entries)
merged_entries_view = print(merged_entries)
trimmed_entries_view = print(trimmed_entries)
