let xs: List[int64] = [cast(1, int64), cast(2, int64), cast(3, int64), cast(4, int64)]
let mapped = map(fn (x: int64) -> add(x, cast(1, int64)), xs)
let filtered = filter(fn (x: int64) -> eq(mod(x, cast(2, int64)), cast(0, int64)), mapped)
let total = fold(fn (acc: int64, x: int64) -> add(acc, x), cast(0, int64), filtered)
let scanned = scan(fn (acc: int64, x: int64) -> add(acc, x), cast(0, int64), xs)
let buckets = partition(fn (x: int64) -> gt(x, cast(2, int64)), xs)
let exploded = flat_map(fn (x: int64) -> [x, add(x, cast(10, int64))], take(xs, cast(2, int64)))
let exploded_batches = chunk(exploded, cast(2, int64))
let mapped_view = print(mapped)
let filtered_view = print(filtered)
let scanned_view = print(scanned)
let buckets_view = print(buckets)
let exploded_view = print(exploded)
let exploded_batches_view = print(exploded_batches)
let summary = print(string_concat("total=", to_string(total)))
