xs: List[i64] = [1i64, 2i64, 3i64, 4i64]
mapped = map(fn (x: i64) -> add(x, 1i64), xs)
filtered = filter(fn (x: i64) -> (x |> mod(2i64) |> eq(0i64)), mapped)
total = fold(fn (acc: i64, x: i64) -> add(acc, x), 0i64, filtered)
scanned = scan(fn (acc: i64, x: i64) -> add(acc, x), 0i64, xs)
buckets = partition(fn (x: i64) -> gt(x, 2i64), xs)
exploded = flat_map(fn (x: i64) -> [x, add(x, 10i64)], take(xs, 2i64))
exploded_batches = chunk(exploded, 2i64)
mapped_view = print(mapped)
filtered_view = print(filtered)
scanned_view = print(scanned)
buckets_view = print(buckets)
exploded_view = print(exploded)
exploded_batches_view = print(exploded_batches)
summary = "total=" |> string_concat(to_string(total)) |> print
