xs: List[int64] = [cast(1, int64), cast(2, int64), cast(3, int64), cast(4, int64)]
mapped = map(fn (x: int64) -> add(x, cast(1, int64)), xs)
filtered = filter(fn (x: int64) -> eq(mod(x, cast(2, int64)), cast(0, int64)), mapped)
total = fold(fn (acc: int64, x: int64) -> add(acc, x), cast(0, int64), filtered)
scanned = scan(fn (acc: int64, x: int64) -> add(acc, x), cast(0, int64), xs)
buckets = partition(fn (x: int64) -> gt(x, cast(2, int64)), xs)
exploded = flat_map(fn (x: int64) -> [x, add(x, cast(10, int64))], take(xs, cast(2, int64)))
exploded_batches = chunk(exploded, cast(2, int64))
mapped_view = print(mapped)
filtered_view = print(filtered)
scanned_view = print(scanned)
buckets_view = print(buckets)
exploded_view = print(exploded)
exploded_batches_view = print(exploded_batches)
summary = print(string_concat("total=", to_string(total)))
