let xs: List[f32] = [1.0, 2.0]
let ys = concat(xs, [3.0, 4.0])
let prefix = take(ys, cast(3, int64))
let suffix = drop(ys, cast(1, int64))
let item_count = numel(to_tensor(ys))
let roundtrip = to_list(to_tensor(ys))
let token_rows: List[List[int64]] = [[cast(1, int64), cast(2, int64)], [cast(3, int64)]]
let flat_tokens = flatten(token_rows)
let token_batches = chunk(flat_tokens, cast(2, int64))
let padded = pad_sequences(token_rows, cast(0, int64))
let report = string_concat(string_concat("len=", to_string(len(ys))), string_concat(", items=", string_concat(to_string(item_count), string_concat(", shape=", string_concat(to_string(shape(padded, 0)), string_concat("x", to_string(shape(padded, 1))))))))
let printed = print(report)
let prefix_view = print(prefix)
let suffix_view = print(suffix)
let flat_tokens_view = print(flat_tokens)
let token_batches_view = print(token_batches)
let roundtrip_view = print(roundtrip)
