[package]
name = "chelis-cli"
description = "CLI for the Chelis language compiler"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "chelis"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
chelis-deep.workspace = true
chelis-surf.workspace = true
chelis-types = { path = "../chelis-types" }
chelis-ir = { path = "../chelis-ir" }
chelis-backend-c = { path = "../chelis-backend-c" }
chelis-backend-hip = { path = "../chelis-backend-hip" }
chelis-lsp.workspace = true
chelis-tide.workspace = true
chelis-validate.workspace = true
serde_json = "1"

[dev-dependencies]
assert_cmd = "2"
cargo-husky = { version = "1", default-features = false, features = ["user-hooks"] }
predicates = "3"
tempfile = "3"
