[package]
name = "chelis-effects"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-deep.workspace = true
chelis-types.workspace = true
chelis-vocab.workspace = true

[dev-dependencies]
chelis-macros.workspace = true
chelis-surf.workspace = true
