#!/usr/bin/env python3
"""Check Devenv package layouts and native product behavior."""

from __future__ import annotations

import argparse
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Callable, Mapping


REPO_ROOT = Path(__file__).resolve().parents[1]
EXPECTED_OUTPUT_KEYS = frozenset(
    {
        "outputs.chelis",
        "outputs.chelis-runtime",
        "outputs.chelisup",
        "outputs.default",
    }
)
REQUIRED_WORKSPACE_MEMBERS = ("chelis-cli", "chelis-runtime", "chelisup")
Runner = Callable[..., subprocess.CompletedProcess[str]]


class CheckError(ValueError):
    """A Devenv package output violates its contract."""


@dataclass(frozen=True)
class BuildOutputs:
    paths: Mapping[str, Path]

    def path(self, name: str) -> Path:
        return self.paths[name]


@dataclass(frozen=True)
class WorkspaceGraph:
    path: Path
    members: frozenset[str]


def parse_build_outputs(text: str) -> BuildOutputs:
    try:
        raw = json.loads(text)
    except json.JSONDecodeError as error:
        raise CheckError(f"the Devenv build result is not valid JSON: {error}") from error
    if not isinstance(raw, dict):
        raise CheckError("the Devenv build result must be a JSON object")
    if frozenset(raw) != EXPECTED_OUTPUT_KEYS:
        raise CheckError(
            "the Devenv build result must contain the exact output set: "
            f"{sorted(raw)!r}"
        )

    parsed: dict[str, Path] = {}
    for key, value in raw.items():
        if not isinstance(value, str) or not value:
            raise CheckError(f"the Devenv output {key} must contain a path")
        path = Path(value)
        if not path.is_dir():
            raise CheckError(f"the Devenv output {key} is not a directory: {path}")
        parsed[key.removeprefix("outputs.")] = path

    if parsed["default"].resolve() != parsed["chelis"].resolve():
        raise CheckError("the default output must alias the chelis output")
    return BuildOutputs(paths=MappingProxyType(parsed))


def parse_workspace_graph(path: Path) -> WorkspaceGraph:
    if not path.is_file():
        raise CheckError(f"the checked-in workspace graph does not exist: {path}")
    generated = path.read_text(encoding="utf-8")
    lines = generated.splitlines()
    expected_stamp = "# This file was @generated by crate2nix 0.15.0 with the command:"
    expected_command = (
        '#   "generate" "--no-default-features" "--features" '
        '"chelis-cli/smt" "--output" "Cargo.nix"'
    )
    digest = re.compile(r"# chelis-crate2nix-input-sha256: [0-9a-f]{64}")
    valid_provenance = (
        len(lines) >= 4
        and lines[0] == ""
        and digest.fullmatch(lines[1]) is not None
        and lines[2] == expected_stamp
        and lines[3] == expected_command
    )
    if not valid_provenance:
        raise CheckError("the checked-in workspace graph has invalid provenance")

    workspace_match = re.search(
        r"(?ms)^  workspaceMembers = \{\n(?P<body>.*?)^  \};$",
        generated,
    )
    if workspace_match is None:
        raise CheckError("the checked-in workspace graph has no workspaceMembers block")
    workspace_members = frozenset(
        re.findall(
            r'(?m)^    "([^"]+)" = rec \{$',
            workspace_match.group("body"),
        )
    )
    missing = [
        member for member in REQUIRED_WORKSPACE_MEMBERS if member not in workspace_members
    ]
    if missing:
        raise CheckError(
            f"the checked-in workspace graph is missing {', '.join(missing)}"
        )
    return WorkspaceGraph(path=path, members=workspace_members)


def _string_list(value: object, location: str) -> tuple[str, ...]:
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise CheckError(f"{location} must be a list of strings")
    return tuple(value)


def _package_shapes(contracts: object) -> Mapping[str, Mapping[str, object]]:
    if not isinstance(contracts, dict):
        raise CheckError("the Nix package contracts must be an object")
    raw_shapes = contracts.get("packageShapes")
    if not isinstance(raw_shapes, dict):
        raise CheckError("the Nix package contracts must define packageShapes")
    required_names = {"chelis", "chelis-runtime", "chelisup"}
    if set(raw_shapes) != required_names:
        raise CheckError("the Nix package contracts must define the exact package set")
    shapes: dict[str, Mapping[str, object]] = {}
    for name, value in raw_shapes.items():
        if not isinstance(value, dict):
            raise CheckError(f"packageShapes.{name} must be an object")
        shapes[name] = value
    return MappingProxyType(shapes)


def _inventory(package: Path) -> tuple[str, ...]:
    return tuple(sorted(str(path.relative_to(package)) for path in package.rglob("*")))


def check_inventories(outputs: BuildOutputs, contracts: object) -> None:
    shapes = _package_shapes(contracts)
    for name, shape in shapes.items():
        package = outputs.path(name)
        expected = tuple(sorted(_string_list(shape.get("inventory"), f"{name}.inventory")))
        actual = _inventory(package)
        if actual != expected:
            raise CheckError(
                f"the {name} package inventory differs: "
                f"expected={expected!r}, actual={actual!r}"
            )

        for relative in _string_list(shape.get("required"), f"{name}.required"):
            if not (package / relative).exists():
                raise CheckError(f"the {name} package is missing {relative}")
        for relative in _string_list(shape.get("forbidden"), f"{name}.forbidden"):
            if (package / relative).exists():
                raise CheckError(f"the {name} package contains forbidden path {relative}")

        allowed = frozenset(
            _string_list(
                shape.get("allowedProductExecutables"),
                f"{name}.allowedProductExecutables",
            )
        )
        actual_executables = frozenset(
            relative
            for relative in actual
            if (package / relative).is_file()
            and os.access(package / relative, os.X_OK)
        )
        if actual_executables != allowed:
            raise CheckError(
                f"the {name} executable set differs: "
                f"expected={sorted(allowed)!r}, actual={sorted(actual_executables)!r}"
            )


def _workspace_version() -> str:
    try:
        manifest = tomllib.loads((REPO_ROOT / "Cargo.toml").read_text(encoding="utf-8"))
        version = manifest["workspace"]["package"]["version"]
    except (KeyError, OSError, TypeError, tomllib.TOMLDecodeError) as error:
        raise CheckError(f"the workspace version is unavailable: {error}") from error
    if not isinstance(version, str):
        raise CheckError("the workspace version must be a string")
    return version


def _run_checked(
    command: list[str],
    *,
    runner: Runner,
    **kwargs: object,
) -> subprocess.CompletedProcess[str]:
    completed = runner(
        command,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
        **kwargs,
    )
    if completed.returncode != 0:
        rendered = " ".join(command)
        raise CheckError(
            f"the native command failed ({rendered}): {completed.stderr.strip()}"
        )
    return completed


def check_behavior(
    outputs: BuildOutputs,
    *,
    runner: Runner = subprocess.run,
) -> None:
    chelis = outputs.path("chelis") / "bin/chelis"
    runtime = outputs.path("chelis-runtime")
    chelisup = outputs.path("chelisup") / "bin/chelisup"
    environment = os.environ.copy()
    environment["CHELIS_RUNTIME_DIR"] = str(outputs.path("chelis") / "lib")

    version = _run_checked([str(chelis), "--version"], runner=runner, env=environment)
    expected_version = f"chelis {_workspace_version()}\n"
    if version.stdout != expected_version:
        raise CheckError(
            "the Devenv compiler version differs from the workspace version: "
            f"expected {expected_version!r}, got {version.stdout!r}"
        )
    _run_checked([str(chelis), "--help"], runner=runner, env=environment)

    source_fixture = REPO_ROOT / "crates/chelis-cli/tests/fixtures/release_pipe_stage"
    with tempfile.TemporaryDirectory(prefix="chelis_devenv_fixture_") as raw_dir:
        fixture = Path(raw_dir) / "release-fixture"
        shutil.copytree(source_fixture, fixture)
        _run_checked(
            [str(chelis), "test", "tests"],
            runner=runner,
            cwd=fixture,
            env=environment,
        )

    _run_checked(
        [
            sys.executable,
            str(REPO_ROOT / ".github/scripts/verify_release_smt.py"),
            str(chelis),
        ],
        runner=runner,
        env=environment,
    )

    with tempfile.TemporaryDirectory(prefix="chelis_devenv_runtime_") as raw_dir:
        consumer = Path(raw_dir) / "runtime-consumer"
        command = [
            "cc",
            "-std=c11",
            "-Wall",
            "-Wextra",
            "-Werror",
            f"-I{runtime / 'include'}",
            str(REPO_ROOT / "nix/tests/runtime-consumer.c"),
            str(runtime / "lib/libchelis_runtime.a"),
        ]
        if platform.system() == "Darwin":
            command.extend(["-framework", "Accelerate"])
        else:
            command.extend(["-lopenblas", "-lm", "-lpthread", "-ldl"])
        command.extend(["-o", str(consumer)])
        _run_checked(command, runner=runner, env=environment)
        _run_checked([str(consumer)], runner=runner, env=environment)

    _run_checked([str(chelisup), "--help"], runner=runner, env=environment)
    _run_checked(["bash", "-n", str(chelisup)], runner=runner, env=environment)
    _run_checked(["shellcheck", str(chelisup)], runner=runner, env=environment)


def load_contracts(*, runner: Runner = subprocess.run) -> object:
    completed = _run_checked(
        ["nix", "eval", "--json", "--file", "nix/contracts.nix"],
        runner=runner,
        cwd=REPO_ROOT,
    )
    try:
        return json.loads(completed.stdout)
    except json.JSONDecodeError as error:
        raise CheckError(f"the Nix package contracts are not valid JSON: {error}") from error


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("build_result", type=Path)
    parser.add_argument("workspace_graph", type=Path)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        outputs = parse_build_outputs(args.build_result.read_text(encoding="utf-8"))
        parse_workspace_graph(args.workspace_graph)
        contracts = load_contracts()
        check_inventories(outputs, contracts)
        check_behavior(outputs)
    except (CheckError, OSError) as error:
        print(f"Devenv package check failed: {error}", file=sys.stderr)
        return 1
    print("Devenv package layouts and native behavior match the shared contracts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
