"""Publish the durable prebuilt-cvc5 assets to a GitHub Release tag.

`build-cvc5.yml` builds cvc5 from source per namespace, packs each into a
`<store-key>.tar.gz` + `.sha256`, and uploads them as workflow artifacts. This
helper collects those files and (idempotently) creates-or-updates the
`cvc5-prebuilt-cvc5sys<ver>` prerelease that the smt lanes fetch from
(scripts/ci_cvc5_cache.py `fetch`).

The tag is deliberately NOT `v*`, so it never triggers release.yml's shipped-
release build. `gh release upload --clobber` makes republishing a namespace
idempotent (a manual `force` re-run overwrites the same asset name).

Policy: no shell scripts. Command construction is a pure, unit-tested function
(`build_commands`); `main` runs the commands via subprocess against the `gh`
CLI that ships on the runners.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


RELEASE_NOTES = (
    "Prebuilt cvc5 static libraries linked by the CI `smt` lanes "
    "(scripts/ci_cvc5_cache.py). Auto-generated by build-cvc5.yml; do not edit. "
    "One `<namespace>` tar.gz + `.sha256` per runner target."
)


def asset_files(dist_dir: Path) -> list[Path]:
    """Return the tar.gz + sha256 asset files under `dist_dir`, sorted.

    Only `.tar.gz` and `.tar.gz.sha256` are eligible so a stray file in the
    artifact download never gets published as a release asset.
    """
    files = sorted(
        p
        for p in dist_dir.iterdir()
        if p.is_file() and (p.name.endswith(".tar.gz") or p.name.endswith(".tar.gz.sha256"))
    )
    return files


def build_commands(
    tag: str, files: list[Path], release_exists: bool
) -> list[list[str]]:
    """Pure command plan: create the release if absent, then upload+clobber.

    Kept pure (no IO) so the idempotency contract is unit-testable without a
    live `gh`.
    """
    if not files:
        raise RuntimeError(f"no cvc5 assets to publish for tag {tag}")
    cmds: list[list[str]] = []
    if not release_exists:
        cmds.append(
            [
                "gh",
                "release",
                "create",
                tag,
                "--prerelease",
                "--title",
                tag,
                "--notes",
                RELEASE_NOTES,
            ]
        )
    cmds.append(
        ["gh", "release", "upload", tag, "--clobber", *[str(p) for p in files]]
    )
    return cmds


def release_exists(tag: str) -> bool:
    """True iff a release for `tag` already exists (via `gh release view`)."""
    result = subprocess.run(
        ["gh", "release", "view", tag],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--dir", required=True, help="artifact download dir")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the command plan without running gh",
    )
    args = parser.parse_args(argv)

    files = asset_files(Path(args.dir))
    exists = False if args.dry_run else release_exists(args.tag)
    cmds = build_commands(args.tag, files, exists)

    for cmd in cmds:
        print("+ " + " ".join(cmd))
        if not args.dry_run:
            subprocess.run(cmd, check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
