"""Generate the interim C exclusion inventory from its actual source rosters."""
from __future__ import annotations

import argparse
from pathlib import Path
import re

if __package__:
    from .check_single_compile import tokenize
else:
    from check_single_compile import tokenize

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = Path("docs/book/src/c-support.md")


def literal_roster(source: str, name: str) -> tuple[str, ...]:
    tokens = tokenize(source)
    declarations = [i for i in range(len(tokens) - 1)
                    if tokens[i].text == "const" and tokens[i + 1].text == name]
    if len(declarations) != 1:
        raise ValueError(f"expected one literal roster {name}, found {len(declarations)}")
    start = declarations[0] + 2
    while start < len(tokens) and tokens[start].text not in {"=", ";"}:
        start += 1
    if [t.text for t in tokens[start:start + 3]] != ["=", "&", "["]:
        raise ValueError(f"{name} must be a literal string slice")
    cursor = start + 3
    rows: list[str] = []
    while cursor < len(tokens) and tokens[cursor].text != "]":
        token = tokens[cursor]
        if token.kind != "str" or not re.fullmatch(r"[a-z][a-z0-9_]*", token.text):
            raise ValueError(f"nonliteral identity in {name} at line {token.line}")
        rows.append(token.text)
        cursor += 1
        if cursor < len(tokens) and tokens[cursor].text == ",":
            cursor += 1
        elif cursor >= len(tokens) or tokens[cursor].text != "]":
            raise ValueError(f"invalid separator in {name}")
    if [t.text for t in tokens[cursor:cursor + 2]] != ["]", ";"]:
        raise ValueError(f"unterminated {name}")
    if len(rows) != len(set(rows)):
        raise ValueError(f"duplicate identity in {name}")
    return tuple(rows)


def route_metadata(name: str) -> str:
    """Reviewed route decisions; unknown source additions require a decision."""
    if name == "tensor_scan":
        return "Use eval/test, or rewrite the recurrence with supported tensor primitives."
    raise ValueError(f"missing reviewed route metadata for {name}")


def exclusions(root: Path) -> list[tuple[str, str, str]]:
    compiler = root / "crates/chelis-compiler-api/src/compiler.rs"
    groups = [
        (literal_roster(compiler.read_text(), "HOST_ONLY_BUILTINS"), "Whole checked program"),
    ]
    rows = [(name, scope, route_metadata(name)) for names, scope in groups for name in names]
    if len({row[0] for row in rows}) != len(rows):
        raise ValueError("overlapping exclusion rosters require one reviewed scope")
    return rows


def assertions(root: Path) -> tuple[str, ...]:
    spec = (root / "spec/05-risc-primitives.md").read_text()
    section = spec.split("### 3.6.1 The `test_*` assertion family", 1)[1].split("> **[05-HOST-3]**", 1)[0]
    names = tuple(re.findall(r"`(test_[a-z_]+)`", section))
    if not names or len(names) != len(set(names)):
        raise ValueError("assertion-family inventory is missing or ambiguous")
    builtins = literal_roster((root / "crates/chelis-types/src/builtins.rs").read_text(), "BUILTIN_NAMES")
    if set(names) != {name for name in builtins if name.startswith("test_")}:
        raise ValueError("normative assertion family and builtin vocabulary disagree")
    return names


def render(root: Path) -> str:
    csv_source = (root / "packages/chelis-std/src/io/csv.ch").read_text()
    exported = re.search(r"^export \(([^)]+)\)", csv_source, re.MULTILINE)
    required = {"read_csv", "try_read_csv", "to_csv", "write_csv"}
    if not exported or not required <= {name.strip() for name in exported[1].split(",")}:
        raise ValueError("published CSV alternative no longer exports the cited functions")
    lines = [
        "# C support and exclusions", "",
        "Generated by `scripts/generate_c_support_inventory.py`; edit its route decisions or the owning source, then regenerate. This is an interim exclusion inventory, not a guarantee that every other program compiles.", "",
        "`chelis check` verifies language validity. `chelis build --target c` additionally checks whether the selected program can be emitted. A typed `unsupported` error is a refusal, never an approximate result or a success with a placeholder value.", "",
        "## Explicit build gates", "",
        "These identities come directly from the compiler's exclusion roster. Eval availability remains subject to each operation's ordinary type, effect and runtime prerequisites. Whole checked program means even an entry-unreachable helper is rejected.", "",
        "| Identity | Entry route | Eval/test | C | Rejection scope | Supported alternative |",
        "|---|---|---|---|---|---|",
    ]
    for name, scope, alternative in exclusions(root):
        lines.append(f"| `{name}` | builtin | Available | Rejected | {scope} | {alternative} |")
    lines += [
        "", "Source owner: `crates/chelis-compiler-api/src/compiler.rs::HOST_ONLY_BUILTINS`. The private, same-named kernel-routing roster in `crates/chelis-ir/src/host.rs` chooses the host lane; it is not a C exclusion list. For example, `print`, string operations, `process_run`, the clock reads, `round_to`, and the CSV builtins have compiled host implementations.", "",
        "## Assertions and other live host code", "",
        "The assertion identities "
        + ", ".join(f"`{name}`" for name in assertions(root))
        + " are derived from spec/05 §3.6.1 and checked against the builtin vocabulary. [05-HOST-3] requires host-runtime execution in every language execution mode, and compiled C runs them through the same runtime checks and failure messages as eval, reachable or not.", "",
        "The C host emitter has a closed builtin dispatch and rejects unimplemented live expressions. This catch-all is not a finite roster of missing capabilities.", "",
        "## Structured I/O routes", "",
        "The CSV builtins (`parse_csv`, `to_csv`, and the `csv_*` accessors) run on both lanes through one runtime definition. The source-defined `Std.Io.Csv` module is a separate route whose file reader, string renderer and writer compile through ordinary List/Dict/string/IO support. Its cells are strings, and numeric conversion must be explicit. The line-based reader does not support quoted fields containing embedded newlines ([#954](https://github.com/Chelis-Lang/chelis/issues/954)).", "",
        "`Std.Io.Json` is likewise a separate source-defined route. The removed JSON builtins are not current exclusions. Import resolution needs the `chelis-std` dependency; an unresolved import on both lanes is a dependency error, not evidence of a C capability gap.", "",
        "## Partial surfaces and release boundary", "",
        "| Surface | Eval | C and scope | Owning work / alternative |",
        "|---|---|---|---|",
        "| General function values stored or passed as data | Language-valid forms can execute | Partial; live lowering/ABI forms can refuse | [#909](https://github.com/Chelis-Lang/chelis/issues/909); use direct named calls or a documented admitted higher-order form. |",
        "| `to_string` of tensors/lists | Available | Live C host emission refuses these representations | [#1059](https://github.com/Chelis-Lang/chelis/issues/1059); extract and render admitted scalar elements explicitly. |",
        "| Dimension-generic ADTs read through generic containers | Can execute | Partial; live host lowering can refuse unresolved dimensions/types | [#730](https://github.com/Chelis-Lang/chelis/issues/730), [#1226](https://github.com/Chelis-Lang/chelis/issues/1226), and [coral#26](https://github.com/Chelis-Lang/coral/issues/26). No universal source-level workaround is promised. |",
        "", "These partial surfaces are recorded boundaries, not whole-family bans. Successful concrete cases do not prove all instantiations. The launch contract and executable eval/C receipt are tracked by [#1362](https://github.com/Chelis-Lang/chelis/issues/1362) and [#2102](https://github.com/Chelis-Lang/chelis/issues/2102). GPU limits are described separately in [Backends](backends.md).", "",
        "Regenerate with `.venv/bin/python scripts/generate_c_support_inventory.py --write`; check source agreement with the same command's `--check`. The owning [#1170](https://github.com/Chelis-Lang/chelis/issues/1170) class remains until its interim rosters are derived or retired by the capability table.", "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        text = render(ROOT)
        if args.write:
            (ROOT / OUTPUT).write_text(text)
        elif not (ROOT / OUTPUT).is_file() or (ROOT / OUTPUT).read_text() != text:
            raise ValueError("published C inventory is stale; regenerate and review the diff")
    except (ValueError, OSError, IndexError) as error:
        print(f"C SUPPORT INVENTORY: FAIL: {error}")
        return 1
    print("C SUPPORT INVENTORY: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
