"""Unit tests for scripts/ci_cvc5_cache.py (chelis#583 + durable-asset follow-up).

Covers the pure logic that cannot be validated in CI without a real ~22m cvc5
build: version parsing, stable-key formatting, Release-asset naming,
build-output discovery, the harvest/pack/fetch round-trip + completeness
sentinel, and the warm/cold activate gate. The safety contract under test is
"worst case is no speedup, never a broken build": an incomplete harvest/fetch
must NOT mark the store complete, a sha256 mismatch must NOT extract, and
activate must only export CVC5_DIR for a complete store.
"""

from __future__ import annotations

import argparse
import os
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import mock

import ci_cvc5_cache as mod


SAMPLE_LOCK = """\
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "cvc5-rs"
version = "0.3.2"
dependencies = [
 "cvc5-sys",
]

[[package]]
name = "cvc5-sys"
version = "0.3.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1d580e4bc6b26687ef4fcec1109c81e8dc265cefe9eb21575a126f34a986c100"

[[package]]
name = "serde"
version = "1.0.0"
"""


class ParseVersionTests(unittest.TestCase):
    def test_extracts_cvc5_sys_version_not_cvc5_rs(self):
        # Must read cvc5-sys's version (0.3.1), not the adjacent cvc5-rs 0.3.2.
        self.assertEqual(mod.parse_cvc5_sys_version(SAMPLE_LOCK), "0.3.1")

    def test_missing_cvc5_sys_raises(self):
        lock = '[[package]]\nname = "serde"\nversion = "1.0.0"\n'
        with self.assertRaises(RuntimeError):
            mod.parse_cvc5_sys_version(lock)

    def test_real_repo_lock_has_cvc5_sys(self):
        # Guards against the cvc5-sys block being renamed/removed upstream:
        # if the smt graph drops cvc5-sys, the key step would silently break.
        text = mod.CARGO_LOCK.read_text(encoding="utf-8")
        version = mod.parse_cvc5_sys_version(text)
        self.assertRegex(version, r"^\d+\.\d+\.\d+")


class ComputeKeyTests(unittest.TestCase):
    def test_key_shape_is_rustc_free_v2(self):
        key = mod.compute_key("linux-x86_64", "0.3.1")
        self.assertEqual(key, "cvc5-prebuilt-linux-x86_64-cvc5sys0.3.1-v2")

    def test_key_has_no_rustc_component(self):
        # The chelis#583 follow-up: a stable-toolchain bump must NOT rotate the
        # key (rustc is irrelevant to the harvested cvc5 C++ bytes).
        self.assertNotIn("rustc", mod.compute_key("darwin-arm64", "0.3.1"))

    def test_key_excludes_cargo_lock_hash(self):
        # Same cvc5-sys/os -> identical key regardless of the rest of the lock.
        a = mod.compute_key("linux-x86_64", "0.3.1")
        b = mod.compute_key("linux-x86_64", "0.3.1")
        self.assertEqual(a, b)

    def test_key_changes_on_solver_version(self):
        a = mod.compute_key("linux-x86_64", "0.3.1")
        b = mod.compute_key("linux-x86_64", "0.4.0")
        self.assertNotEqual(a, b)

    def test_namespace_separates_lanes(self):
        keys = {mod.compute_key(ns, "0.3.1") for ns in mod.NAMESPACES}
        self.assertEqual(len(keys), 3)


class AssetNamingTests(unittest.TestCase):
    def test_tag_is_per_version_and_not_v_prefixed(self):
        tag = mod.asset_tag("0.3.1")
        self.assertEqual(tag, "cvc5-prebuilt-cvc5sys0.3.1")
        # Must not collide with release.yml's `v*` shipped-release trigger.
        self.assertFalse(tag.startswith("v"))

    def test_asset_filename_is_key_plus_targz(self):
        name = mod.asset_filename("linux-glibc231", "0.3.1")
        self.assertEqual(name, "cvc5-prebuilt-linux-glibc231-cvc5sys0.3.1-v2.tar.gz")

    def test_asset_filenames_unique_per_namespace(self):
        names = {mod.asset_filename(ns, "0.3.1") for ns in mod.NAMESPACES}
        self.assertEqual(len(names), 3)


class Sha256SidecarTests(unittest.TestCase):
    def test_parses_leading_hex(self):
        digest = "a" * 64
        self.assertEqual(mod._parse_sha256_sidecar(f"{digest}  file.tar.gz\n"), digest)

    def test_rejects_non_hex(self):
        self.assertIsNone(mod._parse_sha256_sidecar("not-a-digest file\n"))
        self.assertIsNone(mod._parse_sha256_sidecar(""))


def _make_built_cvc5(root: Path) -> Path:
    """Create a minimal but COMPLETE fake from-source cvc5 tree and return it.

    Mirrors the layout cvc5-sys leaves at OUT_DIR/cvc5 after a source build:
    version-base.cmake, the include/ header tree, the generated build/include/
    headers, libcvc5.a, and the bundled static deps under build/deps/lib/.
    """
    cvc5 = root / "target" / "debug" / "build" / "cvc5-sys-abc123" / "out" / "cvc5"
    (cvc5 / "cmake").mkdir(parents=True)
    (cvc5 / "cmake" / "version-base.cmake").write_text(
        'set(CVC5_LAST_RELEASE "1.3.1")\n'
    )
    (cvc5 / "include" / "cvc5" / "c").mkdir(parents=True)
    (cvc5 / "include" / "cvc5" / "c" / "cvc5.h").write_text("/* api */\n")
    (cvc5 / "include" / "cvc5" / "cvc5.h").write_text("/* cpp api */\n")
    (cvc5 / "build" / "include" / "cvc5").mkdir(parents=True)
    (cvc5 / "build" / "include" / "cvc5" / "cvc5_export.h").write_text("#define X\n")
    (cvc5 / "build" / "src").mkdir(parents=True)
    (cvc5 / "build" / "src" / "libcvc5.a").write_bytes(b"\x00ar\x00")
    (cvc5 / "build" / "deps" / "lib").mkdir(parents=True)
    for dep in ("cadical", "picpoly", "picpolyxx", "gmp"):
        (cvc5 / "build" / "deps" / "lib" / f"lib{dep}.a").write_bytes(b"\x00ar\x00")
    return cvc5


class FindBuiltCvc5Tests(unittest.TestCase):
    def test_finds_built_tree_under_target(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            found = mod.find_built_cvc5(root / "target")
            self.assertEqual(found, built)

    def test_returns_none_when_lib_absent(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            (built / "build" / "src" / "libcvc5.a").unlink()
            self.assertIsNone(mod.find_built_cvc5(root / "target"))

    def test_returns_none_on_empty_target(self):
        with TemporaryDirectory() as td:
            (Path(td) / "target").mkdir()
            self.assertIsNone(mod.find_built_cvc5(Path(td) / "target"))


class HarvestTests(unittest.TestCase):
    def test_complete_harvest_writes_sentinel_and_is_warm(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            dest = root / "cache" / "linux-x86_64"
            self.assertTrue(mod.harvest(built, dest))
            self.assertTrue((dest / mod.SENTINEL_NAME).is_file())
            self.assertTrue(mod.is_warm(dest))
            for rel in mod.REQUIRED_DEST:
                self.assertTrue((dest / rel).exists(), rel)
            self.assertTrue((dest / "build" / "deps" / "lib" / "libgmp.a").is_file())

    def test_incomplete_source_does_not_mark_complete(self):
        # Missing build/include/ (a bindgen input) must NOT yield a sentinel,
        # so a future activate stays cold -> from-source rebuild, never a
        # broken link.
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            import shutil as _sh

            _sh.rmtree(built / "build" / "include")
            dest = root / "cache" / "linux-x86_64"
            self.assertFalse(mod.harvest(built, dest))
            self.assertFalse((dest / mod.SENTINEL_NAME).exists())
            self.assertFalse(mod.is_warm(dest))

    def test_missing_deps_lib_does_not_mark_complete(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            import shutil as _sh

            _sh.rmtree(built / "build" / "deps" / "lib")
            dest = root / "cache" / "linux-x86_64"
            self.assertFalse(mod.harvest(built, dest))
            self.assertFalse(mod.is_warm(dest))

    def test_harvest_overwrites_stale_partial(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            dest = root / "cache" / "linux-x86_64"
            dest.mkdir(parents=True)
            (dest / "stale.txt").write_text("junk\n")
            (dest / mod.SENTINEL_NAME).write_text("complete\n")
            self.assertTrue(mod.harvest(built, dest))
            self.assertFalse((dest / "stale.txt").exists())
            self.assertTrue(mod.is_warm(dest))


class ActivateGateTests(unittest.TestCase):
    def test_is_warm_requires_both_lib_and_sentinel(self):
        with TemporaryDirectory() as td:
            dest = Path(td) / "cache"
            (dest / "build" / "src").mkdir(parents=True)
            # lib present, sentinel absent -> cold.
            (dest / "build" / "src" / "libcvc5.a").write_bytes(b"\x00")
            self.assertFalse(mod.is_warm(dest))
            # sentinel present, lib absent -> cold.
            (dest / "build" / "src" / "libcvc5.a").unlink()
            (dest / mod.SENTINEL_NAME).write_text("complete\n")
            self.assertFalse(mod.is_warm(dest))
            # both present -> warm.
            (dest / "build" / "src" / "libcvc5.a").write_bytes(b"\x00")
            self.assertTrue(mod.is_warm(dest))


class HarvestOutputTests(unittest.TestCase):
    """The `complete` step output gates the dedicated actions/cache/save."""

    def _run_harvest(self, env: dict, target_root: Path | None) -> str:
        with TemporaryDirectory() as td:
            out = Path(td) / "gh_output"
            out.write_text("")
            patched = {"GITHUB_OUTPUT": str(out), **env}
            with mock.patch.dict(os.environ, patched, clear=False):
                if "CVC5_DIR" not in env:
                    os.environ.pop("CVC5_DIR", None)
                root = target_root if target_root is not None else Path(td) / "empty"
                with mock.patch.object(mod, "REPO_ROOT", root):
                    args = argparse.Namespace(dir=str(Path(td) / "cache"))
                    mod.cmd_harvest(args)
            return out.read_text()

    def test_warm_emits_complete_false(self):
        text = self._run_harvest({"CVC5_DIR": "/somewhere"}, None)
        self.assertIn("complete=false", text)

    def test_no_build_emits_complete_false(self):
        with TemporaryDirectory() as td:
            (Path(td) / "target").mkdir()
            text = self._run_harvest({}, Path(td))
            self.assertIn("complete=false", text)

    def test_cold_complete_build_emits_complete_true(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            _make_built_cvc5(root)
            text = self._run_harvest({}, root)
            self.assertIn("complete=true", text)


class PackTests(unittest.TestCase):
    def _harvested(self, root: Path) -> Path:
        built = _make_built_cvc5(root)
        dest = root / "store"
        self.assertTrue(mod.harvest(built, dest))
        return dest

    def test_pack_produces_targz_and_matching_sha256(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            store = self._harvested(root)
            out = root / "art" / "cvc5.tar.gz"
            digest = mod.pack(store, out)
            self.assertTrue(out.is_file())
            sidecar = Path(str(out) + ".sha256")
            self.assertTrue(sidecar.is_file())
            self.assertEqual(mod._parse_sha256_sidecar(sidecar.read_text()), digest)
            self.assertEqual(mod.sha256_file(out), digest)

    def test_pack_refuses_incomplete_store(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            store = root / "store"
            (store / "build" / "src").mkdir(parents=True)  # no sentinel/lib
            with self.assertRaises(RuntimeError):
                mod.pack(store, root / "out.tar.gz")


class SafeExtractTests(unittest.TestCase):
    def test_roundtrip_reproduces_layout(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            store = root / "store"
            self.assertTrue(mod.harvest(built, store))
            tar = root / "a.tar.gz"
            mod.pack(store, tar)
            dest = root / "extracted"
            mod.safe_extract(tar, dest)
            for rel in mod.REQUIRED_DEST:
                self.assertTrue((dest / rel).exists(), rel)

    def test_rejects_path_traversal_member(self):
        import tarfile

        with TemporaryDirectory() as td:
            root = Path(td)
            payload = root / "evil"
            payload.write_text("x\n")
            tar = root / "evil.tar.gz"
            with tarfile.open(tar, "w:gz") as t:
                t.add(payload, arcname="../escape.txt")
            with self.assertRaises(RuntimeError):
                mod.safe_extract(tar, root / "dest")

    def test_rejects_symlink_member(self):
        import os as _os
        import tarfile

        with TemporaryDirectory() as td:
            root = Path(td)
            (root / "real.txt").write_text("x\n")
            _os.symlink(root / "real.txt", root / "link")
            tar = root / "link.tar.gz"
            with tarfile.open(tar, "w:gz") as t:
                t.add(root / "link", arcname="link")
            with self.assertRaises(RuntimeError):
                mod.safe_extract(tar, root / "dest")


class FetchTests(unittest.TestCase):
    """cmd_fetch: durable Release-asset download+verify+extract, always exit 0."""

    def _prepare_asset(self, root: Path) -> tuple[Path, Path, str]:
        """Return (tar_path, sha_path, asset_name) for a valid packed store."""
        built = _make_built_cvc5(root)
        store = root / "producer-store"
        self.assertTrue(mod.harvest(built, store))
        name = mod.asset_filename("linux-x86_64", "0.3.1")
        tar = root / name
        mod.pack(store, tar)
        return tar, Path(str(tar) + ".sha256"), name

    def _run_fetch(
        self,
        root: Path,
        assets_json,
        downloader,
    ) -> tuple[str, Path]:
        """Run cmd_fetch with injected release metadata + downloader. Returns
        (github_output_text, dest_dir)."""
        lock = root / "Cargo.lock"
        lock.write_text(SAMPLE_LOCK, encoding="utf-8")
        dest = root / "consumer-store"
        gh_out = root / "gh_output"
        gh_out.write_text("")
        env = {
            "GITHUB_OUTPUT": str(gh_out),
            "GITHUB_REPOSITORY": "Chelis-Lang/chelis",
        }
        with mock.patch.dict(os.environ, env, clear=False), mock.patch.object(
            mod, "CARGO_LOCK", lock
        ), mock.patch.object(
            mod, "_release_assets", lambda tag: assets_json
        ), mock.patch.object(
            mod, "_http_download", downloader
        ):
            rc = mod.cmd_fetch(argparse.Namespace(namespace="linux-x86_64", dir=str(dest)))
        self.assertEqual(rc, 0)  # ALWAYS exits 0
        return gh_out.read_text(), dest

    def _copy_downloader(self, tar: Path, sha: Path):
        """A downloader that maps browser_download_url back to local files."""

        def dl(url: str, dest: Path, token=None) -> None:
            src = tar if url.endswith(".tar.gz") else sha
            import shutil as _sh

            _sh.copy2(src, dest)

        return dl

    def test_happy_path_warms_store(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            tar, sha, name = self._prepare_asset(root)
            assets = {
                name: {"url": "http://x/" + name},
                name + ".sha256": {"url": "http://x/" + name + ".sha256"},
            }
            text, dest = self._run_fetch(root, assets, self._copy_downloader(tar, sha))
            self.assertIn("warm=true", text)
            self.assertTrue(mod.is_warm(dest))

    def test_missing_release_falls_back_cold(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            tar, sha, _ = self._prepare_asset(root)
            text, dest = self._run_fetch(root, None, self._copy_downloader(tar, sha))
            self.assertIn("warm=false", text)
            self.assertFalse(mod.is_warm(dest))

    def test_asset_absent_from_release_falls_back_cold(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            tar, sha, _ = self._prepare_asset(root)
            text, dest = self._run_fetch(root, {}, self._copy_downloader(tar, sha))
            self.assertIn("warm=false", text)
            self.assertFalse(mod.is_warm(dest))

    def test_sha256_mismatch_does_not_extract(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            tar, sha, name = self._prepare_asset(root)
            # Corrupt the sidecar to a valid-but-wrong digest.
            sha.write_text(("b" * 64) + f"  {name}\n", encoding="utf-8")
            assets = {
                name: {"url": "http://x/" + name},
                name + ".sha256": {"url": "http://x/" + name + ".sha256"},
            }
            text, dest = self._run_fetch(root, assets, self._copy_downloader(tar, sha))
            self.assertIn("warm=false", text)
            self.assertFalse(mod.is_warm(dest))
            # Nothing should have been extracted.
            self.assertFalse((dest / "build" / "src" / "libcvc5.a").exists())

    def test_incomplete_archive_does_not_mark_warm(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            # Pack a store that is missing a REQUIRED_DEST path, but force a
            # sentinel so pack() accepts it, then re-verify fetch's finalize
            # rejects it. Simpler: build a tar lacking build/deps/lib.
            import tarfile

            built = _make_built_cvc5(root)
            store = root / "s"
            self.assertTrue(mod.harvest(built, store))
            import shutil as _sh

            _sh.rmtree(store / "build" / "deps" / "lib")
            name = mod.asset_filename("linux-x86_64", "0.3.1")
            tar = root / name
            with tarfile.open(tar, "w:gz") as t:
                for child in sorted(store.iterdir()):
                    t.add(child, arcname=child.name)
            digest = mod.sha256_file(tar)
            sha = Path(str(tar) + ".sha256")
            sha.write_text(f"{digest}  {name}\n", encoding="utf-8")
            assets = {
                name: {"url": "http://x/" + name},
                name + ".sha256": {"url": "http://x/" + name + ".sha256"},
            }
            text, dest = self._run_fetch(root, assets, self._copy_downloader(tar, sha))
            self.assertIn("warm=false", text)
            self.assertFalse(mod.is_warm(dest))

    def test_already_warm_skips_download(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            tar, sha, name = self._prepare_asset(root)
            lock = root / "Cargo.lock"
            lock.write_text(SAMPLE_LOCK, encoding="utf-8")
            dest = root / "consumer-store"
            # Pre-warm dest so fetch must short-circuit.
            built = _make_built_cvc5(root / "pre")
            self.assertTrue(mod.harvest(built, dest))
            gh_out = root / "gh_output"
            gh_out.write_text("")

            def _boom(url, d, token=None):  # must NOT be called
                raise AssertionError("download attempted on an already-warm store")

            with mock.patch.dict(
                os.environ, {"GITHUB_OUTPUT": str(gh_out)}, clear=False
            ), mock.patch.object(mod, "CARGO_LOCK", lock), mock.patch.object(
                mod, "_http_download", _boom
            ):
                rc = mod.cmd_fetch(
                    argparse.Namespace(namespace="linux-x86_64", dir=str(dest))
                )
            self.assertEqual(rc, 0)
            self.assertIn("warm=true", gh_out.read_text())

    def test_missing_sha256_sidecar_falls_back_cold(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            tar, sha, name = self._prepare_asset(root)
            # Release lists the tar but NOT its .sha256 sidecar.
            assets = {name: {"url": "http://x/" + name}}
            text, dest = self._run_fetch(root, assets, self._copy_downloader(tar, sha))
            self.assertIn("warm=false", text)
            self.assertFalse(mod.is_warm(dest))

    def test_download_error_falls_back_cold(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            tar, sha, name = self._prepare_asset(root)
            assets = {
                name: {"url": "http://x/" + name},
                name + ".sha256": {"url": "http://x/" + name + ".sha256"},
            }

            def _boom(url, dest, token=None):
                raise OSError("network down")

            text, dest = self._run_fetch(root, assets, _boom)
            self.assertIn("warm=false", text)
            self.assertFalse(mod.is_warm(dest))

    def test_garbage_gzip_falls_back_cold(self):
        # A non-gzip payload whose sha256 sidecar MATCHES (so it passes
        # verification) must still fail to open as a tar.gz -> caught -> cold.
        with TemporaryDirectory() as td:
            root = Path(td)
            name = mod.asset_filename("linux-x86_64", "0.3.1")
            garbage = root / name
            garbage.write_bytes(b"this is not a gzip tarball")
            digest = mod.sha256_file(garbage)
            sha = Path(str(garbage) + ".sha256")
            sha.write_text(f"{digest}  {name}\n", encoding="utf-8")
            assets = {
                name: {"url": "http://x/" + name},
                name + ".sha256": {"url": "http://x/" + name + ".sha256"},
            }
            text, dest = self._run_fetch(root, assets, self._copy_downloader(garbage, sha))
            self.assertIn("warm=false", text)
            self.assertFalse(mod.is_warm(dest))


class PlanTests(unittest.TestCase):
    def _run_plan(self, root: Path, assets_json, force: bool = False) -> str:
        lock = root / "Cargo.lock"
        lock.write_text(SAMPLE_LOCK, encoding="utf-8")
        gh_out = root / "gh_output"
        gh_out.write_text("")
        env = {"GITHUB_OUTPUT": str(gh_out)}
        if force:
            env["CVC5_FORCE_REBUILD"] = "1"
        with mock.patch.dict(os.environ, env, clear=False), mock.patch.object(
            mod, "CARGO_LOCK", lock
        ), mock.patch.object(mod, "_release_assets", lambda tag: assets_json):
            if not force:
                os.environ.pop("CVC5_FORCE_REBUILD", None)
            mod.cmd_plan(argparse.Namespace(namespace=None))
        return gh_out.read_text()

    def test_no_release_marks_all_missing(self):
        with TemporaryDirectory() as td:
            text = self._run_plan(Path(td), None)
            for ns in mod.NAMESPACES:
                self.assertIn(f"missing_{ns.replace('-', '_')}=true", text)

    def test_all_present_marks_none_missing(self):
        with TemporaryDirectory() as td:
            assets = {mod.asset_filename(ns, "0.3.1"): {} for ns in mod.NAMESPACES}
            text = self._run_plan(Path(td), assets)
            for ns in mod.NAMESPACES:
                self.assertIn(f"missing_{ns.replace('-', '_')}=false", text)

    def test_partial_presence_is_per_namespace(self):
        with TemporaryDirectory() as td:
            assets = {mod.asset_filename("linux-x86_64", "0.3.1"): {}}
            text = self._run_plan(Path(td), assets)
            self.assertIn("missing_linux_x86_64=false", text)
            self.assertIn("missing_linux_glibc231=true", text)
            self.assertIn("missing_darwin_arm64=true", text)

    def test_force_marks_all_missing_even_when_present(self):
        with TemporaryDirectory() as td:
            assets = {mod.asset_filename(ns, "0.3.1"): {} for ns in mod.NAMESPACES}
            text = self._run_plan(Path(td), assets, force=True)
            for ns in mod.NAMESPACES:
                self.assertIn(f"missing_{ns.replace('-', '_')}=true", text)


class HttpDownloadRedirectTests(unittest.TestCase):
    """REAL (non-mocked) test of `_http_download` against a local HTTP server.

    Locks the private-repo fix: the asset API `url` hop must carry the Bearer
    token + octet-stream Accept, and the 302 redirect to signed storage must be
    followed WITHOUT the Authorization header (leaking the token to a third
    party host, or letting storage reject it, is the bug this guards). The unit
    tests elsewhere mock `_http_download`, so this is the only coverage of the
    actual auth/redirect transport.
    """

    def test_auth_on_api_hop_stripped_on_redirect(self):
        import http.server
        import threading

        payload = b"cvc5-durable-asset-bytes"
        seen = {}

        class Handler(http.server.BaseHTTPRequestHandler):
            def log_message(self, *a):  # silence
                pass

            def do_GET(self):
                if self.path == "/asset":
                    seen["asset_auth"] = self.headers.get("Authorization")
                    seen["asset_accept"] = self.headers.get("Accept")
                    self.send_response(302)
                    self.send_header("Location", f"http://{self.headers['Host']}/signed")
                    self.end_headers()
                elif self.path == "/signed":
                    seen["signed_auth"] = self.headers.get("Authorization")
                    self.send_response(200)
                    self.send_header("Content-Length", str(len(payload)))
                    self.end_headers()
                    self.wfile.write(payload)
                else:  # pragma: no cover
                    self.send_response(404)
                    self.end_headers()

        srv = http.server.HTTPServer(("127.0.0.1", 0), Handler)
        port = srv.server_address[1]
        thread = threading.Thread(target=srv.serve_forever, daemon=True)
        thread.start()
        try:
            with TemporaryDirectory() as td:
                dest = Path(td) / "out.bin"
                mod._http_download(
                    f"http://127.0.0.1:{port}/asset", dest, token="TESTTOKEN"
                )
                self.assertEqual(dest.read_bytes(), payload)
        finally:
            srv.shutdown()
            thread.join(timeout=5)

        # Auth + octet-stream reach the GitHub API hop...
        self.assertEqual(seen.get("asset_auth"), "Bearer TESTTOKEN")
        self.assertEqual(seen.get("asset_accept"), "application/octet-stream")
        # ...but the token is NOT forwarded to the signed storage URL.
        self.assertIsNone(seen.get("signed_auth"))

    def test_no_token_sends_no_auth_header(self):
        import http.server
        import threading

        payload = b"anon"
        seen = {}

        class Handler(http.server.BaseHTTPRequestHandler):
            def log_message(self, *a):
                pass

            def do_GET(self):
                seen["auth"] = self.headers.get("Authorization")
                self.send_response(200)
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers()
                self.wfile.write(payload)

        srv = http.server.HTTPServer(("127.0.0.1", 0), Handler)
        port = srv.server_address[1]
        thread = threading.Thread(target=srv.serve_forever, daemon=True)
        thread.start()
        try:
            with TemporaryDirectory() as td:
                dest = Path(td) / "out.bin"
                mod._http_download(f"http://127.0.0.1:{port}/a", dest, token=None)
                self.assertEqual(dest.read_bytes(), payload)
        finally:
            srv.shutdown()
            thread.join(timeout=5)
        self.assertIsNone(seen.get("auth"))


if __name__ == "__main__":
    unittest.main()
