"""Tests for the commit-message authorship policy.

Run with `.venv/bin/python scripts/test_check_commit_message.py`.
"""

from __future__ import annotations

import importlib.util
import io
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts/check_commit_message.py"

spec = importlib.util.spec_from_file_location("check_commit_message", SCRIPT_PATH)
if spec is None or spec.loader is None:
    raise RuntimeError(f"cannot load {SCRIPT_PATH}")
checker = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = checker
spec.loader.exec_module(checker)


PROHIBITED_MESSAGES = (
    "Co-Authored-By: Claude <noreply@anthropic.com>",
    "Authored-By: Anthropic",
    "Generated with Claude",
    "Co-Authored-By: Codex <noreply@openai.com>",
    "Authored-By: ChatGPT",
    "Generated by OpenAI GPT-4",
    "Co-Authored-By: GitHub Copilot",
    "Co-Authored-By: Kiro <kiro@example.invalid>",
    "Generated by Kiro",
    "Co-Authored-By: AI assistant",
    "Authored-By: LLM",
    "Generated by AI",
)

ALLOWED_MESSAGES = (
    "build(devenv): add a commit message hook",
    "docs: explain AI tensor lowering",
    "refactor: rename the assistant module",
    "test: cover generated output from the compiler",
)


class CommitMessagePolicyTests(unittest.TestCase):
    def test_prohibited_markers_are_rejected(self) -> None:
        for message in PROHIBITED_MESSAGES:
            with self.subTest(message=message):
                self.assertIsNotNone(checker.find_prohibited_marker(message))

    def test_ordinary_messages_are_accepted(self) -> None:
        for message in ALLOWED_MESSAGES:
            with self.subTest(message=message):
                self.assertIsNone(checker.find_prohibited_marker(message))

    def test_main_reports_the_matched_marker(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            message_path = Path(temp_dir) / "COMMIT_EDITMSG"
            message_path.write_text(PROHIBITED_MESSAGES[0], encoding="utf-8")
            stderr = io.StringIO()
            result = checker.main([str(message_path)], stderr=stderr)
        self.assertEqual(result, 1)
        self.assertIn("prohibited AI authorship marker", stderr.getvalue())
        self.assertIn("Matched pattern:", stderr.getvalue())

    def test_main_accepts_a_clean_message(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            message_path = Path(temp_dir) / "COMMIT_EDITMSG"
            message_path.write_text(ALLOWED_MESSAGES[0], encoding="utf-8")
            result = checker.main([str(message_path)], stderr=io.StringIO())
        self.assertEqual(result, 0)

    def test_missing_message_path_fails_at_the_parse_boundary(self) -> None:
        stderr = io.StringIO()
        result = checker.main([], stderr=stderr)
        self.assertEqual(result, 2)
        self.assertIn("requires one commit message file", stderr.getvalue())

    def test_legacy_cargo_husky_installer_is_absent(self) -> None:
        self.assertFalse((REPO_ROOT / ".cargo-husky/hooks/commit-msg").exists())
        manifest = (REPO_ROOT / "crates/chelis-cli/Cargo.toml").read_text(
            encoding="utf-8"
        )
        lock = (REPO_ROOT / "Cargo.lock").read_text(encoding="utf-8")
        self.assertNotIn("cargo-husky", manifest)
        self.assertNotIn('name = "cargo-husky"', lock)


if __name__ == "__main__":
    unittest.main()
