"""Tests for the crate2nix workspace-input digest check."""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
CHECKER = REPO_ROOT / "scripts" / "check_crate2nix_sync.py"


def write_workspace(root: Path, *, members: tuple[str, ...] = ("crates/a", "crates/b")) -> None:
    rendered_members = ", ".join(f'"{member}"' for member in members)
    (root / "Cargo.toml").write_text(
        f'[workspace]\nmembers = [{rendered_members}]\nresolver = "3"\n',
        encoding="utf-8",
    )
    (root / "Cargo.lock").write_text("version = 4\n", encoding="utf-8")
    for index, member in enumerate(members):
        if member.startswith("../"):
            continue
        member_root = root / member
        member_root.mkdir(parents=True)
        (member_root / "Cargo.toml").write_text(
            f'[package]\nname = "fixture-{index}"\nversion = "0.1.0"\n',
            encoding="utf-8",
        )
    (root / "Cargo.nix").write_text(
        "# This file was @generated by crate2nix 0.15.0\n{ pkgs }: { }\n",
        encoding="utf-8",
    )


def run_checker(root: Path, *extra: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CHECKER), "--root", str(root), *extra],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


class Crate2nixSyncTests(unittest.TestCase):
    def test_write_then_check_accepts_matching_inputs(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_workspace(root)

            written = run_checker(root, "--write")
            self.assertEqual(written.returncode, 0, written.stderr)
            self.assertIn("updated Cargo.nix input digest", written.stdout)
            cargo_nix = (root / "Cargo.nix").read_text(encoding="utf-8")
            self.assertTrue(cargo_nix.endswith("\n"))
            self.assertFalse(cargo_nix.endswith("\n\n"))

            checked = run_checker(root)
            self.assertEqual(checked.returncode, 0, checked.stderr)
            self.assertIn("Cargo.nix inputs match", checked.stdout)

    def test_changed_lock_rejects_stale_generated_graph(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_workspace(root)
            self.assertEqual(run_checker(root, "--write").returncode, 0)

            (root / "Cargo.lock").write_text(
                "version = 4\n# dependency changed\n",
                encoding="utf-8",
            )
            checked = run_checker(root)
            self.assertEqual(checked.returncode, 1)
            self.assertIn("Cargo.nix input digest is stale", checked.stderr)

    def test_changed_member_manifest_rejects_stale_generated_graph(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_workspace(root)
            self.assertEqual(run_checker(root, "--write").returncode, 0)

            (root / "crates" / "a" / "Cargo.toml").write_text(
                '[package]\nname = "fixture-a"\nversion = "0.2.0"\n',
                encoding="utf-8",
            )
            checked = run_checker(root)
            self.assertEqual(checked.returncode, 1)
            self.assertIn("Cargo.nix input digest is stale", checked.stderr)

    def test_missing_digest_is_an_error(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_workspace(root)

            checked = run_checker(root)
            self.assertEqual(checked.returncode, 1)
            self.assertIn("Cargo.nix input digest is missing", checked.stderr)

    def test_workspace_member_cannot_escape_the_repository(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_workspace(root, members=("../outside",))

            checked = run_checker(root, "--write")
            self.assertEqual(checked.returncode, 2)
            self.assertIn("workspace member must stay below the repository root", checked.stderr)

    def test_workspace_members_must_be_nonempty(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_workspace(root, members=())

            checked = run_checker(root, "--write")
            self.assertEqual(checked.returncode, 2)
            self.assertIn("workspace.members must be a nonempty array", checked.stderr)

    def test_missing_cargo_nix_fails_at_the_parse_boundary(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_workspace(root)
            (root / "Cargo.nix").unlink()

            checked = run_checker(root)
            self.assertEqual(checked.returncode, 2)
            self.assertIn("required file does not exist", checked.stderr)


if __name__ == "__main__":
    unittest.main()
