"""Tests for the native Devenv package output checker.

Run with `.venv/bin/python -m unittest scripts.test_check_devenv_package_outputs`.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path

from scripts.check_devenv_package_outputs import (
    CheckError,
    check_behavior,
    check_inventories,
    check_workspace_artifact,
    parse_build_outputs,
    parse_workspace_artifact,
)


CONTRACTS = {
    "packageShapes": {
        "chelis": {
            "inventory": [
                "bin",
                "include",
                "lib",
                "bin/chelis",
                "include/chelis_runtime.h",
                "lib/libchelis_runtime.a",
            ],
            "required": [
                "bin/chelis",
                "include/chelis_runtime.h",
                "lib/libchelis_runtime.a",
            ],
            "forbidden": ["bin/chelisup"],
            "allowedProductExecutables": ["bin/chelis"],
        },
        "chelis-runtime": {
            "inventory": [
                "include",
                "lib",
                "include/chelis_runtime.h",
                "lib/libchelis_runtime.a",
            ],
            "required": [
                "include/chelis_runtime.h",
                "lib/libchelis_runtime.a",
            ],
            "forbidden": ["bin/chelis", "bin/chelisup"],
            "allowedProductExecutables": [],
        },
        "chelisup": {
            "inventory": [
                "bin",
                "libexec",
                "bin/chelisup",
                "libexec/chelisup",
            ],
            "required": ["bin/chelisup", "libexec/chelisup"],
            "forbidden": ["bin/chelis"],
            "allowedProductExecutables": ["bin/chelisup", "libexec/chelisup"],
        },
    }
}


def _write_file(path: Path, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("fixture\n", encoding="utf-8")
    if executable:
        path.chmod(0o755)


def _make_workspace_artifact(root: Path) -> Path:
    artifact = root / "workspace-graph"
    _write_file(artifact / "default.nix")
    generated = artifact / "crate/Cargo-generated.nix"
    generated.parent.mkdir(parents=True)
    generated.write_text(
        "\n"
        "# This file was @generated by crate2nix 0.15.0 with the command:\n"
        "  workspaceMembers = {\n"
        '    "chelis-cli" = rec {\n'
        "    };\n"
        '    "chelis-runtime" = rec {\n'
        "    };\n"
        '    "chelisup" = rec {\n'
        "    };\n"
        "  };\n",
        encoding="utf-8",
    )
    return artifact


def _make_outputs(root: Path) -> dict[str, str]:
    chelis = root / "chelis"
    _write_file(chelis / "bin/chelis", executable=True)
    _write_file(chelis / "include/chelis_runtime.h")
    _write_file(chelis / "lib/libchelis_runtime.a")

    runtime = root / "runtime"
    _write_file(runtime / "include/chelis_runtime.h")
    _write_file(runtime / "lib/libchelis_runtime.a")

    chelisup = root / "chelisup"
    _write_file(chelisup / "bin/chelisup", executable=True)
    _write_file(chelisup / "libexec/chelisup", executable=True)

    return {
        "outputs.chelis": str(chelis),
        "outputs.chelis-runtime": str(runtime),
        "outputs.chelisup": str(chelisup),
        "outputs.default": str(chelis),
    }


class DevenvPackageOutputTests(unittest.TestCase):
    def test_complete_build_result_and_exact_inventories_pass(self) -> None:
        with tempfile.TemporaryDirectory() as raw_dir:
            data = _make_outputs(Path(raw_dir))
            parsed = parse_build_outputs(json.dumps(data))
            check_inventories(parsed, CONTRACTS)
        self.assertEqual(
            set(parsed.paths),
            {"chelis", "chelis-runtime", "chelisup", "default"},
        )

    def test_workspace_artifact_contains_each_required_member(self) -> None:
        with tempfile.TemporaryDirectory() as raw_dir:
            artifact = _make_workspace_artifact(Path(raw_dir))
            parsed = parse_workspace_artifact(
                json.dumps(
                    {"chelis.rust.workspaceGraph.generatedCargoNix": str(artifact)}
                )
            )
            check_workspace_artifact(parsed)

    def test_workspace_artifact_with_an_invalid_generator_stamp_fails(self) -> None:
        stamp = "# This file was @generated by crate2nix 0.15.0 with the command:"
        with tempfile.TemporaryDirectory() as raw_dir:
            artifact = _make_workspace_artifact(Path(raw_dir))
            generated = artifact / "crate/Cargo-generated.nix"
            valid = generated.read_text(encoding="utf-8")
            invalid_stamps = (
                stamp.replace("0.15.0", "0.15.0-untrusted"),
                "# note: @generated by crate2nix 0.15.0",
                f"# wrong first stamp\n{stamp}",
            )
            for invalid_stamp in invalid_stamps:
                with self.subTest(stamp=invalid_stamp):
                    generated.write_text(
                        valid.replace(stamp, invalid_stamp),
                        encoding="utf-8",
                    )
                    with self.assertRaisesRegex(CheckError, "crate2nix 0.15.0"):
                        check_workspace_artifact(artifact)

    def test_workspace_artifact_without_one_member_fails(self) -> None:
        with tempfile.TemporaryDirectory() as raw_dir:
            artifact = _make_workspace_artifact(Path(raw_dir))
            generated = artifact / "crate/Cargo-generated.nix"
            generated.write_text(
                generated.read_text(encoding="utf-8").replace(
                    '    "chelisup" = rec {',
                    '    "missing" = rec {',
                )
                + 'otherReference = "chelisup";\n',
                encoding="utf-8",
            )
            with self.assertRaisesRegex(CheckError, "chelisup"):
                check_workspace_artifact(artifact)

    def test_workspace_artifact_result_rejects_an_extra_key(self) -> None:
        with tempfile.TemporaryDirectory() as raw_dir:
            artifact = _make_workspace_artifact(Path(raw_dir))
            with self.assertRaisesRegex(CheckError, "workspace graph build"):
                parse_workspace_artifact(
                    json.dumps(
                        {
                            "chelis.rust.workspaceGraph.generatedCargoNix": str(
                                artifact
                            ),
                            "other": str(artifact),
                        }
                    )
                )

    def test_missing_or_extra_output_fails_at_the_parse_boundary(self) -> None:
        with tempfile.TemporaryDirectory() as raw_dir:
            data = _make_outputs(Path(raw_dir))
            fixtures = []
            missing = dict(data)
            del missing["outputs.default"]
            fixtures.append(missing)
            extra = dict(data)
            extra["outputs.other"] = extra["outputs.chelis"]
            fixtures.append(extra)
            for fixture in fixtures:
                with self.subTest(keys=sorted(fixture)):
                    with self.assertRaisesRegex(CheckError, "exact output set"):
                        parse_build_outputs(json.dumps(fixture))

    def test_default_output_must_alias_chelis(self) -> None:
        with tempfile.TemporaryDirectory() as raw_dir:
            root = Path(raw_dir)
            data = _make_outputs(root)
            other = root / "other"
            other.mkdir()
            data["outputs.default"] = str(other)
            with self.assertRaisesRegex(CheckError, "default output"):
                parse_build_outputs(json.dumps(data))

    def test_missing_or_extra_inventory_path_fails(self) -> None:
        with tempfile.TemporaryDirectory() as raw_dir:
            root = Path(raw_dir)
            data = _make_outputs(root)
            parsed = parse_build_outputs(json.dumps(data))
            (root / "chelis/include/chelis_runtime.h").unlink()
            with self.assertRaisesRegex(CheckError, "inventory differs"):
                check_inventories(parsed, CONTRACTS)

        with tempfile.TemporaryDirectory() as raw_dir:
            root = Path(raw_dir)
            data = _make_outputs(root)
            parsed = parse_build_outputs(json.dumps(data))
            _write_file(root / "runtime/undeclared")
            with self.assertRaisesRegex(CheckError, "inventory differs"):
                check_inventories(parsed, CONTRACTS)

    def test_behavior_checks_cover_compiler_runtime_launcher_and_smt(self) -> None:
        commands: list[tuple[str, ...]] = []

        def fake_runner(
            command: list[str],
            **_kwargs: object,
        ) -> subprocess.CompletedProcess[str]:
            commands.append(tuple(command))
            stdout = "chelis 0.18.1\n" if command[-1] == "--version" else ""
            return subprocess.CompletedProcess(command, 0, stdout, "")

        with tempfile.TemporaryDirectory() as raw_dir:
            parsed = parse_build_outputs(json.dumps(_make_outputs(Path(raw_dir))))
            check_behavior(parsed, runner=fake_runner)

        flattened = [" ".join(command) for command in commands]
        self.assertTrue(any(command.endswith("bin/chelis --version") for command in flattened))
        self.assertTrue(any(command.endswith("bin/chelis --help") for command in flattened))
        self.assertTrue(any("chelis test tests" in command for command in flattened))
        self.assertTrue(any("verify_release_smt.py" in command for command in flattened))
        self.assertTrue(any(command.startswith("cc -std=c11") for command in flattened))
        self.assertTrue(any(command.endswith("bin/chelisup --help") for command in flattened))
        self.assertTrue(any("bash -n" in command for command in flattened))
        self.assertTrue(any(command.startswith("shellcheck ") for command in flattened))

    def test_behavior_checks_reject_an_incorrect_compiler_version(self) -> None:
        def wrong_version_runner(
            command: list[str],
            **_kwargs: object,
        ) -> subprocess.CompletedProcess[str]:
            stdout = "chelis 999.0.0\n" if command[-1] == "--version" else ""
            return subprocess.CompletedProcess(command, 0, stdout, "")

        with tempfile.TemporaryDirectory() as raw_dir:
            parsed = parse_build_outputs(json.dumps(_make_outputs(Path(raw_dir))))
            with self.assertRaisesRegex(CheckError, "0.18.1"):
                check_behavior(parsed, runner=wrong_version_runner)

    def test_failed_behavior_command_names_the_command(self) -> None:
        def failed_runner(
            command: list[str],
            **_kwargs: object,
        ) -> subprocess.CompletedProcess[str]:
            return subprocess.CompletedProcess(command, 7, "", "fixture failure")

        with tempfile.TemporaryDirectory() as raw_dir:
            parsed = parse_build_outputs(json.dumps(_make_outputs(Path(raw_dir))))
            with self.assertRaisesRegex(CheckError, "--version"):
                check_behavior(parsed, runner=failed_runner)


if __name__ == "__main__":
    unittest.main()
