"""Tests for the commit-message authorship policy.

Run with
`uv run --managed-python --python 3.11 --no-project python
scripts/test_check_commit_message.py`.
"""

from __future__ import annotations

import importlib.util
import io
import os
import re
import shlex
import subprocess
import sys
import tempfile
import unittest
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts/check_commit_message.py"

spec = importlib.util.spec_from_file_location("check_commit_message", SCRIPT_PATH)
if spec is None or spec.loader is None:
    raise RuntimeError(f"cannot load {SCRIPT_PATH}")
checker = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = checker
spec.loader.exec_module(checker)


PROHIBITED_MESSAGES = (
    "Co-Authored-By: Claude <noreply@anthropic.com>",
    "Authored-By: Anthropic",
    "Generated with Claude",
    "Co-Authored-By: Codex <noreply@openai.com>",
    "Authored-By: ChatGPT",
    "Generated by OpenAI GPT-4",
    "Co-Authored-By: GitHub Copilot",
    "Co-Authored-By: Kiro <kiro@example.invalid>",
    "Generated by Kiro",
    "Co-Authored-By: AI assistant",
    "Authored-By: LLM",
    "Generated by AI",
)

ALLOWED_MESSAGES = (
    "build(devenv): add a commit message hook",
    "docs: explain AI tensor lowering",
    "refactor: rename the assistant module",
    "test: cover generated output from the compiler",
)
CARGO_HUSKY_DEPENDENCY = (
    'cargo-husky = { version = "1", default-features = false, '
    'features = ["user-hooks"] }'
)


@dataclass(frozen=True)
class CargoHuskyFallback:
    checker_path: str
    interpreter_paths: tuple[str, str, str]
    uv_command: str
    dependency: str
    locked_version: str

    @classmethod
    def parse(cls, hook: str, manifest: str, lock: str) -> CargoHuskyFallback:
        if not hook.startswith("#!/bin/sh\n"):
            raise ValueError("the cargo-husky hook must use POSIX sh")

        checker_path = "scripts/check_commit_message.py"
        interpreter_paths = (
            "$DEVENV_STATE/venv/bin/python",
            ".devenv/state/venv/bin/python",
            ".venv/bin/python",
        )
        missing_hook_paths = [
            path for path in (checker_path, *interpreter_paths) if path not in hook
        ]
        if missing_hook_paths:
            raise ValueError(
                "the cargo-husky hook must use the shared checker and managed Python: "
                f"{missing_hook_paths!r}"
            )
        uv_command = (
            "uv run --managed-python --python 3.11 --no-project python"
        )
        if uv_command not in hook:
            raise ValueError(
                "the cargo-husky hook must fall back to uv-managed Python"
            )
        if CARGO_HUSKY_DEPENDENCY not in manifest:
            raise ValueError("the chelis-cli manifest must retain cargo-husky")

        locked = re.search(
            r'(?m)^name = "cargo-husky"\nversion = "(?P<version>[^"]+)"$',
            lock,
        )
        if locked is None:
            raise ValueError("Cargo.lock must retain cargo-husky")
        return cls(
            checker_path=checker_path,
            interpreter_paths=interpreter_paths,
            uv_command=uv_command,
            dependency=CARGO_HUSKY_DEPENDENCY,
            locked_version=locked.group("version"),
        )


class CommitMessagePolicyTests(unittest.TestCase):
    def test_prohibited_markers_are_rejected(self) -> None:
        for message in PROHIBITED_MESSAGES:
            with self.subTest(message=message):
                self.assertIsNotNone(checker.find_prohibited_marker(message))

    def test_ordinary_messages_are_accepted(self) -> None:
        for message in ALLOWED_MESSAGES:
            with self.subTest(message=message):
                self.assertIsNone(checker.find_prohibited_marker(message))

    def test_main_reports_the_matched_marker(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            message_path = Path(temp_dir) / "COMMIT_EDITMSG"
            message_path.write_text(PROHIBITED_MESSAGES[0], encoding="utf-8")
            stderr = io.StringIO()
            result = checker.main([str(message_path)], stderr=stderr)
        self.assertEqual(result, 1)
        self.assertIn("prohibited AI authorship marker", stderr.getvalue())
        self.assertIn("Matched pattern:", stderr.getvalue())

    def test_main_accepts_a_clean_message(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            message_path = Path(temp_dir) / "COMMIT_EDITMSG"
            message_path.write_text(ALLOWED_MESSAGES[0], encoding="utf-8")
            result = checker.main([str(message_path)], stderr=io.StringIO())
        self.assertEqual(result, 0)

    def test_missing_message_path_fails_at_the_parse_boundary(self) -> None:
        stderr = io.StringIO()
        result = checker.main([], stderr=stderr)
        self.assertEqual(result, 2)
        self.assertIn("requires one commit message file", stderr.getvalue())

    def cargo_husky_inputs(self) -> tuple[str, str, str]:
        hook = (REPO_ROOT / ".cargo-husky/hooks/commit-msg").read_text(
            encoding="utf-8"
        )
        manifest = (REPO_ROOT / "crates/chelis-cli/Cargo.toml").read_text(
            encoding="utf-8"
        )
        lock = (REPO_ROOT / "Cargo.lock").read_text(encoding="utf-8")
        return hook, manifest, lock

    def test_cargo_husky_fallback_is_retained(self) -> None:
        fallback = CargoHuskyFallback.parse(*self.cargo_husky_inputs())
        self.assertEqual(fallback.checker_path, "scripts/check_commit_message.py")
        self.assertIn("--managed-python", fallback.uv_command)
        self.assertEqual(fallback.locked_version, "1.5.0")

    def test_cargo_husky_hook_prefers_the_active_devenv_state(self) -> None:
        hook, manifest, lock = self.cargo_husky_inputs()
        fallback = CargoHuskyFallback.parse(hook, manifest, lock)
        self.assertEqual(
            fallback.interpreter_paths[0], "$DEVENV_STATE/venv/bin/python"
        )
        self.assertLess(
            hook.index('$DEVENV_STATE/venv/bin/python'),
            hook.index('.devenv/state/venv/bin/python'),
        )

    def test_cargo_husky_hook_executes_the_active_devenv_interpreter(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            active = Path(temp_dir) / "active"
            active_bin = active / "venv" / "bin"
            active_bin.mkdir(parents=True)
            marker = Path(temp_dir) / "active-python-used"
            python = active_bin / "python"
            python.write_text(
                "#!/bin/sh\n"
                f"printf active > {shlex.quote(str(marker))}\n"
                f"exec {shlex.quote(sys.executable)} \"$@\"\n",
                encoding="utf-8",
            )
            python.chmod(0o755)
            message_path = Path(temp_dir) / "COMMIT_EDITMSG"
            message_path.write_text(ALLOWED_MESSAGES[0], encoding="utf-8")
            environment = os.environ.copy()
            environment["DEVENV_STATE"] = str(active)
            result = subprocess.run(
                [str(REPO_ROOT / ".cargo-husky/hooks/commit-msg"), str(message_path)],
                cwd=REPO_ROOT,
                env=environment,
                check=False,
                capture_output=True,
                text=True,
            )
            marker_value = marker.read_text(encoding="utf-8")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(marker_value, "active")

    def test_cargo_husky_hook_has_valid_posix_shell_syntax(self) -> None:
        hook_path = REPO_ROOT / ".cargo-husky/hooks/commit-msg"
        result = subprocess.run(
            ["sh", "-n", str(hook_path)],
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 0, result.stderr)

    def run_cargo_husky_hook(self, message: str) -> subprocess.CompletedProcess[str]:
        with tempfile.TemporaryDirectory() as temp_dir:
            message_path = Path(temp_dir) / "COMMIT_EDITMSG"
            message_path.write_text(message, encoding="utf-8")
            return subprocess.run(
                [str(REPO_ROOT / ".cargo-husky/hooks/commit-msg"), str(message_path)],
                cwd=REPO_ROOT,
                check=False,
                capture_output=True,
                text=True,
            )

    def test_cargo_husky_hook_accepts_an_ordinary_message(self) -> None:
        result = self.run_cargo_husky_hook(ALLOWED_MESSAGES[0])
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_cargo_husky_hook_rejects_a_prohibited_marker(self) -> None:
        result = self.run_cargo_husky_hook(PROHIBITED_MESSAGES[0])
        self.assertEqual(result.returncode, 1)
        self.assertIn("prohibited AI authorship marker", result.stderr)

    def test_incomplete_cargo_husky_fallback_fails_at_parse_boundary(self) -> None:
        hook, manifest, lock = self.cargo_husky_inputs()
        mutations = (
            (hook.replace("scripts/check_commit_message.py", "other.py"), manifest, lock),
            (hook.replace("--managed-python", "--system"), manifest, lock),
            (
                hook.replace("$DEVENV_STATE/venv/bin/python", "$OTHER/bin/python"),
                manifest,
                lock,
            ),
            (hook, manifest.replace(CARGO_HUSKY_DEPENDENCY, ""), lock),
            (hook, manifest, lock.replace('name = "cargo-husky"', 'name = "other"')),
        )
        for mutated in mutations:
            with self.subTest(mutated=mutated):
                with self.assertRaises(ValueError):
                    CargoHuskyFallback.parse(*mutated)

    def test_malformed_cargo_husky_hook_fails_shell_parse(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            hook_path = Path(temp_dir) / "commit-msg"
            hook_path.write_text("#!/bin/sh\nif then\n", encoding="utf-8")
            result = subprocess.run(
                ["sh", "-n", str(hook_path)],
                check=False,
                capture_output=True,
                text=True,
            )
        self.assertNotEqual(result.returncode, 0)


if __name__ == "__main__":
    unittest.main()
