"""Unit tests for scripts/ci_cvc5_cache.py (chelis#583).

Covers the pure logic that cannot be validated in CI without a real ~30m cvc5
build: version parsing, stable-key formatting, build-output discovery, the
harvest copy + completeness sentinel, and the warm/cold activate gate. The
safety contract under test is "worst case is no speedup, never a broken build":
an incomplete harvest must NOT mark the cache complete, and activate must only
export CVC5_DIR for a complete cache.
"""

from __future__ import annotations

import argparse
import os
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import mock

import ci_cvc5_cache as mod


SAMPLE_LOCK = """\
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "cvc5-rs"
version = "0.3.2"
dependencies = [
 "cvc5-sys",
]

[[package]]
name = "cvc5-sys"
version = "0.3.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1d580e4bc6b26687ef4fcec1109c81e8dc265cefe9eb21575a126f34a986c100"

[[package]]
name = "serde"
version = "1.0.0"
"""


class ParseVersionTests(unittest.TestCase):
    def test_extracts_cvc5_sys_version_not_cvc5_rs(self):
        # Must read cvc5-sys's version (0.3.1), not the adjacent cvc5-rs 0.3.2.
        self.assertEqual(mod.parse_cvc5_sys_version(SAMPLE_LOCK), "0.3.1")

    def test_missing_cvc5_sys_raises(self):
        lock = '[[package]]\nname = "serde"\nversion = "1.0.0"\n'
        with self.assertRaises(RuntimeError):
            mod.parse_cvc5_sys_version(lock)

    def test_real_repo_lock_has_cvc5_sys(self):
        # Guards against the cvc5-sys block being renamed/removed upstream:
        # if the smt graph drops cvc5-sys, the key step would silently break.
        text = mod.CARGO_LOCK.read_text(encoding="utf-8")
        version = mod.parse_cvc5_sys_version(text)
        self.assertRegex(version, r"^\d+\.\d+\.\d+")


class ParseRustcTests(unittest.TestCase):
    def test_typical_output(self):
        out = "rustc 1.86.0 (05f9846f8 2025-03-31)"
        self.assertEqual(mod.parse_rustc_version(out), "1.86.0")

    def test_nightly_output(self):
        out = "rustc 1.90.0-nightly (abc123 2025-06-01)"
        self.assertEqual(mod.parse_rustc_version(out), "1.90.0")

    def test_unparseable_does_not_raise(self):
        self.assertEqual(mod.parse_rustc_version(""), "unknown")
        # Sanitized but non-empty for a surprising format.
        self.assertTrue(mod.parse_rustc_version("weird build"))


class ComputeKeyTests(unittest.TestCase):
    def test_key_shape_and_stability(self):
        key = mod.compute_key("linux-x86_64", "0.3.1", "1.86.0")
        self.assertEqual(
            key, "cvc5-prebuilt-linux-x86_64-cvc5sys0.3.1-rustc1.86.0-v1"
        )

    def test_key_excludes_cargo_lock_hash(self):
        # The whole point of chelis#583: the key must not encode anything that
        # changes on an unrelated Cargo.lock bump. Same cvc5-sys/os/rustc ->
        # identical key regardless of the rest of the lockfile.
        a = mod.compute_key("linux-x86_64", "0.3.1", "1.86.0")
        b = mod.compute_key("linux-x86_64", "0.3.1", "1.86.0")
        self.assertEqual(a, b)

    def test_key_changes_on_solver_version(self):
        a = mod.compute_key("linux-x86_64", "0.3.1", "1.86.0")
        b = mod.compute_key("linux-x86_64", "0.4.0", "1.86.0")
        self.assertNotEqual(a, b)

    def test_key_changes_on_rustc(self):
        a = mod.compute_key("linux-x86_64", "0.3.1", "1.86.0")
        b = mod.compute_key("linux-x86_64", "0.3.1", "1.87.0")
        self.assertNotEqual(a, b)

    def test_namespace_separates_lanes(self):
        a = mod.compute_key("linux-x86_64", "0.3.1", "1.86.0")
        b = mod.compute_key("linux-glibc231", "0.3.1", "1.86.0")
        c = mod.compute_key("darwin-arm64", "0.3.1", "1.86.0")
        self.assertEqual(len({a, b, c}), 3)


def _make_built_cvc5(root: Path) -> Path:
    """Create a minimal but COMPLETE fake from-source cvc5 tree and return it.

    Mirrors the layout cvc5-sys leaves at OUT_DIR/cvc5 after a source build:
    version-base.cmake, the include/ header tree, the generated build/include/
    headers, libcvc5.a, and the bundled static deps under build/deps/lib/.
    """
    cvc5 = root / "target" / "debug" / "build" / "cvc5-sys-abc123" / "out" / "cvc5"
    (cvc5 / "cmake").mkdir(parents=True)
    (cvc5 / "cmake" / "version-base.cmake").write_text(
        'set(CVC5_LAST_RELEASE "1.3.1")\n'
    )
    (cvc5 / "include" / "cvc5" / "c").mkdir(parents=True)
    (cvc5 / "include" / "cvc5" / "c" / "cvc5.h").write_text("/* api */\n")
    (cvc5 / "include" / "cvc5" / "cvc5.h").write_text("/* cpp api */\n")
    (cvc5 / "build" / "include" / "cvc5").mkdir(parents=True)
    (cvc5 / "build" / "include" / "cvc5" / "cvc5_export.h").write_text("#define X\n")
    (cvc5 / "build" / "src").mkdir(parents=True)
    (cvc5 / "build" / "src" / "libcvc5.a").write_bytes(b"\x00ar\x00")
    (cvc5 / "build" / "deps" / "lib").mkdir(parents=True)
    for dep in ("cadical", "picpoly", "picpolyxx", "gmp"):
        (cvc5 / "build" / "deps" / "lib" / f"lib{dep}.a").write_bytes(b"\x00ar\x00")
    return cvc5


class FindBuiltCvc5Tests(unittest.TestCase):
    def test_finds_built_tree_under_target(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            found = mod.find_built_cvc5(root / "target")
            self.assertEqual(found, built)

    def test_returns_none_when_lib_absent(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            (built / "build" / "src" / "libcvc5.a").unlink()
            self.assertIsNone(mod.find_built_cvc5(root / "target"))

    def test_returns_none_on_empty_target(self):
        with TemporaryDirectory() as td:
            (Path(td) / "target").mkdir()
            self.assertIsNone(mod.find_built_cvc5(Path(td) / "target"))


class HarvestTests(unittest.TestCase):
    def test_complete_harvest_writes_sentinel_and_is_warm(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            dest = root / "cache" / "linux-x86_64"
            self.assertTrue(mod.harvest(built, dest))
            # Sentinel present -> activate would treat it as warm.
            self.assertTrue((dest / mod.SENTINEL_NAME).is_file())
            self.assertTrue(mod.is_warm(dest))
            # Every required link/bindgen input landed.
            for rel in mod.REQUIRED_DEST:
                self.assertTrue((dest / rel).exists(), rel)
            # The dep static libs came across.
            self.assertTrue((dest / "build" / "deps" / "lib" / "libgmp.a").is_file())

    def test_incomplete_source_does_not_mark_complete(self):
        # Missing build/include/ (a bindgen input) must NOT yield a sentinel,
        # so a future activate stays cold -> from-source rebuild, never a
        # broken link.
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            import shutil as _sh

            _sh.rmtree(built / "build" / "include")
            dest = root / "cache" / "linux-x86_64"
            self.assertFalse(mod.harvest(built, dest))
            self.assertFalse((dest / mod.SENTINEL_NAME).exists())
            self.assertFalse(mod.is_warm(dest))

    def test_missing_deps_lib_does_not_mark_complete(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            import shutil as _sh

            _sh.rmtree(built / "build" / "deps" / "lib")
            dest = root / "cache" / "linux-x86_64"
            self.assertFalse(mod.harvest(built, dest))
            self.assertFalse(mod.is_warm(dest))

    def test_harvest_overwrites_stale_partial(self):
        # A prior partial harvest left junk + a stale sentinel; a fresh
        # complete harvest must clean it and end complete.
        with TemporaryDirectory() as td:
            root = Path(td)
            built = _make_built_cvc5(root)
            dest = root / "cache" / "linux-x86_64"
            dest.mkdir(parents=True)
            (dest / "stale.txt").write_text("junk\n")
            (dest / mod.SENTINEL_NAME).write_text("complete\n")
            self.assertTrue(mod.harvest(built, dest))
            self.assertFalse((dest / "stale.txt").exists())
            self.assertTrue(mod.is_warm(dest))


class ActivateGateTests(unittest.TestCase):
    def test_is_warm_requires_both_lib_and_sentinel(self):
        with TemporaryDirectory() as td:
            dest = Path(td) / "cache"
            (dest / "build" / "src").mkdir(parents=True)
            # lib present, sentinel absent -> cold.
            (dest / "build" / "src" / "libcvc5.a").write_bytes(b"\x00")
            self.assertFalse(mod.is_warm(dest))
            # sentinel present, lib absent -> cold.
            (dest / "build" / "src" / "libcvc5.a").unlink()
            (dest / mod.SENTINEL_NAME).write_text("complete\n")
            self.assertFalse(mod.is_warm(dest))
            # both present -> warm.
            (dest / "build" / "src" / "libcvc5.a").write_bytes(b"\x00")
            self.assertTrue(mod.is_warm(dest))


class HarvestOutputTests(unittest.TestCase):
    """The `complete` step output gates the dedicated actions/cache/save."""

    def _run_harvest(self, env: dict, target_root: Path | None) -> str:
        with TemporaryDirectory() as td:
            out = Path(td) / "gh_output"
            out.write_text("")
            patched = {"GITHUB_OUTPUT": str(out), **env}
            with mock.patch.dict(os.environ, patched, clear=False):
                # Drop CVC5_DIR if not requested (the runner may export it).
                if "CVC5_DIR" not in env:
                    os.environ.pop("CVC5_DIR", None)
                root = target_root if target_root is not None else Path(td) / "empty"
                with mock.patch.object(mod, "REPO_ROOT", root):
                    args = argparse.Namespace(dir=str(Path(td) / "cache"))
                    mod.cmd_harvest(args)
            return out.read_text()

    def test_warm_emits_complete_false(self):
        text = self._run_harvest({"CVC5_DIR": "/somewhere"}, None)
        self.assertIn("complete=false", text)

    def test_no_build_emits_complete_false(self):
        with TemporaryDirectory() as td:
            (Path(td) / "target").mkdir()
            text = self._run_harvest({}, Path(td))
            self.assertIn("complete=false", text)

    def test_cold_complete_build_emits_complete_true(self):
        with TemporaryDirectory() as td:
            root = Path(td)
            _make_built_cvc5(root)
            text = self._run_harvest({}, root)
            self.assertIn("complete=true", text)


if __name__ == "__main__":
    unittest.main()
