import LaCaDiLE.Syntax
import LaCaDiLE.Store
import LaCaDiLE.Typing
import LaCaDiLE.Operational
import LaCaDiLE.AdjointTransform
import LaCaDiLE.Substitution
import LaCaDiLE.AdjointTyping
import LaCaDiLE.AddDim
import LaCaDiLE.Progress
import LaCaDiLE.Preservation
import LaCaDiLE.DimSafety
import LaCaDiLE.EffectCorrectness
import LaCaDiLE.LinearitySoundness
import LaCaDiLE.ADCorrectness
