//! Metal codegen entry point.
//!
//! M2 first cut: emits Objective-C++ host code with embedded MSL kernel
//! strings for **same-shape, contiguous, rank-1** elementwise + fused-elem
//! programs. Reductions land in M4, matmul in M5, and broadcasting/strided
//! layouts will be added incrementally.

use chelis_ir::dag::{Dag, DagNode, DimInfo, NodeId, RiscOp, TensorType};

use crate::blas;
use crate::kernels;
use std::collections::{HashMap, HashSet};

/// Distinct input labels in DAG order.
///
/// Mirrors `chelis_backend_hip::emit::HipEmitter::input_labels`.
pub fn input_labels(dag: &Dag) -> Vec<String> {
    let mut labels = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for node in dag.nodes() {
        if let RiscOp::Load { name } = &node.op
            && seen.insert(name.clone())
        {
            labels.push(name.clone());
        }
    }
    labels
}

/// Output specification for one positional output of the emitted function.
///
/// An output may come from an explicit `Store { name }` node in the DAG OR
/// from a root that has no downstream store (the CLI's regular lowering
/// path produces this shape — DAG roots without `Store`). Mirrors
/// `chelis_backend_hip::emit::HipEmitter::output_specs`.
#[derive(Debug, Clone)]
struct OutputSpec {
    id: NodeId,
    label: String,
    is_store: bool,
}

/// Compute output specs in stable order: Store-tagged nodes first, then any
/// remaining roots that aren't already covered.
fn output_specs(dag: &Dag) -> Vec<OutputSpec> {
    let mut specs = Vec::new();
    let mut seen = std::collections::HashSet::new();

    for node in dag.nodes() {
        if let RiscOp::Store { name } = &node.op
            && seen.insert(node.id)
        {
            specs.push(OutputSpec {
                id: node.id,
                label: name.clone(),
                is_store: true,
            });
        }
    }

    let roots: Vec<NodeId> = if dag.roots().is_empty() {
        dag.nodes().last().map(|n| vec![n.id]).unwrap_or_default()
    } else {
        dag.roots().to_vec()
    };
    for (index, root_id) in roots.into_iter().enumerate() {
        if seen.insert(root_id) {
            specs.push(OutputSpec {
                id: root_id,
                label: format!("root{index}"),
                is_store: false,
            });
        }
    }
    specs
}

/// Output labels in DAG order — `Store { name }` nodes plus any
/// no-Store roots, mirroring `output_specs`. The CLI's `cmd_build_metal`
/// passes this through to the result struct so users can map positional
/// outputs back to symbolic names.
pub fn output_labels(dag: &Dag) -> Vec<String> {
    output_specs(dag).into_iter().map(|s| s.label).collect()
}

/// Old M1-stub helper kept for tests that built against it before M2 emit
/// landed. New callers should use `emit_dag` directly.
pub fn stub_mm_source(func_name: &str) -> String {
    format!(
        r#"// Generated by chelis --target metal (M1 fallback stub)
#import "chelis_metal_runtime.h"
#include "chelis_runtime.h"
#include <stdlib.h>
#include <stdio.h>

extern "C" void {func_name}(chelis_tensor **inputs, int n_in,
                            chelis_tensor **outputs, int n_out) {{
    (void)inputs; (void)n_in; (void)outputs; (void)n_out;
    fprintf(stderr,
        "chelis Metal backend stub: codegen for `{func_name}` not yet implemented\n");
    abort();
}}
"#
    )
}

/// Result of an emit pass — source plus the materialized peak-device-bytes
/// total (sum of all per-op buffer allocations the emitted code performs).
pub struct EmitResult {
    pub mm_source: String,
    /// Total bytes of `chelis_metal_alloc()` calls the emitted host code
    /// will issue. On Apple Silicon (unified memory) this is also peak
    /// system RAM consumed for tensor storage. The CLI prefixes the
    /// formula with that note so users do not double-count against host
    /// allocations.
    pub peak_device_bytes: usize,
}

/// Emit complete Objective-C++ source for a DAG.
///
/// Returns `Ok(EmitResult)` on success, `Err(msg)` if the DAG uses features
/// the M2 emitter does not yet support (broadcasting, strided layouts,
/// rank > 1 with non-trivial layout, partial-axis reductions outside the
/// matmul subgraph, RNG).
pub fn emit_dag(dag: &Dag, func_name: &str) -> Result<EmitResult, String> {
    let mut e = Emitter::new(func_name);
    e.emit(dag)?;
    let peak_device_bytes = e.peak_device_bytes();
    Ok(EmitResult {
        mm_source: e.into_source(),
        peak_device_bytes,
    })
}

/// Per-tensor metadata emitted alongside the host program.
#[derive(Clone)]
struct TensorPlan {
    /// Buffer variable name in the emitted .mm (e.g. `buf_2`).
    buf: String,
    /// MSL element type ("float" / "bool").
    msl_ty: &'static str,
    /// Element count (must be statically known for M2).
    n: usize,
    /// Row-major shape (dimensions listed in declaration order).
    shape: Vec<usize>,
}

struct Emitter {
    func_name: String,
    body: Vec<String>,
    /// Collected MSL kernel sources, one per compute node, in emission order.
    /// `(c_var_for_pso, kernel_name, msl_source)`.
    kernels: Vec<(String, String, String)>,
    /// Per-DAG-node tensor plan — `None` if the node hasn't been materialized
    /// yet (e.g., metadata-only ops we will add later) or fell through to a
    /// rejection path.
    plans: Vec<Option<TensorPlan>>,
    /// DAG nodes that participate in a detected matmul subgraph as the
    /// Expand or Mul intermediate. The emitter skips these when walking
    /// the DAG; the matmul kernel emits at the Sum node instead.
    matmul_consumed: HashSet<usize>,
    /// Sum-node-id → MatmulInfo. emit_node looks up the MatmulInfo here
    /// when reaching the Sum and emits a matmul kernel + dispatch.
    matmuls: HashMap<usize, blas::MatmulInfo>,
}

impl Emitter {
    fn new(func_name: &str) -> Self {
        Self {
            func_name: func_name.to_string(),
            body: Vec::new(),
            kernels: Vec::new(),
            plans: Vec::new(),
            matmul_consumed: HashSet::new(),
            matmuls: HashMap::new(),
        }
    }

    fn emit(&mut self, dag: &Dag) -> Result<(), String> {
        self.plans.resize(dag.nodes().len(), None);
        let inputs = input_labels(dag);
        let specs = output_specs(dag);
        let outputs: Vec<String> = specs.iter().map(|s| s.label.clone()).collect();

        // Pre-walk: detect matmul subgraphs and mark Expand/Mul intermediates
        // as "consumed" so the per-node walk skips them. This is the same
        // shape HIP uses (see chelis_backend_hip::emit::HipEmitter pattern).
        for (sum_id, info) in blas::find_all_matmuls(dag) {
            // Mark the two Expand nodes and the Mul node as consumed.
            // (The Sum itself stays — emit_node dispatches it to the matmul
            // emitter via self.matmuls lookup.)
            if let Some(sum_node) = dag.get(sum_id)
                && sum_node.inputs.len() == 1
            {
                let mul_id = sum_node.inputs[0];
                self.matmul_consumed.insert(mul_id.0);
                if let Some(mul_node) = dag.get(mul_id) {
                    for input in &mul_node.inputs {
                        self.matmul_consumed.insert(input.0);
                    }
                }
            }
            self.matmuls.insert(sum_id.0, info);
        }

        for node in dag.nodes() {
            // Skip Expand/Mul nodes that were folded into a matmul subgraph
            // — they have no standalone kernel emission.
            if self.matmul_consumed.contains(&node.id.0) {
                continue;
            }
            self.emit_node(dag, node, &inputs, &outputs)?;
        }

        // Materialize any output that wasn't already written via an
        // explicit `Store` node. This is the path the CLI's regular
        // lowering uses: a DAG with roots but no Store. Without this,
        // the emitted function would compute results into a device
        // buffer and return without ever writing `outputs[idx]`.
        for (idx, spec) in specs.iter().enumerate() {
            if spec.is_store {
                continue;
            }
            self.emit_root_writeback(idx, spec)?;
        }
        Ok(())
    }

    fn emit_root_writeback(&mut self, idx: usize, spec: &OutputSpec) -> Result<(), String> {
        let plan = self
            .plan_of(spec.id)
            .ok_or_else(|| {
                format!(
                    "Metal emit: root output `{}` (node {}) not materialized",
                    spec.label, spec.id.0
                )
            })?
            .clone();
        let dtype = match plan.msl_ty {
            "float" => "CHELIS_F32",
            "bool" => "CHELIS_BOOL",
            other => {
                return Err(format!(
                    "Metal emit root writeback `{}`: unexpected msl_ty `{}`",
                    spec.label, other
                ));
            }
        };
        let bytes = format!("{}u * sizeof({})", plan.n, plan.msl_ty);
        self.body.push(format!(
            "// root output {idx} = `{}` (node {})",
            spec.label, spec.id.0
        ));
        if plan.shape.is_empty() {
            // Scalar output — chelis_alloc(0, NULL, dtype) per chelis_runtime.h.
            self.body
                .push(format!("outputs[{idx}] = chelis_alloc(0, NULL, {dtype});"));
        } else {
            let shape_lit = plan
                .shape
                .iter()
                .map(|d| format!("(int){d}"))
                .collect::<Vec<_>>()
                .join(", ");
            self.body.push(format!(
                "{{ int shape_{idx}[{}] = {{ {shape_lit} }};",
                plan.shape.len()
            ));
            self.body.push(format!(
                "  outputs[{idx}] = chelis_alloc({}, shape_{idx}, {dtype}); }}",
                plan.shape.len()
            ));
        }
        self.body.push(format!(
            "chelis_metal_device_to_host(outputs[{idx}]->data, {}, {bytes});",
            plan.buf
        ));
        Ok(())
    }

    fn into_source(self) -> String {
        let mut header = String::new();
        header.push_str("// Generated by chelis --target metal (M2)\n");
        header.push_str("#import \"chelis_metal_runtime.h\"\n");
        header.push_str("#include \"chelis_runtime.h\"\n");
        header.push_str("#include <stdint.h>\n");
        header.push_str("#include <stdio.h>\n");
        header.push_str("#include <stdlib.h>\n\n");

        // Kernel source string declarations, one C++11 raw string literal per kernel.
        // The cache key for chelis_metal_get_pipeline is the (NSString*, name) pair,
        // so each kernel must have a stable static NSString *const handle.
        for (var, _name, src) in &self.kernels {
            header.push_str(&format!(
                "static NSString *const {var}_src = @R\"MSL(\n{src})MSL\";\n\n"
            ));
        }

        let mut out = header;
        out.push_str(&format!(
            "extern \"C\" void {}(chelis_tensor **inputs, int n_in, chelis_tensor **outputs, int n_out) {{\n",
            self.func_name
        ));
        out.push_str("    (void)n_in; (void)n_out;\n");
        for line in &self.body {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
        out.push_str("}\n");
        out
    }

    fn emit_node(
        &mut self,
        dag: &Dag,
        node: &DagNode,
        inputs: &[String],
        outputs: &[String],
    ) -> Result<(), String> {
        let id = node.id.0;
        match &node.op {
            RiscOp::Load { name } => self.emit_load(node, name, inputs),
            RiscOp::Store { name } => self.emit_store(dag, node, name, outputs),
            RiscOp::Const { value } => self.emit_const(node, *value),

            // Unary elementwise (M2 first cut).
            RiscOp::Neg
            | RiscOp::Exp
            | RiscOp::Log
            | RiscOp::Sin
            | RiscOp::Sqrt
            | RiscOp::Cos
            | RiscOp::Tan
            | RiscOp::Atan
            | RiscOp::Abs
            | RiscOp::Floor
            | RiscOp::Ceil => self.emit_unary(dag, node),

            // Binary elementwise (M2 first cut: add, mul).
            RiscOp::Add | RiscOp::Mul => self.emit_binary(dag, node),

            // Full-axis rank-1 reductions to scalar (M4 first cut).
            RiscOp::Sum { axis: 0 } => self.emit_reduce(dag, node, kernels::ReduceKind::Sum),
            RiscOp::MaxReduce { axis: 0 } => self.emit_reduce(dag, node, kernels::ReduceKind::Max),
            RiscOp::MinReduce { axis: 0 } => self.emit_reduce(dag, node, kernels::ReduceKind::Min),

            // Matmul (Sum{axis:1} head of expand+mul+sum subgraph; M5).
            RiscOp::Sum { axis: 1 } if self.matmuls.contains_key(&node.id.0) => {
                let info = self.matmuls[&node.id.0].clone();
                self.emit_matmul(node, &info)
            }

            other => Err(format!(
                "Metal M4 emit: node {id} op {other:?} not yet supported \
                 (axis>0 reductions, fused-elem-into-reduction, matmul, \
                 broadcasts/strides land in M4.next/M5)"
            )),
        }
    }

    fn require_static_rank1(
        &self,
        ty: &TensorType,
        ctx: &str,
    ) -> Result<(usize, &'static str), String> {
        if ty.dims.len() != 1 {
            return Err(format!(
                "Metal M2 emit ({ctx}): rank {} not yet supported; M2 first cut handles rank-1 only",
                ty.dims.len()
            ));
        }
        let n = match &ty.dims[0] {
            DimInfo::Lit(n) => *n,
            other => {
                return Err(format!(
                    "Metal M2 emit ({ctx}): dim {other:?} not yet supported; rank-1 with literal extent only"
                ));
            }
        };
        Ok((n, kernels::msl_type(ty.precision)))
    }

    /// Accept rank-1 OR rank-2 with literal extents and f32/bool precision.
    /// Used for ops that work on both ranks (Load, Store, matmul operands,
    /// matmul output). Returns `(total_n, shape, msl_ty)`.
    fn require_static_shape(
        &self,
        ty: &TensorType,
        ctx: &str,
    ) -> Result<(usize, Vec<usize>, &'static str), String> {
        if ty.dims.is_empty() {
            return Err(format!(
                "Metal emit ({ctx}): rank-0 not supported via this path; use scalar Const/reduce instead"
            ));
        }
        if ty.dims.len() > 2 {
            return Err(format!(
                "Metal emit ({ctx}): rank {} not yet supported; rank-1 or rank-2 only in this phase",
                ty.dims.len()
            ));
        }
        let mut shape = Vec::with_capacity(ty.dims.len());
        for d in &ty.dims {
            match d {
                DimInfo::Lit(n) => shape.push(*n),
                other => {
                    return Err(format!(
                        "Metal emit ({ctx}): symbolic dim {other:?} not yet supported"
                    ));
                }
            }
        }
        let n: usize = shape.iter().product();
        Ok((n, shape, kernels::msl_type(ty.precision)))
    }

    fn emit_load(&mut self, node: &DagNode, name: &str, inputs: &[String]) -> Result<(), String> {
        // Loads are the boundary at which rank-2 enters. Use the rank-1-or-2
        // helper so a rank-2 input materializes its plan correctly; downstream
        // ops that don't yet handle rank-2 (unary/binary elementwise without
        // matching shape) will reject via require_static_rank1.
        let (n, shape, msl_ty) = self.require_static_shape(&node.output_type, "Load")?;
        let idx = inputs
            .iter()
            .position(|l| l == name)
            .ok_or_else(|| format!("Load `{name}` not registered in input_labels"))?;
        let buf = format!("buf_{}", node.id.0);
        let bytes = format!("{n}u * sizeof({msl_ty})");
        self.body
            .push(format!("// node {} = Load {name}", node.id.0));
        self.body.push(format!(
            "id<MTLBuffer> {buf} = chelis_metal_alloc({bytes});"
        ));
        self.body.push(format!(
            "chelis_metal_host_to_device({buf}, inputs[{idx}]->data, {bytes});"
        ));
        self.plans[node.id.0] = Some(TensorPlan {
            buf,
            msl_ty,
            n,
            shape,
        });
        Ok(())
    }

    fn emit_const(&mut self, node: &DagNode, value: f64) -> Result<(), String> {
        let (n, msl_ty) = self.require_static_rank1(&node.output_type, "Const")?;
        let buf = format!("buf_{}", node.id.0);
        let bytes = format!("{n}u * sizeof({msl_ty})");
        self.body
            .push(format!("// node {} = Const {value}", node.id.0));
        self.body.push(format!(
            "id<MTLBuffer> {buf} = chelis_metal_alloc({bytes});"
        ));
        // Fill via a small CPU loop; small enough for M2's static-extent
        // first cut. M4 will switch to a fused fill MSL kernel when scale
        // matters.
        self.body.push(format!(
            "{{ {msl_ty} *p = ({msl_ty}*)[{buf} contents]; for (uint i = 0; i < {n}u; ++i) p[i] = ({msl_ty}){value:?}; }}"
        ));
        self.plans[node.id.0] = Some(TensorPlan {
            buf,
            msl_ty,
            n,
            shape: vec![n],
        });
        Ok(())
    }

    fn emit_unary(&mut self, dag: &Dag, node: &DagNode) -> Result<(), String> {
        let in_id = *node
            .inputs
            .first()
            .ok_or_else(|| format!("unary node {} has no input", node.id.0))?;
        let in_plan = self
            .plan_of(in_id)
            .ok_or_else(|| {
                format!(
                    "unary node {} input {} not materialized",
                    node.id.0, in_id.0
                )
            })?
            .clone();
        let (n, msl_ty) = self.require_static_rank1(&node.output_type, "unary")?;
        if in_plan.n != n || in_plan.msl_ty != msl_ty {
            return Err(format!(
                "Metal M2 emit unary node {}: input shape {:?}/{} != output shape [{}]/{} \
                 (no implicit broadcast/cast in M2 first cut)",
                node.id.0, in_plan.shape, in_plan.msl_ty, n, msl_ty,
            ));
        }
        let kernel_name = format!("k_unary_{}", node.id.0);
        let pso_var = format!("pso_{}", node.id.0);
        let body = match &node.op {
            RiscOp::Neg => "    out[tid] = -a[tid];".to_string(),
            other => {
                let f = kernels::unary_func(other).ok_or_else(|| {
                    format!(
                        "Metal M2 emit unary node {}: op {:?} unsupported",
                        node.id.0, other
                    )
                })?;
                format!("    out[tid] = {f}(a[tid]);")
            }
        };
        let params = vec![
            kernels::input_param(0, msl_ty, "a"),
            kernels::output_param(1, msl_ty, "out"),
        ];
        let src = kernels::elementwise_kernel(&kernel_name, &params, &body);
        self.kernels
            .push((pso_var.clone(), kernel_name.clone(), src));

        let out_buf = format!("buf_{}", node.id.0);
        let bytes = format!("{n}u * sizeof({msl_ty})");
        self.body
            .push(format!("// node {} = unary {:?}", node.id.0, node.op));
        self.body.push(format!(
            "id<MTLBuffer> {out_buf} = chelis_metal_alloc({bytes});"
        ));
        self.body.push(format!(
            "id<MTLComputePipelineState> {pso_var} = chelis_metal_get_pipeline({pso_var}_src, @\"{kernel_name}\");"
        ));
        self.body.push(format!("uint32_t n_{} = {n}u;", node.id.0));
        self.body.push(format!(
            "{{ __unsafe_unretained id<MTLBuffer> bufs[2] = {{ {}, {out_buf} }}; chelis_metal_launch({pso_var}, {n}u, MIN((NSUInteger){n}u, 256u), bufs, 2, &n_{}, sizeof(uint32_t)); }}",
            in_plan.buf,
            node.id.0
        ));
        self.plans[node.id.0] = Some(TensorPlan {
            buf: out_buf,
            msl_ty,
            n,
            shape: vec![n],
        });
        let _ = dag;
        Ok(())
    }

    fn emit_binary(&mut self, dag: &Dag, node: &DagNode) -> Result<(), String> {
        if node.inputs.len() != 2 {
            return Err(format!(
                "binary node {} has {} inputs (expected 2)",
                node.id.0,
                node.inputs.len()
            ));
        }
        let a_id = node.inputs[0];
        let b_id = node.inputs[1];
        let a_plan = self
            .plan_of(a_id)
            .ok_or_else(|| format!("binary node {} lhs {} not materialized", node.id.0, a_id.0))?
            .clone();
        let b_plan = self
            .plan_of(b_id)
            .ok_or_else(|| format!("binary node {} rhs {} not materialized", node.id.0, b_id.0))?
            .clone();
        let (n, msl_ty) = self.require_static_rank1(&node.output_type, "binary")?;
        if a_plan.n != n || b_plan.n != n || a_plan.msl_ty != msl_ty || b_plan.msl_ty != msl_ty {
            return Err(format!(
                "Metal M2 emit binary node {}: shape/type mismatch (M2 first cut: same-shape contiguous only)",
                node.id.0
            ));
        }
        let op = kernels::binary_op(&node.op).ok_or_else(|| {
            format!(
                "Metal M2 emit binary node {}: op {:?} unsupported",
                node.id.0, node.op
            )
        })?;
        let kernel_name = format!("k_binary_{}", node.id.0);
        let pso_var = format!("pso_{}", node.id.0);
        let params = vec![
            kernels::input_param(0, msl_ty, "a"),
            kernels::input_param(1, msl_ty, "b"),
            kernels::output_param(2, msl_ty, "out"),
        ];
        let body = format!("    out[tid] = a[tid] {op} b[tid];");
        let src = kernels::elementwise_kernel(&kernel_name, &params, &body);
        self.kernels
            .push((pso_var.clone(), kernel_name.clone(), src));

        let out_buf = format!("buf_{}", node.id.0);
        let bytes = format!("{n}u * sizeof({msl_ty})");
        self.body
            .push(format!("// node {} = binary {:?}", node.id.0, node.op));
        self.body.push(format!(
            "id<MTLBuffer> {out_buf} = chelis_metal_alloc({bytes});"
        ));
        self.body.push(format!(
            "id<MTLComputePipelineState> {pso_var} = chelis_metal_get_pipeline({pso_var}_src, @\"{kernel_name}\");"
        ));
        self.body.push(format!("uint32_t n_{} = {n}u;", node.id.0));
        self.body.push(format!(
            "{{ __unsafe_unretained id<MTLBuffer> bufs[3] = {{ {}, {}, {out_buf} }}; chelis_metal_launch({pso_var}, {n}u, MIN((NSUInteger){n}u, 256u), bufs, 3, &n_{}, sizeof(uint32_t)); }}",
            a_plan.buf,
            b_plan.buf,
            node.id.0
        ));
        self.plans[node.id.0] = Some(TensorPlan {
            buf: out_buf,
            msl_ty,
            n,
            shape: vec![n],
        });
        let _ = dag;
        Ok(())
    }

    fn emit_reduce(
        &mut self,
        _dag: &Dag,
        node: &DagNode,
        kind: kernels::ReduceKind,
    ) -> Result<(), String> {
        let in_id = *node
            .inputs
            .first()
            .ok_or_else(|| format!("reduce node {} has no input", node.id.0))?;
        let in_plan = self
            .plan_of(in_id)
            .ok_or_else(|| {
                format!(
                    "reduce node {} input {} not materialized",
                    node.id.0, in_id.0
                )
            })?
            .clone();
        // M4 first cut: full-axis reduce to scalar, rank-1 contiguous f32 input.
        if in_plan.shape.len() != 1 {
            return Err(format!(
                "Metal M4 emit reduce node {}: rank {} input not yet supported \
                 (rank-1 first cut)",
                node.id.0,
                in_plan.shape.len()
            ));
        }
        if in_plan.msl_ty != "float" {
            return Err(format!(
                "Metal M4 emit reduce node {}: only f32 reductions supported in M4 first cut",
                node.id.0
            ));
        }
        // Output should be rank-0 f32 scalar.
        if !node.output_type.dims.is_empty()
            || node.output_type.precision != chelis_types::types::Prim::F32
        {
            return Err(format!(
                "Metal M4 emit reduce node {}: output must be rank-0 f32 in M4 first cut, got {:?}",
                node.id.0, node.output_type
            ));
        }
        let n = in_plan.n;
        // Single-threadgroup reduction with a fixed power-of-two TG_SIZE
        // (see kernels::REDUCE_TG_SIZE). The kernel's wrap loop strides
        // TG_SIZE elements per iteration, so every n up to TG_SIZE *
        // TG_SIZE = 65536 reduces in one pass. We cap at 4096 for now
        // because this M4 first cut hasn't been benchmarked above that;
        // two-pass reduction for larger inputs lands in M4.next. Reject
        // here so the oracle never silently runs a wrong reduction.
        const SINGLE_TG_LIMIT: usize = 4096;
        if n > SINGLE_TG_LIMIT {
            return Err(format!(
                "Metal M4 emit reduce node {}: n={} exceeds single-threadgroup limit {} \
                 (two-pass reduction is M4.next)",
                node.id.0, n, SINGLE_TG_LIMIT
            ));
        }
        let kernel_name = format!("k_reduce_{}_{}", kind.label(), node.id.0);
        let pso_var = format!("pso_{}", node.id.0);
        let src = kernels::reduce_full_kernel(&kernel_name, kind);
        self.kernels
            .push((pso_var.clone(), kernel_name.clone(), src));

        let out_buf = format!("buf_{}", node.id.0);
        // Output is one float scalar.
        let bytes = "1u * sizeof(float)".to_string();
        self.body
            .push(format!("// node {} = reduce_{}", node.id.0, kind.label()));
        self.body.push(format!(
            "id<MTLBuffer> {out_buf} = chelis_metal_alloc({bytes});"
        ));
        self.body.push(format!(
            "id<MTLComputePipelineState> {pso_var} = chelis_metal_get_pipeline({pso_var}_src, @\"{kernel_name}\");"
        ));
        self.body.push(format!("uint32_t n_{} = {n}u;", node.id.0));
        // Always dispatch a single TG_SIZE-thread threadgroup. The kernel
        // strides over n internally; mismatching tg with n was the source
        // of a critical non-power-of-2 miscompile that the previous fix
        // (clamping tg = n.min(256)) shipped — fixed here by decoupling.
        let tg = kernels::REDUCE_TG_SIZE;
        self.body.push(format!(
            "{{ __unsafe_unretained id<MTLBuffer> bufs[2] = {{ {}, {out_buf} }}; chelis_metal_launch({pso_var}, {tg}u, {tg}u, bufs, 2, &n_{}, sizeof(uint32_t)); }}",
            in_plan.buf,
            node.id.0
        ));
        // Reduction returns a rank-0 scalar in IR semantics
        // (TensorType::scalar_f32() has dims: vec![]). Reflect that in
        // the plan so emit_root_writeback emits chelis_alloc(0, NULL,
        // CHELIS_F32) and the resulting tensor has ndim=0 — matching
        // the IR's contract and what host code asserting on rank would
        // see. The buffer itself still holds 1 float on the device.
        self.plans[node.id.0] = Some(TensorPlan {
            buf: out_buf,
            msl_ty: "float",
            n: 1,
            shape: vec![],
        });
        Ok(())
    }

    fn emit_matmul(&mut self, node: &DagNode, info: &blas::MatmulInfo) -> Result<(), String> {
        // Operands must already be materialized (their Load/Const/etc.
        // emitted earlier in the topological walk; the Expand intermediates
        // were skipped because they're in matmul_consumed).
        let a_plan = self
            .plan_of(info.a)
            .ok_or_else(|| {
                format!(
                    "Metal M5 matmul node {}: lhs operand node {} not materialized",
                    node.id.0, info.a.0
                )
            })?
            .clone();
        let b_plan = self
            .plan_of(info.b)
            .ok_or_else(|| {
                format!(
                    "Metal M5 matmul node {}: rhs operand node {} not materialized",
                    node.id.0, info.b.0
                )
            })?
            .clone();
        if a_plan.shape.len() != 2 || b_plan.shape.len() != 2 {
            return Err(format!(
                "Metal M5 matmul node {}: operand ranks must be 2, got lhs={:?} rhs={:?}",
                node.id.0, a_plan.shape, b_plan.shape
            ));
        }
        if a_plan.msl_ty != "float" || b_plan.msl_ty != "float" {
            return Err(format!(
                "Metal M5 matmul node {}: only f32 supported in M5 first cut",
                node.id.0
            ));
        }

        let kernel_name = format!("k_matmul_{}", node.id.0);
        let pso_var = format!("pso_{}", node.id.0);
        let src = kernels::matmul_tiled_kernel(&kernel_name);
        self.kernels
            .push((pso_var.clone(), kernel_name.clone(), src));

        let out_n = info.m * info.n;
        let out_buf = format!("buf_{}", node.id.0);
        self.body.push(format!(
            "// node {} = matmul {}x{}*{}x{}",
            node.id.0, info.m, info.k, info.k, info.n
        ));
        self.body.push(format!(
            "id<MTLBuffer> {out_buf} = chelis_metal_alloc({out_n}u * sizeof(float));"
        ));
        self.body.push(format!(
            "id<MTLComputePipelineState> {pso_var} = chelis_metal_get_pipeline({pso_var}_src, @\"{kernel_name}\");"
        ));
        self.body.push(format!(
            "{{ struct {{ uint32_t M, N, K; }} mm_uniforms_{} = {{ {}u, {}u, {}u }};",
            node.id.0, info.m, info.n, info.k
        ));
        self.body.push(format!(
            "  __unsafe_unretained id<MTLBuffer> bufs[3] = {{ {}, {}, {out_buf} }};",
            a_plan.buf, b_plan.buf
        ));
        // 2D grid sized exactly to the output (rounded up to TILE);
        // tg=(TILE,TILE,1). The kernel handles the boundary cases via the
        // `(aRow < M && aCol < K) ? ...` guards in matmul_tiled_kernel.
        let tile = kernels::MATMUL_TILE;
        let grid_y = info.m.div_ceil(tile) * tile;
        let grid_x = info.n.div_ceil(tile) * tile;
        self.body.push(format!(
            "  chelis_metal_launch2d({pso_var}, {grid_x}u, {grid_y}u, {tile}u, {tile}u, bufs, 3, &mm_uniforms_{}, sizeof(mm_uniforms_{})); }}",
            node.id.0, node.id.0
        ));
        self.plans[node.id.0] = Some(TensorPlan {
            buf: out_buf,
            msl_ty: "float",
            n: out_n,
            shape: vec![info.m, info.n],
        });
        Ok(())
    }

    fn emit_store(
        &mut self,
        _dag: &Dag,
        node: &DagNode,
        name: &str,
        outputs: &[String],
    ) -> Result<(), String> {
        let in_id = *node
            .inputs
            .first()
            .ok_or_else(|| format!("Store `{name}` has no input"))?;
        let in_plan = self
            .plan_of(in_id)
            .ok_or_else(|| format!("Store `{name}`: input node {} not materialized", in_id.0))?
            .clone();
        let idx = outputs
            .iter()
            .position(|l| l == name)
            .ok_or_else(|| format!("Store `{name}` not registered in output_labels"))?;
        let bytes = format!("{}u * sizeof({})", in_plan.n, in_plan.msl_ty);
        let dtype = match in_plan.msl_ty {
            "float" => "CHELIS_F32",
            "bool" => "CHELIS_BOOL",
            other => {
                return Err(format!(
                    "Metal M2 emit store `{name}`: unexpected msl_ty `{other}`"
                ));
            }
        };
        self.body
            .push(format!("// node {} = Store `{name}`", node.id.0));
        if in_plan.shape.is_empty() {
            // Rank-0 scalar Store: chelis_alloc takes (0, NULL, dtype).
            self.body
                .push(format!("outputs[{idx}] = chelis_alloc(0, NULL, {dtype});"));
        } else {
            let shape_lit = in_plan
                .shape
                .iter()
                .map(|d| format!("(int){d}"))
                .collect::<Vec<_>>()
                .join(", ");
            self.body.push(format!(
                "{{ int shape_store_{idx}[{}] = {{ {shape_lit} }};",
                in_plan.shape.len()
            ));
            self.body.push(format!(
                "  outputs[{idx}] = chelis_alloc({}, shape_store_{idx}, {dtype}); }}",
                in_plan.shape.len()
            ));
        }
        self.body.push(format!(
            "chelis_metal_device_to_host(outputs[{idx}]->data, {}, {bytes});",
            in_plan.buf
        ));
        Ok(())
    }

    /// Sum of per-buffer allocations the emitted host code will issue.
    ///
    /// Each materialized DAG node owns one device buffer (no slot reuse
    /// yet — that's M-phase planner work). Bytes per element follows
    /// the MSL type, matching what the emitter passes to
    /// `chelis_metal_alloc`. On Apple Silicon unified memory this is
    /// also the peak system RAM cost for tensor storage.
    fn peak_device_bytes(&self) -> usize {
        self.plans
            .iter()
            .filter_map(|p| p.as_ref())
            .map(|p| {
                let bytes_per = match p.msl_ty {
                    "float" => 4,
                    "bool" => 1,
                    _ => 4,
                };
                // Every alloc bumps zero-length to >= 1 byte in the
                // runtime, but we report the requested size — n=0 reports
                // 0 bytes, consistent with the formula contract.
                p.n * bytes_per
            })
            .sum()
    }

    fn plan_of(&self, id: NodeId) -> Option<&TensorPlan> {
        self.plans.get(id.0).and_then(Option::as_ref)
    }
}
