//! Version-propagation arm: the mechanical half of `conform bump`.
//!
//! A pin bump is a *de-narrowing event*, not a version edit (contract §7). This
//! module does the deterministic, offline part — rewrite every pin location in
//! lockstep — which `conform bump` then follows with `sync` (restamp the pointer
//! blocks + re-materialize skills) and the executable gates (blocked probes,
//! negatives) run by the CLI. The whole point of the arm is that a bump that
//! skips the restamp leaves the managed-block stamp behind the pin, so
//! `conform audit` (and therefore `conform bump-check`) fails — the exact
//! failure mode that raw direct-to-`main` cascades used to slip past.

use std::fs;
use std::path::{Path, PathBuf};

use crate::audit::{is_installable_version, parse_compiler_pin};

/// Whether a §11 row's primary artifact is regenerated by `conform bump` itself
/// — the pins it rewrites, the managed-block stamps it restamps, and the skills
/// it re-materializes — as opposed to *author follow-up* the bump cannot write
/// (CI wiring, pre-existing doc/citation fixes). Used to categorize the post-bump
/// audit report so a clean retrofit that leaves only follow-up rows reads as
/// success, not a bump failure (chelis#655).
///
/// The set matches exactly what the bump mechanically writes:
/// - pins: [`rewrite_pins`] rewrites `reef.toml` + every workflow env/install;
/// - managed-block stamps: [`crate::scaffold::sync_managed_blocks`] restamps the
///   `agents-inheritance` block (in `AGENTS.md`, row `agents-md`) and the
///   `chelis-surface` block (in `docs/CHELIS_SURFACE.md`, row
///   `chelis-surface`) — and *only* those two blocks;
/// - skills: [`crate::scaffold::materialize_skills`] re-materializes the shared
///   set (row `vendored-skills`).
///
/// It deliberately excludes `pin-bump-checklist` and `scaffolding-drift-rule`:
/// those are plain prose headings from the `init` scaffold template, NOT managed
/// blocks, and `sync_managed_blocks` never rewrites them — so a shell missing one
/// is author follow-up, not a bump defect.
///
/// The check is coarse (keyed on the whole row): rows `agents-md`,
/// `chelis-surface`, and `vendored-skills` also cover author-owned content (a
/// Repo-Identity heading, an exclusion selector, a shell-local block), so a post-bump
/// failure here is treated as blocking without asserting the bump itself
/// malfunctioned. See the caller's report wording.
///
/// Keyed on the stable row `key`, deliberately NOT a field on `ContractRow`:
/// bump-ownership is a property of *this tool*, not of the contract, so it must
/// not ride the doc-locked manifest.
pub fn is_bump_owned(key: &str) -> bool {
    matches!(
        key,
        // pins rewritten by `rewrite_pins`
        "reef-pin" | "workflow-env-pins"
        // managed-block stamps regenerated by `sync_managed_blocks`
        | "agents-md" | "chelis-surface"
        // shared skills re-materialized by `materialize_skills`
        | "vendored-skills"
    )
}

/// A pin rewrite that failed partway, carrying the files it had **already
/// written** (chelis#1263).
///
/// The pin rewrite is the one write step the preflight cannot make
/// all-or-nothing: it edits several files in sequence, and an I/O failure on the
/// second leaves the first rewritten. A bare `String` error made that invisible
/// (the reviewer's read-only-file case exited 1 with `reef.toml` already
/// repinned and nothing but an os error to show for it), so the error type
/// carries the list and the caller enumerates it.
#[derive(Debug, Clone)]
pub struct RewritePinsError {
    pub message: String,
    pub written: Vec<PathBuf>,
}

impl RewritePinsError {
    fn new(message: impl Into<String>, written: Vec<PathBuf>) -> Self {
        RewritePinsError {
            message: message.into(),
            written,
        }
    }
}

impl std::fmt::Display for RewritePinsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

/// Rewrite every pin location under `root` to `new_version`, in lockstep:
/// `reef.toml`'s `compiler = "=X.Y.Z"` and every workflow's
/// `CHELIS_TAG`/`CHELIS_VERSION` env plus `chelisup install` line. Returns the
/// files changed (empty if already at `new_version`); on failure, returns the
/// files it had already written alongside the message.
pub fn rewrite_pins(root: &Path, new_version: &str) -> Result<Vec<PathBuf>, RewritePinsError> {
    // Validate up front so a bump can only ever write a pin the chelisup shim
    // can actually install — otherwise `conform bump garbage` would leave a
    // `compiler = "=garbage"` that audits green but the toolchain cannot resolve.
    if !is_installable_version(new_version) {
        return Err(RewritePinsError::new(
            format!("{new_version:?} is not an installable X.Y.Z version (no `v`, no pre-release)"),
            Vec::new(),
        ));
    }

    // Report paths relative to the shell root: every path a `conform` verb
    // prints is repo-relative, so a reader can act on it without first
    // stripping whatever `--path` happened to be.
    let rel = |p: &Path| p.strip_prefix(root).unwrap_or(p).display().to_string();
    let mut changed = Vec::new();

    let reef_path = root.join("reef.toml");
    let reef = fs::read_to_string(&reef_path)
        .map_err(|e| RewritePinsError::new(format!("read {}: {e}", rel(&reef_path)), Vec::new()))?;
    let old_pin = parse_compiler_pin(&reef).ok_or_else(|| {
        RewritePinsError::new(
            "reef.toml has no `compiler = \"=X.Y.Z\"` pin to bump",
            Vec::new(),
        )
    })?;
    let old = old_pin.trim_start_matches('=').to_string();

    if old != new_version {
        // Rewrite only the `compiler` line under the root/`[package]` table —
        // never a coincidental `"=X.Y.Z"` elsewhere (e.g. a lockstep-versioned
        // `chelis-std = "=X.Y.Z"` dependency pinned to the same version).
        let new_reef = rewrite_compiler_pin(&reef, &old, new_version);
        if new_reef != reef {
            fs::write(&reef_path, new_reef).map_err(|e| {
                RewritePinsError::new(format!("write {}: {e}", rel(&reef_path)), Vec::new())
            })?;
            changed.push(reef_path);
        }
    }

    let wf_dir = root.join(".github/workflows");
    if let Ok(entries) = fs::read_dir(&wf_dir) {
        for e in entries.flatten() {
            let p = e.path();
            let is_yaml = p
                .extension()
                .and_then(|s| s.to_str())
                .is_some_and(|e| e == "yml" || e == "yaml");
            if !is_yaml {
                continue;
            }
            let Ok(body) = fs::read_to_string(&p) else {
                continue;
            };
            let updated = rewrite_workflow_pins(&body, &old, new_version);
            if updated != body {
                if let Err(e) = fs::write(&p, updated) {
                    return Err(RewritePinsError::new(
                        format!("write {}: {e}", rel(&p)),
                        changed,
                    ));
                }
                changed.push(p);
            }
        }
    }

    Ok(changed)
}

/// Rewrite the pin tokens in one workflow body.
fn rewrite_workflow_pins(body: &str, old: &str, new: &str) -> String {
    body.replace(
        &format!("CHELIS_VERSION: {old}"),
        &format!("CHELIS_VERSION: {new}"),
    )
    .replace(
        &format!("CHELIS_VERSION: \"{old}\""),
        &format!("CHELIS_VERSION: \"{new}\""),
    )
    .replace(
        &format!("CHELIS_TAG: v{old}"),
        &format!("CHELIS_TAG: v{new}"),
    )
    .replace(
        &format!("CHELIS_TAG: \"v{old}\""),
        &format!("CHELIS_TAG: \"v{new}\""),
    )
    .replace(
        &format!("chelisup install {old}"),
        &format!("chelisup install {new}"),
    )
}

/// Rewrite the `compiler = "=old"` value to `"=new"` on the `compiler` line
/// under the root or `[package]` table only, leaving every other line — and any
/// coincidental `"=old"` token elsewhere — untouched.
fn rewrite_compiler_pin(reef: &str, old: &str, new: &str) -> String {
    let old_tok = format!("\"={old}\"");
    let new_tok = format!("\"={new}\"");
    let mut in_scope = true;
    let mut out = String::with_capacity(reef.len());
    for line in reef.split_inclusive('\n') {
        let body = line.strip_suffix('\n').unwrap_or(line);
        let trimmed = body.trim();
        if let Some(header) = trimmed.strip_prefix('[').and_then(|h| h.strip_suffix(']')) {
            in_scope = header.trim() == "package";
            out.push_str(line);
            continue;
        }
        let is_compiler_key = trimmed
            .strip_prefix("compiler")
            .is_some_and(|r| r.trim_start().starts_with('='));
        if in_scope && is_compiler_key {
            out.push_str(&line.replace(&old_tok, &new_tok));
        } else {
            out.push_str(line);
        }
    }
    out
}

/// The bare pin (`X.Y.Z`, no leading `=`) recorded in a `reef.toml` text.
pub fn bare_pin(reef_toml: &str) -> Option<String> {
    parse_compiler_pin(reef_toml).map(|p| p.trim_start_matches('=').to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bump_ownership_classification() {
        // The bump's own mechanical output — the two pins, the two managed-block
        // stamps `sync_managed_blocks` restamps, and the re-materialized skills.
        for k in [
            "reef-pin",
            "workflow-env-pins",
            "agents-md",
            "chelis-surface",
            "vendored-skills",
        ] {
            assert!(is_bump_owned(k), "{k} is produced by the bump");
        }
        // Author follow-up — CI wiring, pre-existing docs, and (critically) the
        // `pin-bump-checklist` / `scaffolding-drift-rule` prose headings, which
        // are written only by the `init` scaffold template and NOT restamped by
        // `sync_managed_blocks`, so the bump cannot fix a shell missing them.
        for k in [
            "pin-consistency-guard",
            "tests-neg",
            "tests-blocked",
            "upstream-bugs",
            "staleness-audit",
            "pin-bump-checklist",
            "scaffolding-drift-rule",
        ] {
            assert!(!is_bump_owned(k), "{k} is author follow-up");
        }
    }

    /// Guard the exact managed-block coupling the classification rests on: the
    /// bump-owned managed-block rows must be precisely the rows whose check
    /// verifies a block that `sync_managed_blocks` restamps. If someone adds a
    /// third managed block (or moves one), this fails until `is_bump_owned` is
    /// brought back in lockstep — the same lockstep discipline as the manifest
    /// tripwire, but for tool ownership rather than the doc.
    #[test]
    fn bump_owned_managed_block_rows_match_sync() {
        // The two documents `sync_managed_blocks` restamps map to these rows.
        for k in ["agents-md", "chelis-surface"] {
            assert!(
                is_bump_owned(k),
                "{k} owns a managed block sync restamps, so it must be bump-owned"
            );
        }
        // Prose-heading rows carry no managed block and are never restamped.
        for k in ["pin-bump-checklist", "scaffolding-drift-rule"] {
            assert!(
                !is_bump_owned(k),
                "{k} is a prose heading, not a restamped managed block"
            );
        }
    }

    #[test]
    fn workflow_pin_rewrite() {
        let body = "env:\n  CHELIS_TAG: v0.14.0\n  CHELIS_VERSION: 0.14.0\n  run: chelisup install 0.14.0\n";
        let out = rewrite_workflow_pins(body, "0.14.0", "0.15.0");
        assert!(out.contains("CHELIS_TAG: v0.15.0"));
        assert!(out.contains("CHELIS_VERSION: 0.15.0"));
        assert!(out.contains("chelisup install 0.15.0"));
        assert!(!out.contains("0.14.0"));
    }

    #[test]
    fn bare_pin_extraction() {
        assert_eq!(
            bare_pin("compiler = \"=0.14.0\"\n").as_deref(),
            Some("0.14.0")
        );
        assert_eq!(bare_pin("no pin here"), None);
    }

    #[test]
    fn compiler_pin_rewrite_leaves_lockstep_dependency_alone() {
        let reef =
            "[package]\ncompiler = \"=0.14.0\"\n\n[dependencies]\nchelis-std = \"=0.14.0\"\n";
        let out = rewrite_compiler_pin(reef, "0.14.0", "0.15.0");
        assert!(out.contains("compiler = \"=0.15.0\""));
        assert!(
            out.contains("chelis-std = \"=0.14.0\""),
            "a same-version dependency pin must not be rewritten"
        );
    }

    #[test]
    fn rewrite_pins_rejects_non_installable_version() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("reef.toml"), "compiler = \"=0.14.0\"\n").unwrap();
        for bad in ["garbage", "=0.15.0", "v0.15.0", "0.15", "0.15.0-rc1"] {
            assert!(
                rewrite_pins(dir.path(), bad).is_err(),
                "bump to {bad:?} must be rejected"
            );
        }
        // reef.toml is untouched by a rejected bump.
        assert_eq!(
            std::fs::read_to_string(dir.path().join("reef.toml")).unwrap(),
            "compiler = \"=0.14.0\"\n"
        );
    }
}
