//! The shared agent-skill set, embedded into the toolchain.
//!
//! Contract §8 requires every shell to carry the monorepo's shared skills. In
//! the old model each shell committed a *forked copy* that drifted. Here the
//! canonical bytes are embedded in the binary (below); `conform sync`
//! materializes them into a shell's `agent-skills/` and `conform audit` checks
//! any present copy byte-for-byte against them (fork detection). The shell owns
//! zero skill content — the embedded set for the shell's pinned toolchain is the
//! source of truth.
//!
//! The embedded copies live under `assets/skills/`, regenerated by
//! `scripts/regenerate_conformance_assets.py` from each skill's one authored
//! source: `agent-skills/<name>/SKILL.md` for the compiler repository's own
//! skills, or the package path in [`PACKAGE_SKILLS`] for a downstream skill
//! authored beside its package. [`SHARED_SKILLS`], the `assets/skills/` tree,
//! and those sources must agree, and `tests/asset_drift_tripwire.rs` locks them.

/// The shared skill names every shell receives, sorted. Keep in lockstep with
/// `scripts/regenerate_conformance_assets.py::SHARED_SKILLS`.
pub const SHARED_SKILLS: &[&str] = &[
    "backend-numerics",
    "chelis-std",
    "cli-surface",
    "example-corpus",
    "issue-resolution",
    "packaging-install",
    "phase-gate",
    "redteam-exec",
    "spec-sync",
];

/// Shared skills authored beside the package they teach rather than under the
/// compiler repository's `agent-skills/`, as `(name, repo-relative SKILL.md)`.
/// They guide work in a shell, not on the compiler, so the compiler repository
/// does not load them as its own agent skills.
pub const PACKAGE_SKILLS: &[(&str, &str)] = &[("chelis-std", "packages/chelis-std/SKILL.md")];

/// The repo-relative path of the one authored source for shared skill `name`.
pub fn source_path(name: &str) -> String {
    PACKAGE_SKILLS.iter().find(|(n, _)| *n == name).map_or_else(
        || format!("agent-skills/{name}/SKILL.md"),
        |(_, p)| p.to_string(),
    )
}

/// `(skill-name, SKILL.md contents)` embedded at compile time. One entry per
/// [`SHARED_SKILLS`] name; a new skill needs an entry here plus a re-embed.
pub const EMBEDDED_SKILLS: &[(&str, &str)] = &[
    (
        "backend-numerics",
        include_str!("../assets/skills/backend-numerics/SKILL.md"),
    ),
    (
        "chelis-std",
        include_str!("../assets/skills/chelis-std/SKILL.md"),
    ),
    (
        "cli-surface",
        include_str!("../assets/skills/cli-surface/SKILL.md"),
    ),
    (
        "example-corpus",
        include_str!("../assets/skills/example-corpus/SKILL.md"),
    ),
    (
        "issue-resolution",
        include_str!("../assets/skills/issue-resolution/SKILL.md"),
    ),
    (
        "packaging-install",
        include_str!("../assets/skills/packaging-install/SKILL.md"),
    ),
    (
        "phase-gate",
        include_str!("../assets/skills/phase-gate/SKILL.md"),
    ),
    (
        "redteam-exec",
        include_str!("../assets/skills/redteam-exec/SKILL.md"),
    ),
    (
        "spec-sync",
        include_str!("../assets/skills/spec-sync/SKILL.md"),
    ),
];

/// The embedded `SKILL.md` for `name`, or `None` if `name` is not a shared skill.
pub fn skill_body(name: &str) -> Option<&'static str> {
    EMBEDDED_SKILLS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, body)| *body)
}
