[package]
name = "chelis-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chelis-unord.workspace = true
chelis-deep.workspace = true
thiserror.workspace = true

[dev-dependencies]
chelis-surf.workspace = true
chelis-types.workspace = true
chelis-effects.workspace = true
chelis-ir.workspace = true
