/* Generated by chelis-abi; edit its schema, not this fragment. */
#ifndef CHELIS_RUNTIME_VIEWS_H
#define CHELIS_RUNTIME_VIEWS_H
#include <stdint.h>
#include "chelis_runtime_dtype.h"

typedef struct {
    const void *data;
    int64_t count;
    chelis_dtype dtype;
    uint8_t reserved[7];
} chelis_read_view;
typedef struct {
    void *data;
    int64_t count;
    chelis_dtype dtype;
    uint8_t reserved[7];
} chelis_write_view;
#endif
