/* Generated by chelis-abi; edit its schema, not this fragment. */
typedef struct {
    const void *data;
    int64_t count;
    chelis_dtype dtype;
    uint8_t reserved[7];
} chelis_read_view;
typedef struct {
    void *data;
    int64_t count;
    chelis_dtype dtype;
    uint8_t reserved[7];
} chelis_write_view;
